- .github/workflows/lint.yml
- frontend/.eslintrc
- frontend/.husky/pre-commit
- frontend/.prettierrc.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.test.tsx
- frontend/src/App.tsx
- frontend/src/components/ChatInterface.tsx
- frontend/src/components/Planner.tsx
- frontend/src/components/Terminal.tsx
- frontend/src/index.tsx
- frontend/src/reportWebVitals.ts
- frontend/src/setupTests.ts
- frontend/tsconfig.json
This commit enforces the [Airbnb style guide](https://github.com/airbnb/javascript). The `eslint-config-airbnb` package doesn't support React TypeScript natively, so the `eslint-config-airbnb-typescript` package is needed. `eslint-config-airbnb-typescript` must be installed with `--legacy-peer-deps`, otherwise it throws an error.
We don't have to use Airbnb style, I just chose this because it's the most commonly used.
This commit adds a GitHub action which lints the frontend (`npm run lint`).
This commit uses Husky to install a lint pre-commit git hook via `npm install`.
Resolves https://github.com/OpenDevin/OpenDevin/issues/31
> Add formatting and linting for typescript components

- frontend/.env
- frontend/README.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Terminal.tsx
This pull request instantiates an Xterm terminal, replacing the mock terminal with one functional over WebSocket.
The terminal listens for events over a WebSocket connection. The WebSocket URL is specified by the environment variable `REACT_APP_TERMINAL_WS_URL` (prepending `REACT_APP_` to environment variable names is necessary to expose them).
You can test with a WebSocket server. Below is an echo server for example:
```js
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8080 });
wss.on('connection', (ws) => {
ws.on('message', (message) => {
ws.send(message);
});
});
```
To reproduce,
1. Save the above code snippet in the file `echo.js`
2. Install `ws` (`npm install ws`)
3. Run `node echo.js`
4. Run the frontend and type characters. You should see them being …
> Frontend: Implement real terminal with xterm.js

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/CodeEditor.tsx
This PR adds a `@monaco-editor/react` code panel. If OpenDevin writes code on the backend, this will serve as as a display only. We might want a WebSocket interface for the OpenDevin backend to stream code updates to this editor.
This PR also refactors how tabs are represented in `App.tsx`, reducing code duplication.
Resolves https://github.com/OpenDevin/OpenDevin/issues/38
> Frontend: implement code editor tab

- frontend/src/components/ChatInterface.css
- frontend/src/components/ChatInterface.tsx
- frontend/src/components/CodeEditor.tsx
This PR implements the changes from an [earlier PR](https://github.com/OpenDevin/OpenDevin/pull/26#issue-2190145942) to add an attachment button to the frontend. It also updates the Monaco editor's theme to match the overall UI theme for a consistent look and feel.
> frontend: add attachment button + editor theme update

- agent/build-and-run.sh
- agent/main.py
- agent/regression/run.sh
tiny change
from this comment https://github.com/OpenDevin/OpenDevin/pull/35#discussion_r1531842241
> use argparse in main.py

- frontend/.eslintrc
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Terminal.tsx
- server/server.py
Resolves https://github.com/OpenDevin/OpenDevin/issues/64
Also removes the `xterm-addon-attach` dependency because a custom JSON WebSocket addon is defined to handle our schema instead.
> Fix: Keypresses in Terminal throws exception

- agenthub/codeact_agent/__init__.py
- agenthub/langchains_agent/requirements.txt
- opendevin/README.md
- opendevin/controller.py
- opendevin/lib/actions/read.py
- opendevin/lib/actions/write.py
- opendevin/lib/command_manager.py
- opendevin/lib/event.py
- opendevin/main.py
- opendevin/sandbox/docker.py
- opendevin/sandbox/sandbox.py
- requirements.txt
- server/requirements.txt
This changes the agent CommandManager to use the DockerInteractive sandbox. It also updates the sandbox to use the Docker SDK instead of using `Popen` to run docker commands.
You can run this with:
```
PYTHONPATH=`pwd` python ./opendevin/main.py -d ./workspace -t "write a bash script that prints hello world"
```
One TODO here: it seems impossible to clean up the running docker container on shutdown. The docker SDK tries to block, and we end up with a stack trace.
I also merged the many different requirements.txt here--lmk if we should revert that
> Use Docker SDK for sandbox, integrate into CommandManager

- README.md
Following Robert's suggestions, I add something about MVP roadmap in the next step section.
> update MVP roadmap

- opendevin/sandbox/sandbox.py
In #95 @rbren meantion that we cannot cleanup the docker containers in `__del__` because the python interpreter is already shutting down.
In this PR, I use the [atexit](https://docs.python.org/3/library/atexit.html) package to solve this problem. We can register cleanup functions. Functions thus registered are automatically executed upon normal interpreter termination.
Step:
1. `PYTHONPATH=pwd python ./opendevin/main.py -d ./workspace -t "write a bash script that prints hello world"
` 
2. CMD will output: `Finish cleaning up Docker container`
3. Use `docker ps`, no `sandbox` container.
> fix(evaluation): solve graceful shutdown of docker containers

- frontend/.eslintrc
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/Browser.tsx
- frontend/src/components/ChatInterface.tsx
- frontend/src/components/Terminal.tsx
- frontend/src/index.tsx
- frontend/src/state/browserSlice.ts
- frontend/src/state/chatSlice.ts
- frontend/src/state/socket.ts
- frontend/src/store.ts
Currently, a WebSocket connection is established in the `Terminal` component. This is problematic because WebSocket messages will be used to update the frontend for all types of messages (including chat, code editor, browser, and planner), not just the terminal as per https://github.com/OpenDevin/OpenDevin/issues/44.
This PR moves the WebSocket connection outside of the `Terminal` component so that all WebSocket messages can be propagated appropriately. To handle state changes from WebSocket messages, component state is moved into a Redux store. This also makes component files leaner and achieves better separation of the data layer from the view layer.
**TLDR: this PR adds Redux and refactors the frontend so that all components can make use of a shared WebSocket.**
> Handle WebSockets Across App & Refactor Frontend State

- frontend/src/components/Browser.css
This PR removes extra vertical space from the layout and scales browser screenshot according to window size.
Aims to fix the issue below: 
- https://github.com/OpenDevin/OpenDevin/issues/131
> fix(frontend): Remove extra vertical spacing from layout

- README.md
Some syntax in our code require python >= 3.10
for example: 
```python
def __init__(
self,
workspace_dir: str | None = None,
container_image: str | None = None,
timeout: int = 120,
id: str | None = None
):
```
the python 3.9 cannot recognize `str | None = None`
> doc: add version info

- opendevin/sandbox/sandbox.py
Windows python doesn't have `os.getuid`. This allows us to set it as an env var, or default to 1000
> Fix sandbox user ID on windows

- opendevin/sandbox/sandbox.py
My dev environment is inside an ubuntu container running on my macbook. I mount `/Users/rbren` on my macbook to `/home/rbren` in ubuntu. This causes issues with directory mounting.
This change allows me to specify `DIRECTORY_REWRITE="/home/rbren:/Users/rbren"` to make the volume mounting work properly.
> Add rewrite logic to help with docker-in-docker scenarios

- opendevin/mock/README.md
- opendevin/mock/listen.py
As title. Problem proposed in #133. Add a mock server. Will simply forward every message it got to frontend. Not sure whether this is what team want.
> feat(backend): add mock backend server for frontend

- opendevin/server/README.md
- opendevin/server/session.py
This is what's currently in the README, as this user pointed out: https://github.com/OpenDevin/OpenDevin/pull/234
> standardize on LLM_MODEL env var

- .gitignore
- agenthub/langchains_agent/utils/prompts.py
- opendevin/llm/llm.py
This PR allows you to set `PROMPT_DEBUG_DIR=./debug` to get a record of every prompt and response. This helps agent creators debug their agents.
> add debug dir for prompts

- opendevin/main.py
Currently the command line program does not check for the `LLM_MODEL` env var because it uses the `--model-name` argument to initialize `LLM` object.  Since the argument defaults to gpt-4 if the argument is not specified it will always pass this to the `LLM` constructor and so it never finds the `DEFAULT_MODEL` const `llm.py`
This is just a quick workaround using `or` statement in parser default but probably should be some refactoring with regards to the classes being used by both command line and web app.
> bug: Check for env var in parser argument default value

- frontend/package-lock.json
- frontend/package.json
- frontend/postcss.config.js
- frontend/src/App.css
- frontend/src/App.tsx
- frontend/src/components/Browser.tsx
- frontend/src/components/ChatInterface.tsx
- frontend/src/components/CodeEditor.tsx
- frontend/tailwind.config.js
As discussed in #217 , supported tailwind and daisyUI and made some styling improvements, not perfect but we can keep iterating.
> feat: support tailwind and daisyUI

- frontend/src/App.tsx
- frontend/src/components/BannerSettings.css
- frontend/src/components/BannerSettings.tsx
- frontend/src/services/settingsService.ts
The model and agent selection buttons were accidentally overwritten in https://github.com/OpenDevin/OpenDevin/pull/266. Also, the payload for changing the agent had key `agent`, but the correct key is `agent_cls`.
This PR
1. Adds them back
2. Changes the `agent` key to the correct `agent_cls`
3. Adds a message in chat when a setting is changed
> Re-add banner to App and add change message

- opendevin/sandbox/sandbox.py
- opendevin/server/session.py
1. Fixes #102. Print an error if Docker is not reachable. As docker restart tried in every session, server will automatically recover even if docker bounces.
2. Fixed some python module import order in `session.py` and `sandbox.py`
When docker is not running:
```
INFO:     Started server process [58282]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     ('127.0.0.1', 59155) - "WebSocket /ws" [accepted]
INFO:     connection open
INFO:     Started server process [63469]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     ('127.0.0.1', 60186) - "WebSocket /ws" [accepted]
INFO:     connection open
Failed to stop container: Error while fetching server API version: ('Connection aborted.', PermissionError(13, …
```
> Fix Docker container creation and error handling

- opendevin/sandbox/sandbox.py
Proposed in #179.  
Method: Match the cmd. 
1. Everytime want to kill the cmd, run `ps aux` to get the all thread. 
2. We will save the `cmd` in `BackgroundCommand`, then get the `pid` by comparing the `cmd` prameters. 
3. Then kill it by using `kill -9 pid`. I tried to convert it into `su devin -c kill -9 19`, but will fail. So just will the simple one.
The `for loop` maybe have some performance problem if thread become more and more. But in our current size, i think it is fine.
Result show below:
> fix(sandbox): add get pid code and kill the process

- opendevin/action/fileop.py
- opendevin/controller/agent_controller.py
This was putting `base_path` into the message history, confusing the agent. It'd try and read/write/run things, explicitly specifying the `workspace` dir
> remove base_path from file actions

- frontend/src/services/settingsService.ts
Following https://github.com/OpenDevin/OpenDevin/issues/340,
I've added the option. Maybe should we add all supported models, after careful consideration.
Even better, we could make it a configurable list (via env, or UI directly)
> fix: Add claude-3-opus-20240229 option to settingsService.ts

- opendevin/sandbox/sandbox.py
When I develop the sandbox `python3 opendevin/sandbox/sandbox.py`, will always meet problem:
```
Traceback (most recent call last):
File "/Users/yufansong/code/OpenDevin/opendevin/sandbox/sandbox.py", line 277, in <module>
logs = docker_interactive.read_logs(bg_cmd.id)
File "/Users/yufansong/code/OpenDevin/opendevin/sandbox/sandbox.py", line 149, in read_logs
return bg_cmd.read_logs()
File "/Users/yufansong/code/OpenDevin/opendevin/sandbox/sandbox.py", line 70, in read_logs
chunk, last_remains = self.parse_docker_exec_output(last_remains + data)
File "/Users/yufansong/code/OpenDevin/opendevin/sandbox/sandbox.py", line 52, in parse_docker_exec_output
msg_length = int.from_bytes(prefix[4:8])  # , byteorder='big'
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)
```
It …
> Fix(sandbox): add byte order

- .github/workflows/lint.yml
- Pipfile
- Pipfile.lock
- opendevin/config.py
looks like `tomllib` was only introduced in 3.11, and I'm struggling with it on 3.12
Let's use the older `toml` library for now
> Fix TOML parser

- opendevin/main.py
File Input Support: First up, we've introduced the ability to specify a task through a file. This is super handy when dealing with longer tasks or when you want to keep a record of the tasks being processed. Just use the -f or --file flag followed by the path to your task file, and you're good to go.
Stdin Piping: For those who love their pipes and filters in Unix-like systems, this one's for you. You can now pipe tasks directly into the script from another command. This makes it incredibly flexible when integrating with other tools or scripts. No more temporary files or awkward string manipulations!
Clear Priorities: I've set up a clear priority system for where the script looks for its task input. Command-line arguments come first, then file input, and finally, stdin. This order ensures …
> Support --task-file argument for main.py

- frontend/.env
- frontend/README.md
- frontend/src/components/BannerSettings.tsx
- frontend/src/services/settingsService.ts
- frontend/src/socket/socket.ts
- opendevin/server/listen.py
There are many models supported by LiteLLM. Currently the frontend has a short hardcoded list of model names. This PR has the frontend fetch all LiteLLM model names from the backend.
I'm not sure this is exactly how we should implement it, but with this change the model names list will update anytime we upgrade the `litellm` package.
> Expose LiteLLM model names in backend

- opendevin/llm/llm.py
I had an issue where the prompt was causing a 400 error from the LLM, but I couldn't see the original prompt.
This fixes that issue
> Write prompt debug output before response comes back

- Pipfile
python 3.10 may cause sqlite3 version error.
> fix #375: update python version

- docs/architecture/README.md
This PR adds instructions on how to update the backend architecture diagram.
Goal is to enable all contributors to update the diagram from time to time, until we can fully automate this process (would requires complete type hints, as addressed in #411). 
In the long run these instructions can also be used as a guide to fully automate the process (just put all those steps into a bash script ;) )
> doc: Added instructions to update the backend architecture diagram

- opendevin/sandbox/sandbox.py
OpenDevin currently has trouble installing software, because he's not a sudoer.
Let's make root the default until we figure out a better way to do this
> Run as root by default

- frontend/src/components/ChatInterface.tsx
The user messages were previously blue to differentiate them from the agent messages. This coloring was lost; it is reintroduced in this PR.
Before this PR
After this PR
> Make user messages blue

- .gitattributes
Currently the entire repository is recognized as jupyter notebook due to `*ipynb`, add `.gitattributes` and modify it to ensure consistency.
> add: .gitattributes

- Pipfile.torchidx
- README.md
PyTorch packages in PyPI repository requires CUDA 12 interface.
This makes AMD owners and CPU only owners cannot run OpenDevin.
However, you can select appropriate PyTorch packages according to the GPU you have by changing the index URL of pip repository.
(See: https://pytorch.org/get-started/locally/#start-locally )
This PR added an example of Pipfile that installs torch package which runs on CPU only environment and added a comment on README.md
This PR was tested on Ubuntu 22.04 LTS amd64.
This PR may resolve #437
> Add an Pipfile example for AMD GPU or CPU only users

- opendevin/controller/agent_controller.py
- opendevin/server/session.py
Breaks the task loop on ANY error by propagating error up the stack and returning to caller from coroutine.  The generic message "Error during task loop" is printed to chat.   
Resolves #483
> fix: Handle api key error

- .gitignore
Add files such as requirements.txt, .python-version, bun.lockb, and yarn.lock so that if anybody uses these systems, they don't accidentally push the files
> build: add files created for other dev envs to gitignore 

- opendevin/controller/agent_controller.py
Support disabling color printing as suggested by @rbren in https://github.com/OpenDevin/OpenDevin/pull/176.
It can be achieved by adding `DISABLE_COLOR="true"` to `config.toml`.
> Support disable color printing via environment variable in config.toml

- .gitignore
- Makefile
`make run` does not output any backend logs, leading many people to be unaware that the backend did not start successfully or encountered errors. Now it will output both frontend and backend logs simultaneously.
> fix: let make run output both backend and frontend

- Makefile
**What problem or use case are you trying to solve?**
- Allows for more convenient update of default LLM model in Makefile.  
- Ensures non null config when user does not provide default model.  
- Reduces typing when default model intended by user
- Follows the same pattern as Workspace
> Enhancement: Add default model option to setup-config in Make

- opendevin/server/session.py
Solve #418. Optimize the initialization spped. Also necessary to collect resource in time.
1. This PR will try to close the docker container when website disconnected.
2. In previous logic, the sandbox will not stop when websocket disconnected. It will try to stop and restart it when a new connection comming, which stop process will largely slow down the initialization.
3. If user just refresh the frontend, which means close the websocket and start a new one immediately. it still need 10+s to initialization. We do need 10s to stop and restart te container.
> optimize(sandbox): cleanup docker when disconnect to speed up restart speed

- agenthub/monologue_agent/utils/memory.py
- opendevin/config.py
- opendevin/llm/llm.py
- opendevin/main.py
- opendevin/sandbox/sandbox.py
- opendevin/server/session.py
Solve #392, move all default configuration into config file.
1. Propose we try to use less `get_or_none` and `get_or_default`. If we can give a default value, then configure it in config.py.
2. We set default value in `config.py`, and if user provide value in `config.toml`, the default value will be override.
3. At beginning, I want to move config into a defaul `.toml` file, but find sometimes we need value like `os.path.join(os.getcwd(), "workspace")`. So currently keep it in python code.
> refactor(config): make a single source of truth file

- Makefile
A "fix" for https://github.com/OpenDevin/OpenDevin/issues/655
Using fifo is to allow make run to display the logs of backend and frontend at the same time. If Windows doesn't support it, there don't seem to be any good solutions to achieve a similar effect.
A simple solution is to let make run remind users to use make start-frontend and make start-backend to start separately in Windows.
> fix: make run on Windows

- .github/workflows/lint.yml
- Makefile
- README.md
- frontend/.npmrc
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/scripts/detect-node-version.js
- Use Corepack and the `packageManager` field in `package.json` to specify the package manager and its version.
- This approach helps avoid conflicts caused by different `npm` versions generating different lockfiles.
- Adopt `pnpm` for managing frontend dependencies because:
- `pnpm` is more efficient in terms of disk space usage, and installs faster.
- <img width="683" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/10394160/f0b52ba3-733c-475a-b099-c022a5737a75">
- It maintains a flat `node_modules` file structure.
- Many new and popular frontend projects now use `pnpm`, such as:
- [Vue.js](https://github.com/vuejs/vue)
- [Vite](https://github.com/vitejs/vite)
- For more details on `pnpm` versus `npm`, see: [pnpm vs npm](https://pnpm.io/pnpm-vs-npm).
- Automatically detect …
> chore: use pnpm to manage frontend deps

- frontend/scripts/detect-node-version.js
fix node version compare while `make build` when its exactly 18.17.1
for https://github.com/OpenDevin/OpenDevin/issues/698
> fix: detect corepack node version need to equal minimize

- frontend/.eslintrc
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/ChatInterface.tsx
- frontend/src/components/Input.tsx
- frontend/src/hooks/useInputComposition.ts
- frontend/src/hooks/useTypingEffect.ts
- frontend/src/services/chatService.ts
Before the fix, when users activated an input method (such as Chinese, Japanese, Korean, etc.) and entered composition mode, pressing the Enter key would trigger the `onKeyPress` method in the Input component and ultimately send a message, which was unintended.
After the fix, when users are in composition mode (indicating that they have not finished typing and the input method is still in use), pressing Enter should select the current candidate word (or execute other features of the input method) without triggering the message sending logic of the input component.
Additionally, some optimization work was done, such as:
1. Extracting the input component into a separate file to make the code more focused.
2. Handling the logic where the input should be disabled when the agent has not yet …
> fix: block input send event while ime composition

- Makefile
- agenthub/monologue_agent/utils/memory.py
Updates to makefile and monologue agent memory
- agenthub/monologue_agent/utils/memory.py was using base_url as parameter in call to llama_index.embeddings.openai.OpenAIEmbedding. This was causing an issue when setting the LLM embedding option to OpenAI but not the LLM base url. Also from LlamaIndex docs, that parameter is not needed. I have removed that and place a default model parameter of text-embedding-ada-002
- I have added more embedding model configuration settings in make file for setup-config. This now sets the azure or llama2 needed options if one of those embedding models are selected
> Updating MakeFile and fixing monologue memory parameter issue

- frontend/src/App.tsx
- frontend/src/components/ChatInterface.tsx
- frontend/src/components/Terminal.tsx
- frontend/src/components/Workspace.tsx
- frontend/src/index.css
- frontend/src/types/TabOption.tsx
- frontend/tailwind.config.js
as per this outline [in Figma](https://www.figma.com/file/iM5UBG1lnpg2sgE3cFnF1P/OpenDevin?type=design&node-id=7306-17372&mode=design&t=VzmfRPl4s0z6oDcb-0).
> feat: start implementing new frontend layout

- agenthub/monologue_agent/utils/prompts.py
- agenthub/planner_agent/prompt.py
We had multiple reports of broken JSON from the LLM. I think the presence of markdown in prompts must be what is "breaking" responses in this particular way: the LLM sends back markdown around JSON. We're telling it this is JSON format, and it sure looks like millions of lines associated with JSON it has been trained on. 😆 Just a guess, it just makes some sense to me.
Testing with GPT-3.5, I see over 40% backticks in responses with the current code, and with this, zero. Testing was spot-checking, not exhaustive, but the difference is remarkable.
I'm not sure if GPT-4 has completely solved this, I didn't yet test this one with it.
> Remove md around json

- agenthub/monologue_agent/utils/memory.py
API key parameter missing in call to llama_index.embeddings.openai.OpenAIEmbedding in OpenDevin/agenthub/monologue_agent/utils/memory.py causing a connection error
> fix to pass api key to openai embedding

- .github/workflows/build_run-tests.yml
- Makefile
On mac, Poetry previously auto-installed when it was missing, but didn't install completely due to the path not being set, leaving the user with a confusing "poetry not found" error.
This PR:
1. Makes it so the user has to install poetry manually (because it's probably better for the make file to not make global changes to their system without the user knowing).
2. Provides some instruction on how they can do so.
Fixes https://github.com/OpenDevin/OpenDevin/issues/777
Fixes https://github.com/OpenDevin/OpenDevin/issues/785
> Make poetry install manual and provide user with install instructions

- README.md
Added a Discord logo with a hyperlink to the Discord server invite in the README.md file of the OpenDevin GitHub repository. This enhancement provides users with easy access to join the Discord community directly from the project's README. The Discord logo is linked to the Discord server invite, ensuring seamless navigation for users interested in engaging with the project's community. This update aims to improve user experience and promote community engagement within the OpenDevin project.
> Added Discord Logo with Link to GitHub README

- README.md
This pull request enhances the README.md file by adding a Discord and Slack community link to the OpenDevin project. The addition includes a Discord and Slack logo with a hyperlink to the project's Discord server invite and Slack invite, ensuring easy access for users interested in joining the community. This update maintains consistency with existing style elements, such as badges for other community platforms like Slack. By incorporating the Discord link, this pull request aims to promote community engagement and improve user accessibility within the project.
> Add Discord and Slack Community Link to README #1

- Makefile
- evaluation/regression/README.md
- evaluation/regression/conftest.py
- opendevin/config.py
- opendevin/main.py
- opendevin/server/README.md
In relation to https://github.com/OpenDevin/OpenDevin/issues/449
This PR proposes a simple measure for unexpected costs: default to GPT-3.5. Everyone who wishes GPT-4 can choose it in configuration.
Note that it changes also files in /evaluation, where GPT-4 might make more sense, but user configuration should apply there too.
> Default to a less expensive model

- opendevin/logging.py
Fix the duplicated log printing issue mentioned [here](https://github.com/OpenDevin/OpenDevin/pull/847#issue-2229598945).
As seen above, each logger.info get printed twice, once to the `root` logger, once to the `opendevin` logger.
According to [GPT-4](https://chat.openai.com/share/7caf102c-9058-4e56-bf5d-c5542b63e96f):
> You initially get the root logger using logging.getLogger() with no arguments, and then change its name later. This could be misleading because changing the name of the root logger does not change its behavior or its instance; it just changes a property of the root logger. If other parts of your application or third-party libraries also configure the root logger, it could lead to unexpected results.
In this PR, we create a dedicated `opendevin` logger to resolve this …
> fix(logger): use .getLogger to avoid same logging message to get printed twice

- Makefile
Don't save backend file anymore, for two reasons:
- redundant, since we have now an opendevin.log for the app
- in particular cases liteLLM can still leak sensitive data. That is being fixed [here](https://github.com/OpenDevin/OpenDevin/compare/main...enyst:OpenDevin:log) 
@dorbanianas @rbren
> Don't save backend file

- opendevin/sandbox/Makefile
Version `v0.1.1` will be recognized as `v0.1` minor version in [the Makefile implementation](https://github.com/OpenDevin/OpenDevin/blob/55760ec4ddc669daf4a0b8b36028d2e73c9ab17a/opendevin/sandbox/Makefile#L9-L12), potentially causing the new docker image to fail to build and push to ghcr.
This PR bumps up `v0.1.1` into `v0.2` to fix this issue.
> fix(ghcr image): Bump minor version to fix docker build

- opendevin/config.py
- opendevin/sandbox/sandbox.py
Quick fix the problem #887 introduced in #847. Firstly change the `RUN_AS_DEVIN: 'true'`.
After changing also meet problem like 
```
pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
```
After trying locally with `ssh -p 2222 opendevin@localhost` still will meet. 
So do little change to the docker network setting. (not sure this change from my local env setting, or a wrong docker network configruation)
> fix: change default RUN_AS_DEVIN to true and change some network setting

- opendevin/sandbox/sandbox.py
Now `opendevin` user can run the command with `sudo` in the sandbox. This will largely get rid of the need for OpenDevin to run as root (modified in #895).
> feat(sandbox): Support running sudo in a passwordless manner

- frontend/src/components/Input.tsx
Clicking the send button is still only possible once initialized.
fix https://github.com/OpenDevin/OpenDevin/issues/859
> fix: text input can be edited even if not yet initialized

- opendevin/controller/agent_controller.py
- opendevin/llm/llm.py
- poetry.lock
Upon more investigation on this one, it turns out that:
- our most active upstream, liteLLM, released a patch and fixed some issues with async calls and their Router class.([example](https://github.com/BerriAI/litellm/commit/0d1cca9aa0a853452fa67032e98e670fc43c8598)) The worst behavior that I was seeing is gone. For reference: when you didn't have correct credentials, the errors went on in a loop in the Router constructor (meaning our LLM constructor), and were printing sensitive information. I am not sure I see clearly what exactly fixed it, but I'm not seeing that anymore.
- updated poetry.lock to propagate this version.
- the stop loop in agent controller doesn't work (anymore?). Hot-fixed with a string that works for openai. I am not sure if this might work also for openai-compatible …
> Revert the use of Router, good ole completion works.

- frontend/src/services/fileService.ts
- opendevin/server/listen.py
Issue:
The following endpoint used `json.dumps` as a return for the endpoints
/refresh-files
/select-file
This conflicts with FastAPI's ability to assign the proper response headers causing CORS issues.
Also, the client side handler code was adjusted to work with the FastAPI rendered JSON response.
> Fix Cors issue with files endpoints

- agenthub/monologue_agent/utils/prompts.py
When the response json can't be decoded straight away (the llm included multiple responses),
search the text for all json-looking strings and pick the longest one.
This massively helps with weak llms that include multiple responses in their output.
> Response recognition for weak llms

- agenthub/monologue_agent/agent.py
- agenthub/monologue_agent/utils/monologue.py
- agenthub/monologue_agent/utils/prompts.py
- opendevin/action/__init__.py
- opendevin/agent.py
- opendevin/controller/agent_controller.py
- opendevin/exceptions.py
- opendevin/plan.py
- opendevin/sandbox/exec_box.py
- opendevin/sandbox/ssh_box.py
This PR aims to revamp exception handling, including:
1) Use custom exceptions if needed, especially when callers might need to catch the exception
2) Instance type check failure should throw "TypeError" rather than "ValueError"
3) In agent controller, sleep 3 seconds if APIConnectionError to avoid bursting the LLM backend
4) Avoid LLM-specific exception handling if there's a more generic substitute: E.g. use `litellm.exceptions.AuthenticationError` type check rather than OpenAI specific handling: 'The api_key client option must be set' string match.
Closes #1056
> Revamp Exception handling

- .github/workflows/lint.yml
- dev_config/python/.pre-commit-config.yaml
- poetry.lock
- pyproject.toml
We have a lot of headache with linting this project. Although https://github.com/OpenDevin/OpenDevin/pull/1071 made a first attempt to unify the behavior of local linting and CI linting, it still has the following limitations:
1) The version of pre-commit run locally (pyproject.toml) and that in CI config (lint.yml) are not fixed, and can diverge.
2) The versions of linters (ruff and mypy) are not fixed, which means new releases of these libraries can bring us surprises.
To avoid surprising results on GitHub Actions, e.g. a new release of pre-commit starts to reject all PRs, fix it to the latest version, 3.7.0, in both pyproject.toml and lint.yml. This PR also fixes ruff and mypy versions in pyproject.toml since we very likely don't really need latest upgrades from linters.
> Fix pre-commit and linter versions to avoid surprise

- frontend/src/services/fileService.ts
- opendevin/server/listen.py
In Code Editor, When select a file and then call /select-file, if selected file is deleted, or the file can't be opened with exceptions like encoding problems, current error handling of server side and frontend side are not good, and the failure reason is not clear in frontend.
this pr will fix: https://github.com/OpenDevin/OpenDevin/issues/1028 
server:
frontend:
server:
frontend:
> fix #1028, /select-file api call on deleted file in Code Editor caused Error

- .github/workflows/dogfood.yml
Fixes:
* Use SANDBOX_TYPE=exec, because docker networking in GitHub actions interferes with SSH
* Use docker image rather than build OpenDevin from scratch
> (fix) OpenDevin works on OpenDevin issues

- opendevin/action/agent.py
- opendevin/action/base.py
- opendevin/action/bash.py
- opendevin/action/fileop.py
- opendevin/action/tasks.py
- opendevin/controller/__init__.py
- opendevin/controller/action_manager.py
- opendevin/controller/agent_controller.py
- opendevin/server/agent/agent.py
Went down this path while trying to address https://github.com/OpenDevin/OpenDevin/issues/1164 as well as some comments in the e2b PR
I think we will probably want to pull all the `run()` logic into the ActionManager, and make the actions just dataclasses. It's a little messy, but it'll be less leaky than passing the AgentController into `run`
> Refactor actions a bit

- frontend/package-lock.json
- frontend/package.json
- frontend/src/hooks/useTypingEffect.test.ts
- frontend/src/services/auth.test.ts
- frontend/src/services/session.test.ts
- frontend/src/services/settingsService.test.ts
- frontend/src/utils/storage.test.ts
- frontend/tsconfig.json
- frontend/vite.config.ts
Propose to use the Vitest test runner instead of Jest to reduce times it takes to execute tests. This can also be beneficial for any pre commit/push hooks later on.
> test(frontend): replace Jest with Vitest as the test runner

- agenthub/monologue_agent/agent.py
- opendevin/controller/agent_controller.py
Closes #399.
Suggesting to use the `reset()` method of the agent to solve this.
I chose not to reset the long term memory, with the thought it could be interesting for subsequent tasks. We may want to change this in the future.
> fix: reset context between tasks

- frontend/src/components/CodeEditor.tsx
Syntax highlighting changes based on the extension of the selected file. Uses Monaco editor's path URI field.
(It appears I am unable to add label but "frontend" would be appropriate)
> feat(frontend): syntax highlighting switches to whichever language matches the selected file

- frontend/src/App.tsx
- frontend/src/components/SettingModal.tsx
- frontend/src/services/settingsService.test.ts
- frontend/src/services/settingsService.ts
- frontend/src/services/socket.ts
- frontend/src/types/ConfigType.tsx
- opendevin/config.py
- opendevin/llm/llm.py
- opendevin/mock/listen.py
- opendevin/server/agent/agent.py
- opendevin/server/agent/manager.py
- opendevin/server/listen.py
Fixes https://github.com/OpenDevin/OpenDevin/issues/1167
This ended up being a much bigger change than I hoped. Fortunately most of it is deleted code.
* One really important change is that we always recreate the agent controller when we get an `initialize` event. This gives the frontend the ability to change settings during the same session
* There's a lot of cleanup on frontend localStorage mgmt. We were saving things there that don't really need to be saved (e.g. supportedModels).
* We were also downloading a configuration from the server, and setting that as the initial configuration, which isn't a great pattern--the server was overriding choices the user made in the FE.
* There was a bug where the session wasn't starting properly for brand new sessions, and you needed to refresh the …
> Fix for setting LLM model, frontend settings refactor

- agenthub/monologue_agent/agent.py
- agenthub/planner_agent/prompt.py
- opendevin/action/base.py
- tests/test_action_serialization.py
When we compute embeddings, we're sending duplicate text to get embeddings for. The text of the document looks like this:
`{"action": "think", "args": {"thought": "But I should only use the finish action when I'm absolutely certain that I've completed my task and have tested my work."}, "message": "But I should only use the finish action when I'm absolutely certain that I've completed my task and have tested my work."}`
During a task:
`'{"action": "think", "args": {"thought": "Upon reviewing the script, I suspect there might be an issue either with how the array indices or the element access is done in the bash script. Bash arrays can be finicky and may not support multidimensional arrays directly like other programming languages. I should modify the script to use a different method for …
> Property 'message' sent to llm

- opendevin/action/fileop.py
I believe this fixes https://github.com/OpenDevin/OpenDevin/issues/1164
We were passing FileNotFound exceptions directly back to the LLM, which included absolute paths _outside_ the sandbox. This ensures that the error message only contains the filepath known to the LLM
> handle not found errors inside fileop

- opendevin/action/fileop.py
Python gotcha #3876: `writelines` does not write lines.
> fix file writes

- frontend/src/services/fileService.ts
- opendevin/files.py
- opendevin/server/listen.py
New api endpoint `/api/list-files?relpath=` to facilitate lazy loading of workspace contents for https://github.com/OpenDevin/OpenDevin/issues/1136
* Returns file listing at `relpath` relative to `WORKSPACE_BASE`
* with depth = 1
* blocks traversing outside of `WORKSPACE_BASE`
--
PR doesn't contain UI changes, but here's a reference implementation:
https://github.com/OpenDevin/OpenDevin/assets/8560257/aadd6120-501b-4b3b-a101-c617da726890
> Add new endpoint for shallow file listing - backend only

- frontend/src/services/fileService.ts
- opendevin/files.py
- opendevin/server/listen.py
Removing because the new filetree implementation is fast enough as is and fetching partial trees adds a lot of complexity that we probably don't need. For example, if we still want to automatically open the tree location of a changed file, we need to make sure all the parent folders are fetched first.
> refactor: remove the previously implemented shallow file fetch

- opendevin/controller/action_manager.py
- opendevin/controller/agent_controller.py
- opendevin/llm/llm.py
- opendevin/main.py
The agent often encounters errors, and we're showing a traceback every time. This hides it unless debug logs are on
> less debug info when errors happen

- frontend/src/components/AgentControlBar.tsx
This warning was appended to every PR. While the warningn typically makes sense, in this case we intentionally don't want to rerun if `desiredState` changes.
> style: remove warning about useEffect

- opendevin/config.py
- opendevin/main.py
- tests/test_arg_parser.py
We have two arg parsers that "fight" with each other: one in `config.py` and the other one in `main.py`. Although it doesn't harm the parsing functionality, the coexistence leads to an incomplete help message. To fix this, This PR combines the two partial arg parsers into a single one and puts it in `config.py`.
0356f6e (04/20/2024):
> Fix arg parser help message display

- README.md
fixes #1156 on Ubuntu 22.04, please test on WSL?
> Update README.md:--add-host host.docker.internal=host-gateway

- Makefile
Closes #1225.
`sh` itself does not support double square brackets.
> fix: Use /bin/bash as the shell for Makefile

- .github/workflows/review-pr.yml
- .github/workflows/solve-issue.yml
This PR aims to improve the OpenDevin-powered reviewer bot. Previously, we include the PR diff in the task (prompt), and now we instruct the agent to read from the diff file. This brings the following benefits:
1) The log is now much more concise. Previously, every step would print out the task info, which includes the whole diff that could be large.
2) Interestingly, it seems the agent is better at understanding the content if it's in the diff file, not in the task itself. In my previous PR https://github.com/OpenDevin/OpenDevin/pull/1223, I mentioned that OpenDevin couldn't manage to review https://github.com/li-boxuan/OpenDevin/pull/4, likely because the diff itself contained a lot of prompts and confused the agent. With this new change, OpenDevin is able to provide a …
> DogFood: instruct agent to read from diff file

- docs/guides/LocalLLMs.md
> Set local LLM host to host.docker.internal when running in docker

- frontend/src/i18n/translation.json
Updated the Korean translation for the key "en" in the section where OpenDevin introduces itself, to make it more specific and localized. The previous text was a direct English transliteration, while the new text translates and adapts the message for Korean speakers.
Changed the translation for "Assistant" in Korean from the English word "Assistant" to the Korean word "어시스턴트", which is a transliteration of the English term into Korean script.
> refactor(frontend): modify i18n korean translatiion

- README.md
- docs/README-zh.md
- docs/guides/LocalLLMs.md
It seems the `WORKSPACE_DIR` environment variable has been renamed to `WORKSPACE_BASE`, but the `README.md` files still say `WORKSPACE_DIR`. This PR renames all instances of `WORKSPACE_DIR` to `WORKSPACE_BASE` since `WORKSPACE_DIR` is not referenced anywhere in the code.
There were some automatic formatting changes applied to the `.md` files. I can remove if desired.
> Correct workspace directory config variable in README

- containers/sandbox/Dockerfile
Got an error when trying to run the sandbox today:
ssh_box.py:325 - b'Missing privilege separation directory: /run/sshd\r\n'
There is a bug with the sandbox, and rebuilding it with the ssh service start line, for no apparent reason, worked. (forcing sshd to make that directory, presumably)
Needs confirmation, it's a weird one, and I also did other things when my system didn't want to start opendevin. 
https://askubuntu.com/questions/1110828/ssh-failed-to-start-missing-privilege-separation-directory-var-run-sshd
https://askubuntu.com/questions/1109934/ssh-server-stops-working-after-reboot-caused-by-missing-var-run-sshd/1110843#1110843
May fix #1294
> Bug with sshd

- evaluation/regression/conftest.py
fix conftest.py compile bug, comment close """ wrong：
> fix: conftest.py comment bug.

- containers/build.sh
this PR will resolve the unknown os/arch in ghcr.io
to
> Disable additional Docker metadata to more compatible with OCI spec.

- docs/guides/LocalLLMs.md
Installing ollama in wsl and potentially other linux setups will not publicly host ollama from your machine.
I added a section on how to identify the problem and how to fix it by changing the ollama config to host 0.0.0.0:11434 and allowing any origins.
> doc: Add ollama wsl section to LocalLLMs.md

- opendevin/action/fileop.py
- opendevin/controller/agent_controller.py
Fixes #326 
Added checks for some common cases of infinite loops. If any of these are repeated three times, call it stuck and stop the task.
- (NullAction, same Observation)
- (same Action, NullObservation)
- (same Action, AgentErrorObservation)
The first two are too common. Not too sure about the third, but I didn't add (same Action, any Observation) because it seemed it might catch too much 🤔 
Notes:
- tested with console alone atm.
- it's easy to get the 2nd with GPT-3.5, and in that case it doesn't actually mean infinite. Sure, it won't solve the task if it's having such trouble, but it could still change next step. Maybe make it 5 times instead of 3?
> Add checks to stop infinite loops

- opendevin/action/__init__.py
- opendevin/exceptions.py
Send the failed decoding of an action, probably missing an argument, back to the LLM
> Send the failed decoding back to the LLM

- opendevin/sandbox/docker/ssh_box.py
In `DockerSSHBox,` sometimes the previous execution observation will come out in subsequent `ssh.before.decode`, which causes (1) exit code reading sometime to fail, and/or (2) output of a previous command to come out in a subsequent command. This PR tries to fix it.
> fix(sandbox): SSH box `.execute` misalign issue

- opendevin/action/fileop.py
- tests/test_fileops.py
Without this the LLM is free to write or read any file accessible by the back-end process, even those outside of the workspace. This is less of a concern when the back-end is used inside of a docker container, but can be seriously damaging when run in a dev environment outside of a container.
> fix(backend): Prevent llm path traversal with fileop actions.

- frontend/README.md
**Summary**
Include the `npm run make-i18n` script that should be run during first time setup or any updates to translations.
> docs(frontend): improve format and extend to include i18n scripts

- opendevin/config.py
- opendevin/sandbox/docker/ssh_box.py
The default for `WORKSPACE_MOUNT_PATH` is None, which causes issues when try to map it into SSHBox.
Right now, `SSHBox` first read for `WORKSPACE_MOUNT_PATH` then `WORKSPACE_BASE`.
Based on our README.md, it seems to me that both of these variable means the same thing. Can we merge them together into one variable (i.e., we keep `WORKSPACE_MOUNT_PATH` and remove `WORKSPACE_BASE`)?
```
...
-e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
-v $WORKSPACE_BASE:/opt/workspace_base \
...
```
> fix(sandbox): `mount_dir` for ssh_box

- .github/workflows/build_run-tests.yml
macos builds are broken, seems like maybe there were recent changes to 14: https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
> Pin macos to 13

- agenthub/SWE_agent/agent.py
SYSTEM_MESSAGE role should be set to system, not user.
> fix: sweagent prompt message SYSTEM_MESSAGE role set to user bug.

- containers/app/Dockerfile
- opendevin/config.py
- opendevin/sandbox/docker/ssh_box.py
This PR switch back to using `--network=host` as a default.
The `--network=host` is now supported with the newest version of Docker Desktop for MacOS - this was the only reason iirc that stopped us from using it before.
> Version Docker Desktop 4.29.0
Settings ⇒ Features in development ⇒ Enable host networking
Host networking allows containers that are started with --net=host to use localhost to connect to TCP and UDP services on the host. It will automatically allow software on the host to use localhost to connect to TCP and UDP services in the container. Sign in required.
_Originally posted by @4-FLOSS-Free-Libre-Open-Source-Software in https://github.com/docker/roadmap/issues/238#issuecomment-2044688144_
> Default for sandbox to use the host network

- opendevin/action/fileop.py
Send the permission error when trying to access a file outside of workspace back to the llm, with a message about the format.
> Send the permission error to the llm

- opendevin/config.py
I'm unable to get `main` to work with host network, even on the lastest Docker Desktop `4.29.0`.
I think we need to revert this until it's out of beta.
> Go back to not using host network by default

- opendevin/sandbox/docker/ssh_box.py
CC @xingyaoww 
I think this mount breaks the DOOD setup that we recommend in the README. I'm going to remove it for now, but let's talk about what a better solution looks like. Maybe we can mount to `/tmp` by default?
> Temporarily remove CACHE_DIR from sandbox

- opendevin/sandbox/docker/exec_box.py
- opendevin/sandbox/docker/local_box.py
I found this while working on #1301. #1304 includes a minor change to ssh sandbox: the command output is stripped before returning. Meanwhile, other sandboxes don't strip the output. This PR fixes this trivial behavior difference, which is not important to most people.
> Fix output strip behavior discrepancy among sandboxes

- opendevin/config.py
- opendevin/sandbox/docker/ssh_box.py
For some reason, without cache dir, `python3 opendevin/sandbox/docker/ssh_box.py` will timeout during `~/.bashrc`.
> Add back cache dir and default to /tmp

- opendevin/config.py
Docker will throw errors if the default `WORKSPACE_MOUNT_PATH` is not abspath
> make default WORKSPACE_MOUNT_PATH as abspath

- opendevin/mock/listen.py
Currently, the mock server is broken because several of the API endpoints aren't implemented. Also, the endpoints were moved under the `/api` route, which hasn't been updated in the mock server. This causes the frontend to crash with a blank page.
This PR fixes the mock server to work properly.
> Fix mock server

- frontend/src/components/ChatInterface.tsx
- frontend/src/components/markdown/code.tsx
Inspired by but does not complete #1399 
- Language-specific syntax highlighting to code-blocks (e.g., ```py).
- Y overflow is bounded to the chat bubble and not the entire chat interface
> feature(frontend): improve chat overflow handling and syntax highlighting

- tests/integration/README.md
This PR fixes a typo in the integration tests README.md.
The first draft was entirely authored and pushed to github by OpenDevin! :) For proof, see the video below:
Video:
https://drive.google.com/file/d/1qCJzKARAV-6JRd-9fRwyV5G9K7c3ytLP/view?usp=sharing
Fixes: https://github.com/OpenDevin/OpenDevin/issues/1433
> Fixed typo in integration tests README.md

- dev_config/python/.pre-commit-config.yaml
The project does not have any `setup.cfg` (look for it with `find . -name "setup"`) so there is no need to keep this hook
cc: @rbren, @li-boxuan
> precommit: remove unused `setup-cfg-fmt`

- frontend/src/components/ChatInput.test.tsx
- package-lock.json
The behavior of how `ChatInput` disables the `textarea` element changed in #1353, resulting in a failing test. This PR updates the test to pass according to this new behavior.
> test(fronted): update chat input tests to according to new behavior

- frontend/src/components/modals/settings/AutocompleteCombobox.test.tsx
- frontend/src/components/modals/settings/AutocompleteCombobox.tsx
This PR fixes the issue presented in #1442. The issue was the `<Autocomplete>` component from nextui was expecting a key that exists in the items it uses to display the combobox values. If a custom value was inputted, it did not display because it didn't exist in the provided items.
Instead of setting the default key in the props, this PR fixes the issue by setting a default *value* that is found by the provided key and fallbacks to the key itself (actually the value).
Also extends the test to ensure this behavior.
> fix(frontend): fix custom llm model value not displaying

- .github/workflows/run-unit-tests.yml
- Development.md
- opendevin/sandbox/docker/ssh_box.py
- tests/unit/test_arg_parser.py
- tests/unit/test_sandbox.py
This PR is an updated version of https://github.com/OpenDevin/OpenDevin/pull/1432. The previous one had too many issues with rebase and merging with `main,` so I'd think just restart a clean one.
- Revert SSHBox implementation change in https://github.com/OpenDevin/OpenDevin/pull/1417, which does not pass all the unit tests (it causes failure for CodeActAgent when `source ~/.bashrc`.
- Add docs and instructions for unit tests.
**NOTE**: we need to run unit tests for `test_sandbox.py` separately. `test_sandbox.py` needs to import OpenDevin modules in the fixture. Running it together with another file will cause it to re-use the imported module and loaded config from other modules, hence causing errors.
> Revert ssh box implemetation, fix multi-line command issues and add unit tests

- opendevin/config.py
Add ConfigType.SANDBOX_USER_ID into DEFAULT_CONFIG to ensure such item be overwritten by environment variables or config.toml correctly.
> fix: configurable sand box user id

- frontend/src/components/modals/settings/SettingsForm.test.tsx
- frontend/src/components/modals/settings/SettingsModal.test.tsx
- frontend/src/components/modals/settings/SettingsModal.tsx
- frontend/src/services/settings.test.ts
- frontend/src/services/settings.ts
- package-lock.json
Changes introduced in #1319 caused the settings test to fail because they did not take into account the new property. They have since been updated to do so.
- A test in settings modal failed because the modal did not save settings due to its implementation. There were some cases where the save button would be disabled when API key was empty, because any empty input resulted in disabling the button. Of course this is not desired with the new change, so the `isDisabled` logic has been updated to take into account the api key.
- Removed `package-lock.json` from root (accidentally added from a previous commit)
> (refactor|fix|test)(frontend): update tests after setting modals upgrade

- frontend/src/components/modals/settings/SettingsModal.tsx
- Added an array for storing sensitive keys we don't want to expose in plaintext.
> Fix API key exposure in toast notifications, resolves #1477

- .github/workflows/ghcr.yml
- containers/app/Dockerfile
- containers/app/entrypoint.sh
- containers/build.sh
Apparently the existing check to see if we were on a fork was always (?) false--don't believe everything you read on Stack Overflow!
Seems there might be some flaky issues with `--push`, I believe as a result of https://github.com/OpenDevin/OpenDevin/pull/1426
From what I've gathered, running `chown` on a big directory creates a huge layer, and big layers seem to cause issues w/ GitHub actions. This uses the more efficient `COPY --chown` method
I'm also removing the "Free Disk Space" bit, because it _shouldn't_ be necessary (we have 20GB), and takes a little while.
> Fix docker push for non-forks

- .github/workflows/lint.yml
https://github.com/OpenDevin/OpenDevin/pull/1457 made a change so that we only lint changed files. But the logic isn't happy when running on the main branch--we get this error: https://github.com/OpenDevin/OpenDevin/actions/runs/8923448020/job/24507727023
This PR disables pre-commit checks on the main branch. Not ideal, but good enough for now
> Fix linting on main branch

- frontend/src/components/AgentControlBar.tsx
- opendevin/server/agent/agent.py
Prerequisite: merge https://github.com/OpenDevin/OpenDevin/pull/1516
Fix https://github.com/OpenDevin/OpenDevin/issues/1492#issuecomment-2090316167
> fix(controller): "Current task state not recognized"

- agenthub/micro/agent.py
This removes the `BrowserObservation` screenshot from the microagent prompt.
Fixes https://github.com/OpenDevin/OpenDevin/issues/1545
This is based on what we do in MonologueAgent:
https://github.com/OpenDevin/OpenDevin/blob/91c8f1cb3f16904bac79f548bc1474c8601403f8/agenthub/monologue_agent/agent.py#L117
We might also consider making this a more general utility function in the future (converting history to text).
UPDATE: This is still buggy, will convert to an issue and ping when it's fixed.
> Remove screenshot from microagent prompt

- containers/build.sh
We haven't been using `v`, so removing this for consistency (and to fix the major/minor tags)
> Remove `v` prefix on tags

- opendevin/runtime/docker/exec_box.py
- opendevin/runtime/docker/ssh_box.py
When multiple users are debugging OpenDevin on the same machine, operations on the same instance may occur due to identical sid. Therefore, random unique identifiers are applied to sid here to avoid such conflicts.
> fix the issue where session id might be duplicated

- containers/app/Dockerfile
- containers/app/entrypoint.sh
- opendevin/runtime/plugins/jupyter/__init__.py
Was trying out `main` but running into UID issues.
This PR makes a few changes:
* create a separate `enduser` user, which uses the UID passed in at runtime
* create an `app` group, which both `opendevin` and `enduser` belong to
* change UID_MIN to something compatible with OS X
* chmod everything so that it's group-readable
I've verified that:
* App starts in docker
* Browser starts up OK
* Files created by agent have the end-user's UID
> Fix user permissions in docker

- frontend/src/i18n/translation.json
Hello, like #1157, this PR adds the translation of Traditional Chinese.
(It seems that some sentences were translated in #947, but due to changes in the source file, some additional sentences were not translated.)
Also, I'm not quite sure why "Agent" should be translated as "智能體" (intelligent body), but since that's how it was translated before and in zh-CN, for the sake of consistency, I decided to stick with this translation for the term.
Thank you for review this PR! Hope it can be merged quickly!
> i18n: translation of zh-TW

- frontend/src/i18n/translation.json
"畀助手發消息" feels more like Cantonese than standard Mandarin, also, some zh-CN translations have been added.
> i18n: Fix and add zh-CN 简体中文 

- frontend/src/components/Workspace.tsx
Currently, all agents display the same tabs, and some tab functionalities are yet to be implemented, which can confuse users and increase their learning curve. Therefore, I have customized the tab pages for commonly used agents, while other agents still display all tab pages。
MonologueAgent: [FileEditor, Browser],
CodeActAgent: [FileEditor, IPython],
others: AllTabs
> feat: customize the tab list displayed for different agents

- frontend/src/components/chat/ChatInterface.test.tsx
- frontend/src/components/chat/ChatInterface.tsx
- frontend/src/services/chatService.ts
Updates the tests according to changes made in #1538.
The test `it("should render the new message the user has typed")` no longer fails due to the Redux store not updating. The dispatch was called outside the component with the `store` object directly. We end up have more than one store in the app, [which is not advised](https://redux.js.org/faq/store-setup#can-or-should-i-create-multiple-stores-can-i-import-my-store-directly-and-use-it-in-components-myself).
- Removed the need for preloaded task state (removal of `initialized` from `taskSlice`)
> test(frontend): update unit tests

- opendevin/events/action/__init__.py
Check action['action'] instance type to avoid undesired llm outputs, which may cause runtime type error.
> fix: check action['action'] instance type before parsing action cls

- agenthub/micro/instructions.py
For file (not directory) in _instructions, right now just `history_truncated.md`, the `instructions` is not set correctly: 
and the `{{ instructions.history_truncated }}` in prompt template will not be rendered.
> fix: file in _instructions directory not set correctly.

- agenthub/delegator_agent/agent.py
Coder and Verifier isn't the correct name, it will throw exception like `opendevin.core.exceptions.AgentNotRegisteredError: No agent class registered under 'Coder'`
> fix: delegateAgent select micro agents name bug.

- agenthub/codeact_agent/codeact_agent.py
- agenthub/codeact_agent/prompt.py
- tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_002.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_003.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_004.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_005.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/response_001.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/response_002.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/response_003.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/response_004.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/response_005.log
Try to resolve https://opendevin.slack.com/archives/C06U8UTKSAD/p1714948281521449
Where the agent installed a new package via `pip` install bash but cannot import the same package in the `IPython` shell.
This PR partially mitigate this by adding an instruction to tell the agent to restart IPython kernel after install, per instruction here: https://github.com/jupyter/notebook/issues/2359#issuecomment-291006199
> Fix the issue of newly import package by including instruction for Kernel restart

- agenthub/micro/agent.py
- agenthub/micro/typo_fixer_agent/agent.yaml
- agenthub/micro/typo_fixer_agent/prompt.md
- tests/unit/test_response_parsing.py
This pull request introduces a new micro-agent named TypoFixerAgent that scans file(s) with the given path and corrects typos in-place. The agent completely rewrites the document to ensure all identified typos are corrected.
- Added `TypoFixerAgent` in `agenthub/micro/typo_fixer_agent/agent.py`.
- Implemented the agent using an approach where the document is completely rewritten with typos fixed.
- Modified the `parse_response` function in `agenthub/micro/agent.py` to more accurately extract the first complete JSON object from responses. This change improves the agent's ability to handle multiple JSON objects, ensuring more reliable parsing and processing.
Fixes #1514
https://github.com/OpenDevin/OpenDevin/assets/5805397/3826bee4-dfeb-4937-af60-219b25aa16d1
The earlier version of …
> Introduce TypoFixerAgent for in-place typo corrections in agenthub/micro

- Makefile
Title: Add Support for Manjaro and Arch Linux in Makefile
Description:
This pull request enhances the Makefile to provide better support for Manjaro and Arch Linux distributions. The following changes have been made:
1. Added detection for Manjaro Linux in the check-system target:
If the /etc/manjaro-release file exists, it indicates the presence of Manjaro Linux.
A specific message is displayed when Manjaro Linux is detected.
2. Modified the install-python-dependencies target to handle Playwright dependencies on Manjaro Linux:
If Manjaro Linux is detected, the Playwright dependencies are installed separately using poetry run pip install playwright and poetry run playwright install chromium.
This ensures that the necessary dependencies for Playwright are properly installed on Manjaro …
> Updated Makefile to support Manjaro / Arch linux hosts

- .github/workflows/run-unit-tests.yml
- Makefile
- Unable to move `test_sandbox.py` to `tests/integration` due to its specialized test environment, so a new step was added to the unit test workflow.
- Implemented the changes discussed in https://github.com/OpenDevin/OpenDevin/pull/1460#issuecomment-2090137426.
> feat(makefile): add capability to skip Docker image pull

- tests/integration/regenerate.sh
- tests/integration/test_agent.py
There's no need to regenerate integration tests artifacts if the test still passes.
> Only regenerate integration test artifacts for failed tests

- Makefile
- evaluation/regression/README.md
- evaluation/regression/conftest.py
- opendevin/core/config.py
- opendevin/server/README.md
Description:
This PR changes the default LLM model from **gpt-3.5-turbo-1106** to **gpt-3.5-turbo**. The **gpt-3.5-turbo** model is half the price of **gpt-3.5-turbo-1106** on input tokens while providing similar performance if not better and with 25% cheaper output. Defaulting to the less expensive model provides a simple way to reduce unexpected costs for users who don't need the more expensive model.
**gpt-3.5-turbo-1106**
**gpt-3.5-trubo**
**currently gpt-3.5-turbo points to gpt-3.5-turbo-0125**
**NOTE:** In my evaluations using **Advent of Code** in different languages and different years [my dataset with correct answer of all challenges for all years for my specific input](https://huggingface.co/datasets/isavita/advent-of-code) **gpt-3.5-turbo-0125** is noticeably better than …
> Default to less expensive gpt-3.5-turbo model

- opendevin/events/action/action.py
- opendevin/events/action/agent.py
- opendevin/events/action/browse.py
- opendevin/events/action/commands.py
- opendevin/events/action/files.py
This PR proposes to use ClassVar[bool] instead of the runnable property. Despite being in theory a static type hint, ClassVar is read by `@dataclass` and it does a couple of things at runtime:
- doesn't add it to `fields`, which are "true" instance vars
- doesn't add it to `__init__` and other methods that would lead to mypy upset about order of args with default values and without
- doesn't add it in `asdict()` or similar, although it can be accessed with `get_type_hints` (and it will say ClassVar)
All of those were true with it as property, and expected as a class var ("true class var"). It will be inherited as a class var, and it will be accessible for reading via an instance, so `action.runnable` works as it did.
Mypy will be upset now if we ever try `action.runnable = True`, via an …
> Runnable action

- opendevin/server/agent/agent.py
**Small improve performance**
- [Minimizing the usage of instanceof checks ]
- [uses a combined isinstance check for both NullAction and NullObservation ]
> perf : optimizations to send event logging performance

- .github/workflows/deploy-docs.yml
In folk repos, there's no github actions enabled,  the deploy-decs [build] job will be runned(but not used...) and the [deploy] job will be failed:
> feat: skip deploy-docs in folk repos.

- README.md
The argument `--add-host host.docker.internal:host-gateway` should be `--add-host host.docker.internal=host-gateway` (with an `=` character).
Solves `Error creating controller: Could not establish connection to host` errors.
> docs: fixed typo in launch command

- agenthub/micro/agent.py
- agenthub/monologue_agent/utils/prompts.py
- agenthub/planner_agent/prompt.py
- opendevin/core/utils/json.py
- tests/unit/test_response_parsing.py
- move json utility additions to the custom json parsing
- apply it to the monologue-like agents, planner, monologue, micro
- for monologue, this replaces the attempt to use the lengthiest JSON string with an attempt to use the first JSON 
(CC: @isavita )
> Use custom JSON with repairs in monologue-like agents

- opendevin/runtime/docker/exec_box.py
- opendevin/runtime/docker/local_box.py
- opendevin/runtime/docker/ssh_box.py
- opendevin/runtime/e2b/sandbox.py
- opendevin/runtime/sandbox.py
This is part of the modification in https://github.com/OpenDevin/OpenDevin/pull/1468.
This PR allows `.execute` of all sandbox to accept an additional argument (`timeout`) which can override the default `self.timeout` specified at the initialization time of the sandbox.
It is required when setting up the evaluation environment: for some repo like `sympy`, the initialization takes several minutes for python setup and compilation, making it necessary to support manually set a longer timeout for such initialization command.
> Support specify timeout for long running tasks

- tests/integration/regenerate.sh
This PR adds an echo to print out the command that is used in the "regenerate" script to generate tests, allowing devs using this script to debug more easily.
> Print out the regenerate command

- README.md
This PR updates the README to correct the format of the `--add-host` flag used in the Docker run command in the README. 
The previous format `host.docker.internal=host-gateway` was incorrect and resulted in the following error: 
> invalid argument "host.docker.internal=host-gateway" for "--add-host" flag: bad format for add-host: "host.docker.internal=host-gateway" Use code with caution.
This PR fixes the issue by updating the flag to the correct format: `--add-host host-gateway:host.docker.internal`. This ensures that the Docker container can correctly resolve the host.docker.internal hostname to the host machine's gateway IP address.
> Fix: Correct `--add-host` Flag Format in README

- tests/integration/conftest.py
Sometimes the test would still pass even if the prompts don't match, either because OpenDevin actually has already finished the task before itself declares success, OR the test assertions are too loose.
We should exit early so that bugs (that cause prompt mismatch) can be uncovered earlier.
> Integration test: exit if no prompt match

- opendevin/runtime/docker/ssh_box.py
Sometimes during eval, the SSHBox parsing will throw errors like: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 982751: invalid start byte`.
This PR follows https://github.com/pexpect/pexpect/issues/381 to set `codec_errors='replace'` to turn unknown bytes into the unicode replacement character to avoid crashing the whole `pxssh`.
> Fix(sandbox): utf-8 decoding issue

- frontend/src/services/observations.ts
- frontend/src/types/Message.tsx
- opendevin/runtime/browser/browser_env.py
Fixed the screenshot not showing up in frontend.
Allow browsing observations to contain links so that the agent could follow through URLs
> Fix frontend browsing screenshot not showing bug, allow link following in markdown

- opendevin/core/config.py
- tests/unit/test_config.py
Setting workspace_mount_path to workspace_base was lost in the recent refactoring, this PR restores it. Also default workspace_base to ./workspace.
> Fix workspace paths defaults

- opendevin/core/main.py
In the evaluation, I found that the number of browser processes will increase as the evaluation progresses -- until it brings the system to OOM.
I think This PR might fixes this by properly clean-up runtime resource when `main` finishes.
> fix: close runtime after main completion

- agenthub/codeact_agent/README.md
I found out that original CodeAct paper link in CodeAct README.md file is not correct, so I make it correct.
> doc: make CodeAct paper link correct

- .github/.codecov.yml
Currently, CodeCov rejects a PR if its coverage is more than 10% lower than project coverage. Sometimes a PR is either hard to test, or cannot be tested completely, especially for small PRs. Although codecov check doesn't block the PR and one can still merge it, it is truly annoying.
This PR allows the patch/PR coverage to be zero - effectively allowing any PR as long as it doesn't decrease the whole project's coverage by 5%.
> Allow code coverage to be zero for PRs

- opendevin/runtime/docker/ssh_box.py
I have seen this many times, both locally and on CI. Although the chance is low (less than 10% for me), sometimes OpenDevin fails to start a ssh session, and exits without shutting down containers, leaving them as zombies. This PR makes sure the close method is called before it shuts down.
With this PR, when the program exits due to ssh connection error, the container correctly exits:
Just to show you there's no running container now:
> ssh_box: Shutdown container when fail to start ssh session

- .github/.codecov.yml
I find these make it harder to review code
> remove codecov annotations

- docs/src/pages/faq.tsx
Fixes #1828
------
This PR was entirely written by OpenDevin using GPT-4o. I had to send three corrections (in English) to fix mistakes, which you can see in the commits. Here were my prompts:
prompt 1
```
Please fix a github issue according to the following procedure:
Read the issue on https://github.com/OpenDevin/OpenDevin/issues/1828
Clone the repository and check out a new branch
Based on the instructions in the issue description, modify files to fix the issue
Push the resulting output to github using the GITHUB_TOKEN environment variable for authentication
Tell me the link that I need to go to to send a pull request
```
prompt 2
```
Thanks, this is a great start! But note that the user of OpenDevin does not need to perform these steps themselves, but rather needs to send a prompt to …
```
> Add documentation regarding how to fix github issues with OpenDevin

- opendevin/controller/agent_controller.py
- opendevin/runtime/docker/ssh_box.py
Solves
```
18:17:31 - ACTION
**CmdRunAction**
COMMAND:
echo "#!/bin/bash
edit 1:1 <<EOF
Updated Storybook
EOF" > tmp_script.sh; bash ./tmp_script.sh
Traceback (most recent call last):
File "/mnt/c/Users/smart/Desktop/GD/OpenDevin/opendevin/controller/agent_controller.py", line 105, in _start_step_loop
await self._step()
File "/mnt/c/Users/smart/Desktop/GD/OpenDevin/opendevin/controller/agent_controller.py", line 231, in _step 
await self.event_stream.add_event(action, EventSource.AGENT)
File "/mnt/c/Users/smart/Desktop/GD/OpenDevin/opendevin/events/stream.py", line 87, in add_event
await fn(event)
File "/mnt/c/Users/smart/Desktop/GD/OpenDevin/opendevin/runtime/runtime.py", line 88, in on_event
observation = await self.run_action(event)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> fix: Handle invalid exit code conversion

- agenthub/SWE_agent/agent.py
- agenthub/codeact_agent/codeact_agent.py
- agenthub/micro/agent.py
- agenthub/monologue_agent/agent.py
- agenthub/planner_agent/agent.py
- opendevin/controller/agent_controller.py
- opendevin/controller/state/state.py
- opendevin/core/metrics.py
- opendevin/llm/llm.py
- opendevin/memory/condenser.py
- tests/unit/test_micro_agents.py
As mentioned in #1913, we need find a better way to log the cost of LLM. 
1. I create a `Metrics` class. We have already have `logger` class in opendevin, but have no way to record the metrics.
2. I add `total_cost: float` `costs: list` vairable in `Metrics`. 
3. `Agent`-> `LLM` -> `Metrics`, then every agent will be recorded how much they spend.
4. `State` -> `Metrics`, then agent will update the latest metrics into state when `step`.
5. Do little refactor on `completion` function as `do_completion`, then when every agent call it in `step`, it will auto calculate the cost, accumulate cost, record cost, and log it out.
> feat: add metrics related to cost for better observability

- opendevin/events/stream.py
After session persistently stored， it will try to _reinitialize_from_file_store, but for a fresh new session which means no Persistent storage files will throw exceptions when init EventStream, or Persistent storage files removed from s3, the EventStream init flow brokes.
> fix session file not existed exception when init EventStream with a new session.

- evaluation/swe_bench/BUILD_TESTBED_AND_ENV.md
- evaluation/swe_bench/EVAL_PATCH.md
- evaluation/swe_bench/README.md
- evaluation/swe_bench/run_infer.py
- evaluation/swe_bench/scripts/docker/Dockerfile.full.v1.1
- evaluation/swe_bench/scripts/eval_infer.sh
- evaluation/swe_bench/swe_env_box.py
For some reason, the current swe-bench sandbox stopped working for `astropy` now:
I chased down to the original repo of `setuptools`, looks like `dep_util` was deprecated: https://github.com/pypa/setuptools/blob/v69.5.1/setuptools/dep_util.py#L5-L16
In particular, there's a May 21 date:
I added a fix to the `OD-SWE-Bench` fork: https://github.com/OpenDevin/OD-SWE-bench/commit/3bc7c55144f1b4ae8c85bdcecd163c8b6767ee41
I also re-build a new SWE-Bench container `v1.1` and pushed to up. This PR bumps the version of the used container.
> Fix SWE-Bench evaluation due to setuptools version

- tests/integration/mock/MonologueAgent/test_write_simple_script/prompt_001.log
- tests/integration/mock/MonologueAgent/test_write_simple_script/prompt_002.log
- tests/integration/mock/MonologueAgent/test_write_simple_script/prompt_003.log
- tests/integration/mock/MonologueAgent/test_write_simple_script/prompt_004.log
Integration tests have broken, likely because we didn't set successful status of integration tests as mandatory gates for merge.
I'll look into how to correctly set up GitHub checks later...
> Fix integration tests broken by recent PR

- opendevin/runtime/docker/ssh_box.py
In some rare occasions (e.g., when the sandbox is started, but the `sshd` inside the sandbox is not ready), `pxssh.pxssh` will raise issues of `pexpect.pxssh.ExceptionPxssh: Could not establish connection to host`.
This can be typically addressed by sleeping for a few more seconds and retrying. This PR addresses this issue by adding this logic.
> Fix ExceptionPxssh by adding retries when ssh into container

- opendevin/runtime/plugins/agent_skills/agentskills.py
- tests/integration/mock/CodeActAgent/test_edits/prompt_001.log
- tests/integration/mock/CodeActAgent/test_edits/prompt_002.log
- tests/integration/mock/CodeActAgent/test_edits/prompt_003.log
- tests/integration/mock/CodeActAgent/test_ipython/prompt_001.log
- tests/integration/mock/CodeActAgent/test_ipython/prompt_002.log
- tests/integration/mock/CodeActAgent/test_ipython_module/prompt_001.log
- tests/integration/mock/CodeActAgent/test_ipython_module/prompt_002.log
- tests/integration/mock/CodeActAgent/test_ipython_module/prompt_003.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_001.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_002.log
- tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_003.log
> Minor docstring & prompt fixes for AgentSkills

- frontend/src/api/index.ts
- frontend/src/components/chat/ChatInterface.tsx
- frontend/src/services/session.ts
- frontend/src/utils/utils.test.ts
- frontend/src/utils/utils.ts
Partially addresses #1802
- Extends the `Session` class to store event history from both agent and user.
- Introduces two buttons (thumbs up and thumbs down) that sends back session history up to that point to backend created by @neubig 
- Conditionally renders these buttons when message length (agent + user) is > 3
- Hides buttons after clicking on either button
- Removes `LLM_API_KEY` before sending data
The data that is sent is of type `Record<string, unknown>` (`Dict[str, Any]`) and includes an `email` key according to @neubig API request definition. We currently do not store any user email, therefore the value is hardcoded to `'NOT_PROVIDED'`
This was a quick PR, so the chat interface component tests were **not extended to reflect this feature**
> feat(frontend): Add actions to send feedback to backend

- opendevin/controller/agent_controller.py
- opendevin/events/action/agent.py
- opendevin/events/action/browse.py
- opendevin/events/action/commands.py
- opendevin/events/action/message.py
- opendevin/events/observation/browse.py
This PR ensures that:
* We properly log user messages and print it to the terminal
* Format browser action/obs, `AgentSummarizeAction`, `MessageAction` appropriately for logging
Example screenshot of logged messages:
> Improve action and observation logging for the CLI interface

- .github/ISSUE_TEMPLATE/bug_template.yml
Creating a place for Operating System when opening a bug so it doesn't need to be asked.
Also makes figuring out which OS has the most issues.
> template: Update bug template to include os version

- opendevin/core/exceptions.py
- opendevin/runtime/browser/browser_env.py
- opendevin/runtime/runtime.py
- opendevin/runtime/server/browse.py
I am a bit surprised that I seem to be the only one who hits this issue consistently... but anyways, here's a little improvement:
1. Increase BrowserEnv init timeout from 10 seconds to 60 seconds
2. If BrowserEnv fails to init, print a warning log and ignore the error until OpenDevin really needs to use it
Fixes #2049 
You could see that it actually took me 11 seconds to start the browser environment.
COMMAND: `poetry run python ./opendevin/core/main.py -i 10 -t "tell me the usa's president using google search" -c BrowsingAgent -m gpt-4o-2024-05-13`
```
20:53:27 - opendevin:INFO: browser_env.py:35 - Starting browser env...
20:53:38 - opendevin:INFO: browser_env.py:51 - Browser env started.
20:53:38 - OBSERVATION
**MessageAction** (source=EventSource.USER)
CONTENT: tell me the usa's …
```
> BrowserEnv: init exception handling

- opendevin/runtime/docker/ssh_box.py
Similar to https://github.com/OpenDevin/OpenDevin/pull/2023, this PR add retry logic to `ssh.login`. While the loop looks a bit ugly, especially when used extensively :( - maybe we can figure out a way to clean this with some sort of retry decorator?
Without this, the `ssh.login` can occasionally failed due to same reason as https://github.com/OpenDevin/OpenDevin/pull/2023 (sshd not initialized yet).
> Add retry logic to ssh login

- opendevin/core/main.py
This is a minor bug that seems to be benign - it doesn't do anything malicious except for a redundant operation.
Without this fix, run any task with any agent using `main.py`:
With this fix:
> main.py: Fix redundant ChangeAgentStateAction

- evaluation/swe_bench/swe_env_box.py
When I run ```poetry run python evaluation/swe_bench/swe_env_box.py```, it failed to execute ```source /swe_util/swe_entry.sh``` in the SWEBench container, to ```source /swe_util/swe_entry.sh``` correctly need to run as root, but it connect the container through ssh as devin by defult, so we need to connect the container as root.  
The default config.run_as_devin is true, but when we use SWEBench container, we need to run as root to use it.
> fix: need to run as root to use SWEBench container

- .gitignore
- evaluation/swe_bench/BUILD_TESTBED_AND_ENV.md
- evaluation/swe_bench/EVAL_PATCH.md
- evaluation/swe_bench/README.md
- evaluation/swe_bench/scripts/docker/Dockerfile.full.v1.2.1
- evaluation/swe_bench/scripts/eval_infer.sh
- evaluation/swe_bench/swe_env_box.py
Bump SWE-Bench container version for https://github.com/OpenDevin/OD-SWE-bench/commit/62f373223be849d1bb48cf9e20496a2d5996277d
For astropy__astropy version lower than 4.1, `pyproject.toml` does not exists which causes `pip install .[test]` to fail :(
> Bump SWE-Bench docker ver to fix yet another swe_bench issue

- opendevin/controller/agent_controller.py
- opendevin/core/config.py
- opendevin/core/main.py
- tests/unit/test_arg_parser.py
- tests/unit/test_config.py
This PR addresses issue #2067 by adding a `max_budget_per_task` configuration to the `AppConfig` and `AgentController`. It allows setting a maximum budget for each task, beyond which the task will be stopped to prevent excessive costs.
- Added `max_budget_per_task` to `AppConfig`.
- Updated configuration loading functions to support `max_budget_per_task`.
- Integrated budget check in `AgentController` to stop the task if the budget is exceeded.
- Added tests to verify the new configuration.
- Verified `max_budget_per_task` can be read from a TOML file.
The implementation assumes that `self.state.metrics.accumulated_cost` resets when the agent start new task.
If this is not the case this part might need to change
```python
current_cost = self.state.metrics.accumulated_cost
if current_cost …
```
> feat: add max_budget_per_task configuration to control task cost

- agenthub/dummy_agent/agent.py
It seems the `DummyAgent` is the only one we forget to add version. After merge, #1611 can be closed.
> feat: add version for DummyAgent

- opendevin/core/config.py
- opendevin/llm/llm.py
- tests/unit/test_config.py
Support tracking costs for other model endpoints by setting in `config.toml` of llm:
```
input_cost_per_token = 0.00000014
output_cost_per_token = 0.00000028
```
> Support specifying custom cost per token

- tests/unit/test_sandbox.py
Remove extra "resets" from the sandboxes tests:
- it should not be necessary, fixtures or tests should set their stuff and clean that up at the end
- it causes issues, when env vars are unexpectedly not respected, like in https://github.com/OpenDevin/OpenDevin/pull/1998/
> Remove unnecessary stuff from the sandboxes tests

- Development.md
- docs/modules/usage/intro.mdx
Python has to be 3.11.
The part that says you can run without docker is confusing and not true. You still need docker in development workflow.
> doc: Small fix for development.md and docs

- Makefile
- frontend/src/components/modals/settings/SettingsModal.test.tsx
- frontend/src/services/settings.ts
- opendevin/core/config.py
- opendevin/server/README.md
- tests/unit/test_config.py
Previously we had a discussion about whether gpt-4-turbo or gpt-3.5-turbo should be the default language model on install. In that time we were at the very beginning of the project, and running expensive models like gpt-4 would cost lots of money for developers and users.
However, since then:
1. gpt-4o came out and it's faster and cheaper than gpt-4-turbo
2. the project has matured and become much more usable, but only if you use a strong model like gpt-4
3. we have become more efficient at solving tasks, so overall it takes fewer tokens
Because of this, I propose we change the default to gpt-4o.
> Default to gpt-4o

- Makefile
#2139 introduces persist_sandbox as an option to `make setup-config`, but has a syntax error. #2168 fixes the syntax error, but there's still another bug: it writes string `"false"` to config file. The correct way of doing it is to write boolean `false` without quotes, otherwise config loader doesn't recognize it.
> Fix persist_sandbox in Makefile

- frontend/package.json
Remove husky "install" parameter to avoid deprecated warning during make build.
Fixes https://github.com/OpenDevin/OpenDevin/issues/2190
> fix: Fix husky install deprecated message (since v9 of husky) (#2190)

- docs/modules/usage/troubleshooting/windows.md
Added more hints for WSL (Windows) users and applied some markdown tweaks/lint fixes.
This primarily addresses https://github.com/OpenDevin/OpenDevin/issues/2200
Thanks to @SmartManoj for all his great advice in above issue!
Example preview (from within VSCode):
> Windows doc extended with more WSL hints

- opendevin/runtime/docker/ssh_box.py
I noticed this many many times during evaluation: a lot of stale containers left running.
The bug comes from https://github.com/OpenDevin/OpenDevin/blob/4ece6fb3cc421e83106c79054dc257ef4596dec3/opendevin/runtime/docker/ssh_box.py#L269-L273
where we only close the containers if we catch `pxssh.ExceptionPxssh`. This used to work until we added `@retry` annotation to `__ssh_login` method. Now this throws retry exception rather than ExceptionPxssh. Thus, our try except clause doesn't correctly catch the exception, leaving stale containers running.
The fix is to always close containers no matter what exception we catch.
> ssh_box: Close containers before throwing exception

- opendevin/runtime/plugins/agent_skills/agentskills.py
Otherwise, eventually, we would meet `OSError: [Errno 24] Too many open files` error.
I encountered this error multiple times when running a benchmark.
> Fix file descriptor leaks in agentskills

- opendevin/runtime/docker/ssh_box.py
Similar to #2209, this might have contributed to `OSError: [Errno 24] Too many open files` too.
I haven't seen that error since the fix in this PR and #2209.
> ssh_box: Fix Docker client descriptor leak

- evaluation/gaia/run_infer.py
- evaluation/humanevalfix/run_infer.py
- evaluation/logic_reasoning/run_infer.py
- evaluation/swe_bench/swe_env_box.py
A few evaluations change global config on the fly, and then revert them at the end of each task. This doesn't work if OpenDevin itself throws an exception, which I have seen multiple times during evaluation.
The consequence is funny: since `config.workspace_mount_path` is not reverted, every task (after a failed one) would append new suffix to it, and eventually this path would be too long and hit system limit.
The fix is simple: put revert code in `finally` block under `try-except-finally`.
> evaluation: Reset configs in finally block

- opendevin/core/logger.py
After a few fixes to resource leak, the benchmarks can now run in a much more stable mode. That being said, occasionally, I still see `OSError: [Errno 24] Too many open files`. Hope this is the last one...
> logger.py: Fix resource leak

- opendevin/llm/llm.py
With https://github.com/OpenDevin/OpenDevin/pull/2122 the model name got truncated if a colon ":" was part of the model name as "tag".
It was originally aimed at https://github.com/OpenDevin/OpenDevin/issues/2118 to fix an issue with Ollama.
However, this caused problem with OpenRouter, where model names are like "wizardlm-2-8x22b:nitro" and that is the full model name as-is and now got truncated.
For what I could research, Ollama is supposed to have/support these tags and I'm not sure why 2118 caused an issue.
With this PR I added an if to prevent the split for openrouter.
> fix: keep colon part in model name for OpenRouter

- docs/src/css/welcome.css
Fixes the weird aspect ratio of the OpenDevin Logo: 
Before: 
After:
> doc: changed the welcome logo from 60vh to auto

- opendevin/server/data_models/feedback.py
Part of #1802 
We have implemented some functionality to (privately or publicly) share feedback about instances where OpenDevin is working or not: https://github.com/OpenDevin/OpenDevin/pull/2169
Previously I had started hosting of Share-OpenDevin on my own personal AWS account, but we transitioned this to a more permanent gcloud endpoint that will be financially supported by All Hands AI so it won't disappear. This PR just changes the URL to point to this new endpoint.
> Transition Share-OpenDevin to gcloud endpoint

- docs/modules/usage/about.md
- docs/modules/usage/feedback.md
Fixes https://github.com/OpenDevin/OpenDevin/issues/2204
Provides documentation for how to share feedback and how it will be used.
> Add docs for sharing feedback

- opendevin/runtime/plugins/mixin.py
Current behavior: 
`RuntimeError: Failed to initialize plugin agent_skills with exit code 1 and output <opendevin.runtime.docker.ssh_box.SSHExecCancellableStream object at 0x2841754d0>`
> Fixed output logging

- evaluation/agent_bench/README.md
Some tasks empty the contents of the /etc/sudoers file before running OpenDevin. If we set run_as_devin to false, then installation of jupyter environment would timeout.
> [AgentBench evaluation] set run_as_devin to true

- Makefile
To make the sandbox persistant, we need to have persist_sandbox=true
in config.toml 
However, in current Makefile setup-config, it does not store this value.
> Makefile setup-config to store the persist_sandbox boolean value

- opendevin/runtime/files.py
- opendevin/runtime/server/files.py
- opendevin/server/README.md
- opendevin/server/listen.py
A list of special folders is now being excluded from the workspace folder tree:
`'.git',
'.DS_Store',
'.svn',
'.hg',
'.idea',
'.vscode',
'.settings',
'.pytest_cache',
'__pycache__',
'node_modules',
'vendor',
'build',
'dist',
'bin',
'logs',
'log',
'tmp',
'temp',
'coverage',
'venv',
'env'
`
The Models and Agents lists in the Settings is now sorted by name.
Fixes https://github.com/OpenDevin/OpenDevin/issues/2056
> fix: hide special paths; sort models

- opendevin/runtime/plugins/jupyter/execute_cli
- tests/unit/test_sandbox.py
We introduce `JUPYTER_PWD` in https://github.com/OpenDevin/OpenDevin/pull/2105/files#diff-fbc8351b325a35a525f30e58eae651dbd50b3692963c81b989bee4dac617511c, so that every `create_file`, `open_file` command from `agentskills` is aware of the (bash's) current working directory.
It got accidentally removed in this commit: https://github.com/OpenDevin/OpenDevin/commit/78e003caf651d5031510cb9ed5e094f02d28eddc
Adding it back now.
Example, when `cd` into a folder `aaa`, the new `create_file` command should create file inside `aaa`, instead of `/workspace':
> Add back jupyter PWD env var for agentskills

- opendevin/runtime/server/runtime.py
Finally removing the escaping of backticks from `run_ipython` commands which causes syntax errors more often than not.
Related PR's:
https://github.com/OpenDevin/OpenDevin/pull/2321
https://github.com/OpenDevin/OpenDevin/pull/2117#discussion_r1617737723
Fixes: https://github.com/OpenDevin/OpenDevin/issues/2238
> fix: remove backtick escaping from run_ipython

- agenthub/codeact_agent/action_parser.py
- agenthub/codeact_agent/codeact_agent.py
- opendevin/controller/action_parser.py
With the improvement of our agent, more and more actions will add into agent. The logic of converting LLM response to action become complicated.
In each step: 
1. We need to call LLM get response
2. Parse the response into action str
3. Convert the action string into the actual `Action`. It may involve lots of actions.
So I create two abstract class:
1. `ResponseParser`: take over whole logic of convert LLM response to action
2. `ActionParser`: convert action string into one specific action.
Currently I only refactor the `CodeactAgent` which are most complicated in agenthubs. If others agree with this refactor, I will refactor other agents in future PR.
> Refactor response to action in agent step

- docs/modules/usage/about.md
- frontend/src/components/modals/settings/SettingsModal.test.tsx
- tests/integration/README.md
Removal of a couple of mentions of MonologueAgent in favor of CodeActAgent (readme, frontend settings default).
cc @li-boxuan @neubig is Mono still supported/developed? If not we could probably get rid of it all together and slim down also tests, but just mho.
> fix: remove some MonologueAgent mentions

- evaluation/swe_bench/run_infer.py
Quick fix of a bug introduced in https://github.com/OpenDevin/OpenDevin/pull/2381
> fix(swe_bench_eval): Mkdir `infer_logs` instead of `logs`

- opendevin/core/config.py
- tests/unit/test_config.py
workspace_mount_path proves a little confusing in that:
- it has to be optional - the user can set it or not, more often not when running without app docker, and we don't have a working default
- but it's a necessary config var and, at runtime, the code after the config is fully loaded should be able to work with it as if it was set.
We currently use `str or None` for this case, although that makes mypy unhappy when we try to use it as a string.
PR https://github.com/OpenDevin/OpenDevin/pull/2412 proposes to make it an empty string, so we can define it as `str`. That works to shut up mypy, but it has its downsides, and it seems more error-prone. (please see the discussion in linked PR)
This PR proposes an explicit UNDEFINED value to be initial value. It's checked for identity at the end …
> workspace_mount_path sentinel: an undefined string

- agenthub/browsing_agent/browsing_agent.py
All logic keep the same, only refactor the code style.
1. Move prompts out of `step` function to enhancement the code readability
2. remove `log cost`
> refactor browsing agent code

- opendevin/core/config.py
If there was even a simple typo in the `config.toml`, the existing exception handlers in `config.py` did not log the actual exception text itself.
With this PR, the exception text actually is logged. In my use case, the toml had a wrong-cased boolean value,
e.g. "True" (wrong) instead of "true" (correct).
> fix: improve toml parsing exception in config class

- .github/.codecov.yml
Fixes https://github.com/OpenDevin/OpenDevin/issues/2369
Basically, codecov uploads results incrementally for larger projects, and if the intermediate result is not good coverage then tests are listed as failing temporarily. 
This uses the codecov `after_n_builds` option to only report after the five are finished: https://docs.codecov.com/docs/notifications#section-preventing-notifications-until-after-n-builds
Currently our project is large enough that it uploads 6 reports, so I set this to only update after sending 5/6 (this seems to usually be more than enough to pass our thresholds).
I have …
> Codecov after_n_builds=5

- tests/integration/mock/CodeActSWEAgent/test_edits/prompt_003.log
- tests/integration/mock/CodeActSWEAgent/test_ipython_module/prompt_003.log
- tests/integration/mock/CodeActSWEAgent/test_ipython_module/prompt_004.log
- tests/integration/test_agent.py
From the latest build on main branch, https://github.com/OpenDevin/OpenDevin/actions/runs/9539046253/job/26288933811#step:7:775, we can see the agent already fails, but since the required file is generated, the test still pass. We should assert that the agent finishes without errors.
This PR checks agent error in each test, and fix prompt mismatches for CodeActAgent test_edits test.
> Integration tests: check agent error and fix test_edits

- opendevin/controller/agent_controller.py
- opendevin/controller/state/task.py
- opendevin/core/exceptions.py
- opendevin/core/utils/json.py
- opendevin/events/serialization/action.py
- tests/unit/test_response_parsing.py
Split out of #2021 
This PR proposes a small refactoring and code documentation for the Agent* exceptions. These have two properties:
- we send them back to the LLM in the hope it will self-correct next step
- their message should be user-friendly, without too much code detail, since it is sent to the UI
The main drive of this PR is consistency - just to name all three of them in some similar recognizable way. Here they're renamed from Agent* to LLM*, since they might not always be part of the agent flow, or even if they stay related to the agent, the name does not seem very explanatory for what they do. Granted, LLM isn't great either, but I'm out of ideas...
Also added some bits of code documentation about them.
Ref: https://github.com/OpenDevin/OpenDevin/pull/2021#discussion_r1643076017 …
> Document, rename Agent* exceptions to LLM*

- agenthub/SWE_agent/agent.py
- agenthub/browsing_agent/browsing_agent.py
- agenthub/codeact_agent/codeact_agent.py
- agenthub/codeact_swe_agent/codeact_swe_agent.py
- agenthub/micro/agent.py
- agenthub/monologue_agent/agent.py
- agenthub/planner_agent/agent.py
- opendevin/llm/llm.py
- opendevin/memory/condenser.py
- tests/unit/test_micro_agents.py
Split out of #2021 
This PR proposes to use the `completion` call for client code, while including cost logging in the wrapper.
When we added cost logging (I think), we added it to a new method `do_completion`, which wrapped the `completion` decorator and the post-processing for costs. That implies all clients need to call `do_completion` instead of `completion` as usual. This PR proposes to restore the use of the decorator for client code, while keeping the new cost logging as part of post-processing (in other words, no difference in functionality).
It's not a big deal perhaps, but I don't know, it makes sense to me: the `completion` decorator has been designed already to do a little extra stuff apart from calling `litellm.completion`, it already does some logging, so adding a bit more …
> Use the completion decorator with cost logging

- Makefile
During make build set a default timezone (here: UTC). 
This prevents e.g. the `tzdata` package to interactively prompt for one.
In the past there were issues with hung installations, which could be caused
by packages going interactive but can't be answered.
It was a little while back when I saw that package asking me (running on WSL),
but for the life of me I can't right now say how/when that happened.
> feat: default timezone in build

- opendevin/runtime/plugins/jupyter/setup.sh
We no longer need gcc. Installing GCC will increase the load time of jupyter plugin. After removing GCC, it still works finely on Ubuntu 22.04, Debian 11, and ghcr.io/opendevin/sandbox:main.
Remove gcc installation in jupyter's setup.sh
> remove gcc

- frontend/src/components/file-explorer/FileExplorer.tsx
I felt the left side of the menu bar looked a bit empty, so I added some text to it. I'm not sure if this will conflict with the design draft.
@amanape Could you take a look for this?
before:
after:
> add workspace text

- evaluation/EDA/scripts/run_infer.sh
- evaluation/agent_bench/scripts/run_infer.sh
- evaluation/biocoder/scripts/run_infer.sh
- evaluation/bird/scripts/run_infer.sh
- evaluation/gaia/scripts/run_infer.sh
- evaluation/gorilla/scripts/run_infer.sh
- evaluation/gpqa/scripts/run_infer.sh
- evaluation/humanevalfix/scripts/run_infer.sh
- evaluation/logic_reasoning/scripts/run_infer.sh
- evaluation/miniwob/scripts/run_infer.sh
- evaluation/mint/scripts/run_infer.sh
- evaluation/ml_bench/scripts/run_infer.sh
- evaluation/toolqa/scripts/run_infer.sh
- evaluation/utils/version_control.sh
- evaluation/webarena/scripts/run_infer.sh
After #2356, we support "time-travel" for benchmarks (this PR contains some minor fixes for that functionality, but that's not the point). One missing piece is time-travel for sandboxes. Most evaluations (except SWE-bench) simply use the default sandbox for evaluation, i.e. the one from `config.sandbox_container_image`, which is usually `ghcr.io/opendevin/sandbox:latest`. This could make evaluations non-reproducible.
This PR is almost as simple as two lines of code:
```python
docker build -t eval-sandbox -f containers/sandbox/Dockerfile /tmp
export SANDBOX_CONTAINER_IMAGE="eval-sandbox"
```
It builds a sandbox image locally and uses it for evaluation. Problem solved.
What about SWE-bench? SWE-bench is an exception - it already has a built-in mechanism that builds a special sandbox on the …
> Evaluation time travel: build sandbox on the fly

- .github/workflows/ghcr.yml
`test_agnostic_sandbox_jupyter_agentskills_fileop_pwd` is marked as `TEST_IN_CI` but the env variable is not correctly passed, so this test won't be run by CI. This PR fixes this problem.
> Enable test_agnostic_sandbox_jupyter_agentskills_fileop_pwd in CI

- frontend/package-lock.json
Fix npm audit for Github sec advisory for `ws` module, raised version to 8.17.1.
> sec: update npm module "ws" to 8.17.1

- opendevin/runtime/docker/ssh_box.py
#2555 
From [#2555 Comment ](https://github.com/OpenDevin/OpenDevin/issues/2555#issue-2365611560)
> https://github.com/OpenDevin/OpenDevin/pull/2538 possibly makes startup time much slower. I just pulled the most recent version of OpenDevin and it's stuck at this log step for minutes:
We shouldn't always pull the latest image, or startup will be very slow.
Stop always pulling the latest image
> Stop always pulling the latest image.

- opendevin/runtime/docker/ssh_box.py
Reverts OpenDevin/OpenDevin#2538
The code now depends on `/opendevin/miniforge3/bin/python`. If it doesn't exist, it tells the user need to repull `ghcr.io/opendevin/sandbox:main`. But this was removed in this PR.
> Revert "Always pull sandbox image"

- Makefile
`Makefile` was pulling the `latest` as default sandbox image since no tag was specified.
Fixed by adding `:main` to `DOCKER_IMAGE` variable.
Reference: https://github.com/OpenDevin/OpenDevin/pull/2101
> fix: Makefile shall pull sandbox:main, not :latest

- README.md
- docs/src/components/Welcome/Welcome.tsx
- docs/src/pages/faq.tsx
This PR does two things:
1. It updates our doc to clarify our mission (not to replicate Devin, but be a community-based open source platform for software development)
2. It changes the link on the README to go directly to the contentful doc page, instead of the landing page
[Current doc page](https://opendevin.github.io/OpenDevin/) for reference
> Update doc to clarify OpenDevin mission and link directly to content

- containers/sandbox/Dockerfile
- opendevin/runtime/docker/ssh_box.py
#2555
This code runs very slowly, it takes 10 seconds on my computer. Removing it might fix the slow startup issue.
I tested it, and it still runs fine after removing it.
I originally added this code because I needed to use mamba to install dependencies in setup.sh, otherwise there would be permission issues. Now it's not needed anymore. Even if needed in the future, we can use `sudo /opendevin/miniforge3/bin/mamba install` to install.
> No longer chown -R the miniforge3 folder

- frontend/src/components/modals/feedback/FeedbackModal.tsx
- opendevin/server/data_models/feedback.py
- opendevin/server/listen.py
When users encounter problems, it would be nice if they could share their interaction history with us so we could examine the agent's behavior and see if there was anything wrong.
Fixes #1802
This PR:
1. Exposes a unique feedback ID to the frontend
2. When feedback is successfully uploaded, provides the user with a link to a Vercel app that I set up to display the feedback: https://od-feedback.vercel.app/show
See this video for how the user can copy-paste this link, view it, and share it with us: https://youtu.be/yBf-mT__yKE
And see this link for an example of the shared feedback: …
> Add links to a feedback sharing site

- .github/workflows/run-unit-tests.yml
[Current Action Link](https://github.com/OpenDevin/OpenDevin/actions/runs/9622270197/job/26543320014?pr=2433)
Error: msg="[hostagent] QEMU did not exit in 3m0s, forcibly killing QEMU"
Related issue: https://github.com/abiosoft/colima/issues/777
---
In PR #2499, got the above error once and the below error twice. And the runner get Intel images only and not ARM.
Error:  msg="did not receive an event with the \"running\" status"
Related issue: https://github.com/abiosoft/colima/issues/629
So, as suggested in https://github.com/abiosoft/colima/issues/629#issuecomment-1912389908, Using vz vm-type …
> Enable "vz" vm-type for MacOS CI

- .github/workflows/run-unit-tests.yml
Reverts OpenDevin/OpenDevin#2586 due to actions automatically cancelled.
> Revert "Enable "vz" vm-type for MacOS CI"

- Development.md
- README.md
- docs/modules/usage/intro.mdx
The PERSIST_SANDBOX=true has some issues with workspaces. Especially if you tend to switch your workspace by setting the WORKSPACE_BASE. Removing as this should not be used until completely fixed
> Remove PERSIST_SANDBOX=true option

- evaluation/EDA/scripts/run_infer.sh
- evaluation/agent_bench/scripts/run_infer.sh
- evaluation/biocoder/scripts/run_infer.sh
- evaluation/bird/scripts/run_infer.sh
- evaluation/gaia/scripts/run_infer.sh
- evaluation/gorilla/scripts/run_infer.sh
- evaluation/gpqa/scripts/run_infer.sh
- evaluation/humanevalfix/scripts/run_infer.sh
- evaluation/logic_reasoning/scripts/run_infer.sh
- evaluation/miniwob/scripts/run_infer.sh
- evaluation/mint/scripts/run_infer.sh
- evaluation/ml_bench/scripts/run_infer.sh
- evaluation/swe_bench/scripts/run_infer.sh
- evaluation/toolqa/scripts/run_infer.sh
- evaluation/webarena/scripts/run_infer.sh
Fixes https://github.com/OpenDevin/OpenDevin/issues/2567
This makes NUM_WORKERS configurable in all evaluation scripts, and defaults it to 1.
Authored by OpenDevin.
> Add NUM_WORKERS variable to run_infer.sh scripts for configurable woker settings

- .github/workflows/run-unit-tests.yml
[Current Action Link](https://github.com/OpenDevin/OpenDevin/actions/runs/9622270197/job/26543320014?pr=2433)
Error: msg="[hostagent] QEMU did not exit in 3m0s, forcibly killing QEMU"
Relevant issue: https://github.com/abiosoft/colima/issues/913
Remove the Colima directory after uninstalling as suggested in https://github.com/abiosoft/colima/issues/913#issuecomment-2111925289 as it contains ssh_config and some other configs.
> Remove Colima and lima directory after uninstalling for Mac OS CI

- frontend/.eslintrc
Disables the ESLint rule that throws the annoying exhaustive dependency warning for `useEffect` hooks that don't fill their dependency arrays.
The developer should decide which dependencies they need to add to appropriately trigger the `useEffect`, the dependency array does not need to contain all artifacts used within the `useEffect`.
> fix(frontend): Disable eslint rule that throws `useEffect` warning

- Makefile
This comment was not resolved before PR was merged: https://github.com/OpenDevin/OpenDevin/pull/2591#issuecomment-2184131712
Just defaulting the persist_sandbox to false in the makefile
> Default makefile for persist_sandbox to be false

- opendevin/controller/agent_controller.py
- opendevin/core/metrics.py
- opendevin/llm/llm.py
OpenDevin tracks costs and allow users to set up a max budget for each task, but it doesn't work for delegates. Specifically, parents and children don't share the budget. This means execution for a task can exceed its preset budget.
Moreover, when OpenDevin sees an out-of-budget error, it displays the messages in a weird order. See the screenshots in next comment.
1. Fix messaging order when there's out-of-budget error to improve UX
2. Make parents and children share metrics object (share costs)
Currently this is not testable (especially the message order part). I am …
> Track metrics throughout delegation & Polish UX for out of budget error

- frontend/src/components/chat/ChatInput.tsx
- frontend/src/components/chat/ChatMessage.tsx
- frontend/src/components/file-explorer/FileExplorer.tsx
- frontend/src/components/modals/settings/SettingsModal.tsx
- frontend/src/i18n/translation.json
- frontend/src/services/session.ts
Several frontend areas were missing the translation entries for i18n.
Added several entries to main translations.js file and in appropriate frontend components.
cc @li-boxuan I've used the LLM to translate some entries for "zh-CN", if you could take a read if it messed something up.
> frontend: apply more translations to frontend components

- evaluation/swe_bench/scripts/docker/Dockerfile.full_deps
- opendevin/runtime/docker/image_agnostic_util.py
If you are building your own `SANDBOX_CONTAINER_IMAGE` from `ghcr.io/opendevin/sandbox:main`, building the final sandbox image in `opendevin/runtime/docker/image_agnostic_util.py` fails because it tried to reinstall `miniforge3`.
You may want to build from `ghcr.io/opendevin/sandbox:main` to install additional Python dependencies.
Rather than install `miniforge3` no matter what, check if `/opendevin/miniforge3` is already there
> feat: allow SANDBOX_CONTAINER_IMAGEs built from opendevin/sandbox:main

- tests/unit/test_sandbox.py
`config.enable_auto_lint` is a very important feature to guide LLMs to make edit commands right, since LLM often messes around with indentation and line numbers. It currently only works for python, and is disabled by default. We turn it on for SWE-bench evaluation purpose, though.
This PR adds a basic test for AUTO_LINT feature.
> Add test for auto_lint after file edit

- opendevin/controller/agent_controller.py
This PR proposes a revert of OpenDevin/OpenDevin#2516.
Please check out the history of this issue:
- sending `str(e)` in the ErrorObservation has been shown to leak private info: [screenshot](https://private-user-images.githubusercontent.com/1708914/326360829-d055f819-b857-47cc-8075-cab9d79c9f01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzUwNjQsIm5iZiI6MTcxOTQ3NDc2NCwicGF0aCI6Ii8xNzA4OTE0LzMyNjM2MDgyOS1kMDU1ZjgxOS1iODU3LTQ3Y2MtODA3NS1jYWI5ZDc5YzlmMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDc1MjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cm …
> Revert "Show relevant error in UI"

- evaluation/swe_bench/scripts/eval/convert_od_output_to_swe_json.py
`.rstrip()` removes the last newline of the git patch that affects the applied "rate of the generated patch," which hurts the pass rate a little bit.
This adds a new line at the end of the git patch (if it is not already empty) and improves "CodeAct v1.6 no-hint" from 56 (18.6%) to 58 (19.3%): https://huggingface.co/spaces/OpenDevin/evaluation/commit/a4e8ae805efa8b76a9f7353465baf57bdec415bf
I'm in the process of re-running all the existing runs.
> [Evaluation] Improve patch apply in SWE-Bench

- .github/workflows/ghcr.yml
#2456 introduces a bug: when there are multiple tags (which happens during releases, e.g. we tag the docker image as 0, 0.7, and 0.7.0), the tests don't run.
When loading locally built image names, only take the first one if there are multiple.
I am testing it by releasing 0.7.0 on my fork: https://github.com/li-boxuan/OpenDevin/releases/tag/0.7.0 with CI/CD: https://github.com/li-boxuan/OpenDevin/actions/runs/9722823185 (I changed dependency order so that the CD doesn't wait for tests, but that shouldn't matter)
Looks good: …
> ghcr: Fix local built image name in tests

- evaluation/EDA/run_infer.py
- evaluation/agent_bench/run_infer.py
- evaluation/biocoder/run_infer.py
- evaluation/bird/run_infer.py
- evaluation/gaia/run_infer.py
- evaluation/gorilla/run_infer.py
- evaluation/gpqa/run_infer.py
- evaluation/humanevalfix/run_infer.py
- evaluation/logic_reasoning/run_infer.py
- evaluation/miniwob/run_infer.py
- evaluation/mint/run_infer.py
- evaluation/swe_bench/run_infer.py
- evaluation/toolqa/run_infer.py
- evaluation/webarena/run_infer.py
- opendevin/controller/agent_controller.py
- opendevin/controller/state/state.py
- opendevin/core/config.py
- opendevin/core/main.py
- opendevin/server/session/agent.py
- tests/integration/test_agent.py
During work with CLI, I added the ability to restore the main session on my branch (thinking it was just a quick temporary thing to debug easily). It proved so, so useful, particularly with long-running or large-context sessions, that I think we may find it handy. It's disabled by default, and can be enabled in config. It's pretty basic, just a little step to work better with CLI.
PR #2695 adds the ability to have different sessions when run from a script (e.g. "main_astropy__astropy-12907"). Directly from the command line it's a single session ("main"). Below is the agent remembering our past conversation and continuing:
> 01:47:36 - opendevin:INFO: main.py:93 - Restoring agent state from main session
On my machine with a local file storage:
Additionally, this PR proposes a quick rename …
> Add ability to restore the cli session (optional)

- agenthub/codeact_agent/codeact_agent.py
- agenthub/codeact_swe_agent/codeact_swe_agent.py
- agenthub/monologue_agent/agent.py
- opendevin/core/config.py
- opendevin/events/serialization/event.py
This PR proposes a small refactoring of obs truncation to have the max number of chars configurable, and make it usable by all agents. The default is 10k as it currently is.
It may be evaluated in the future.
Ref: https://github.com/OpenDevin/OpenDevin/issues/2540
> Small refactoring of obs truncation

- opendevin/controller/agent_controller.py
- opendevin/controller/state/state.py
Closes #1493 
Introduced `TRAFFIC_CONTROL_STATE` to allow OpenDevin to switch between normal traffic limiting mode and temporarily disabled mode.
**Demo**
I set `MAX_ITERATIONS=1` so I have to hit "RESUME" button multiple times to get the result step by step. I think it's also useful when you'd like the agent to solve the task step-by-step under your surveillance.
This feature is only available on web GUI. If you are using `main.py`, then the control flow would be paused and there's nothing you could do but quit the program:
> Bypass MAX_ITERATIONS and MAX_BUDGET_PER_TASK on web GUI

- Makefile
- frontend/vite.config.ts
This adds the option `make run-wsl` to make use of the "dev_wsl".
Easier use for me developing in WSL.
Tested in WSL and hot reload of changed .tsx files works like a charm.
https://github.com/OpenDevin/OpenDevin/pull/2506
> feat: added make run-wsl

- frontend/src/components/chat/ChatInput.tsx
- frontend/src/components/chat/ChatMessage.tsx
* Refine the copy button and add copy feedback for the icon.
* Add padding on top for input to overlay the message bubbles.
Before:
After:
The copy button:
https://github.com/OpenDevin/OpenDevin/assets/16201837/d1b47aac-ecbc-4a2d-a70a-0e0c15121bf4
> style: refine the copy button and add copy feedback for the icon.

- frontend/src/components/chat/ChatInterface.test.tsx
- frontend/src/components/terminal/Terminal.test.tsx
Before:
After:
It's wired, it seems the GitHub workflow doesn't check the FE's unit tests. why do the UTs usually fail but no one is blocked by the git hook? 🥶
> test: fix the failed unit tests.

- opendevin/runtime/docker/ssh_box.py
- opendevin/runtime/plugins/mixin.py
Improved exit_code handling to avoid "invalid literal" error message.
Fixes: https://github.com/OpenDevin/OpenDevin/issues/2702
The same error also happens during evaluations.
SSHExecCancellableStream -> exit_code rewritten to make the detection of the actual exit code more robust.
> fix: improve exit_code processing (ssh_box)

- frontend/src/components/file-explorer/FileExplorer.tsx
- frontend/src/components/file-explorer/TreeNode.tsx
Fixes issue [#2714](https://github.com/OpenDevin/OpenDevin/issues/2714) Adds more width control and scroll functionality to the File Explorer side pane.
- Adds scroll functionality for overflow content
- Updates width transition for improved UX
N/A
> Fix: Add scroll functionality to file explorer sidepane

- containers/build.sh
this PR addresses the issue raised in #2730 where the "latest" tag for Docker images was not being updated with the most recent stable release. This caused users pulling the image without specifying a version to get an outdated image.
This PR modifies the `build.sh` script to include the 'latest' tag for semantic version releases. 
- Ensure 'latest' always points to the most recent stable version
> Add 'latest' tag to Docker builds for stable releases only

- opendevin/llm/llm.py
When evaluating on anthropic claude 3.5, we sometimes get error like this that break the `run_infer` loop;
```
There was an unexpected error while running the agent: litellm.InternalServerError: VertexAIException InternalServerError - Reauthentication is needed. Please run `gcloud auth application-default login` to reauthenticate.
```
and/or
```
litellm.InternalServerError: VertexAIException InternalServerError - Error code: 500 - {'type': 'error', 'error': {'type': 'api_error', 'message': 'Internal server error'}}
```
Add retries when hitting litellm.InternalServerError.
> [LLM] Retry for internal server error

- .github/workflows/run-unit-tests.yml
Sometimes CI fails with `msg="did not receive an event with the \"running\" status"`
Applied the suggestion from https://github.com/abiosoft/colima/issues/215#issuecomment-1065864891
Seems there is a bug in the default profile.
> CI: Delete colima default profile

- README.md
- docs/modules/usage/intro.mdx
Use README as the only place for getting started instructions. This avoids changing multiple places when these docs are changed.
> Use README as the only place for getting started instructions

- containers/sandbox/Dockerfile
- opendevin/runtime/docker/image_agnostic_util.py
- opendevin/runtime/docker/ssh_box.py
> https://opendevin.slack.com/archives/C06QKSD9UBA/p1719019334249829
As mentioned in the Slack discussion, our current sandbox image is a bit large and has some unnecessary dependencies. I want to remove these unnecessary dependencies to make the sandbox image smaller.
Also, we will install plugin dependencies in the dockerfile of the agnostic image (just like we do in the current sandbox image). This will significantly improve the startup speed for users using custom sandbox container image.
remove these:
* nano: maybe we can use vim to instead
* bash: system built-in
* libgl1-mesa-glx: …
> trim the sandbox image and install plugin dependencies in agnostic image

- evaluation/swe_bench/swe_env_box.py
This PR is to fix issue # https://github.com/OpenDevin/OpenDevin/issues/2755
During the evaluation on the swe-bench dataset, if you directly use ssh to connect the docker, Git will give paginated output if the diff is large enough. We should close the `pager` setting to enable the `git diff` command, otherwise it will stuck at the `git diff` command.
> fix git diff TIMEOUT problem in swe_bench evaluation

- containers/sandbox/Dockerfile
- opendevin/runtime/docker/image_agnostic_util.py
Resolve 3 problems.
1. Now during the agnostic image build process, real-time output isn't shown, and the whole build can take about a minute. Users might feel anxious while waiting.
2. Sometimes using wget default dot progress seems to cause log display issues (on my computer, one line gets split into multiple lines) . In contrast, the bar style doesn't have this issue and doesn't produce as many logs as the dot style.
3. After installing Miniforge3, the installation script remains in the image, taking up disk space. It should be deleted.
1. Display real-time agnostic docker build logs.
2. Use …
> Display real-time build logs for the agnostic image

- tests/integration/regenerate.sh
https://github.com/OpenDevin/OpenDevin/pull/2824#issuecomment-2212309414 Removing the current directory in WSL makes the OS unstable.
Just removing the directory's content only.
> Test: Update regenerate.sh

- containers/sandbox/Dockerfile
In order to run runtime client introduced here #2603  in snadbox docker image, we need to add more new dependency. Maybe we will introduce poetry to management this environment, but let's use pip now first.
> add od runtime clinet dependencies in sandbox image

- opendevin/runtime/docker/ssh_box.py
- opendevin/runtime/utils/image_agnostic.py
- tests/unit/test_image_agnostic_util.py
Make image agnostic util a shared utility that can be used by other runtime implementation (https://github.com/OpenDevin/OpenDevin/pull/2603)
> Refractor: move image agnostic util to shared runtime util

- opendevin/runtime/client/client.py
Question proposed [here](https://github.com/OpenDevin/OpenDevin/pull/2603#discussion_r1668963066), after test, the default pexpect running in docker image is already root permission.
Here is the execution result:
```
Received command: whoami
root
root@4e38acaed5b1:/Users/yufansong/code/OpenDevin/opt/workspace_base/opendevin/runtime/client
```
In `exec_box` which we already removed, we create `root` and user `devin`, currently we directly use `root` in `od-runtime-client`, not sure whether we still need a non-root user permission in the future.
> fix client pexpect remove permission todo

- opendevin/runtime/client/client.py
As title, do some specific fix for bash in our sandbox image when running pexpect. The output of pexpect in our env may include various escape sequences and control characters that are used by the terminal to control formatting, cursor movement, and other terminal behaviors. Do `re` replacement to clean it.
Here is a example output of test code when execute `ls -l` and `pwd`
```
Received command: ls -l
**CmdOutputObservation (source=None, exit code=0)**
total 24
-rw-r--r-- 1 root root  8777 Jul  9 00:32 client.py
drwxr-xr-x 6 root root   192 Jul  9 00:00 logs
drwxr-xr-x 5 root root   160 Jul  8 18:30 mock_test
-rw-r--r-- 1 root root 10205 Jul  8 18:30 runtime.py
drwxr-xr-x 2 root …
```
> fix pexpect output code error in docker image

- opendevin/runtime/__init__.py
- opendevin/server/session/agent.py
Fix the following issue when try to run docker run command - reported by @mamoodi:
```
ERROR:root:  File "/app/.venv/bin/uvicorn", line 8, in <module>
sys.exit(main())
^^^^^^
File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 783, in …
```
> fix: Runtime import

- opendevin/runtime/browser/__init__.py
- opendevin/runtime/browser/utils.py
- opendevin/runtime/client/client.py
- opendevin/runtime/client/runtime.py
- opendevin/runtime/server/runtime.py
- opendevin/runtime/utils/image_agnostic.py
This is part of https://github.com/OpenDevin/OpenDevin/issues/2404.
Right now, the `RuntimeClient` running inside the sandbox supports running Browser actions.
- Move the browser into `RuntimeClient` to be executed inside sandbox.
- Tweak the dependency a bit to make sure it works.
Command to test `python3 opendevin/runtime/client/runtime.py`
Example output:
> [Arch] `EventStreamRuntime` supports browser

- .github/workflows/ghcr.yml
It doesn't fix any problem. It only prettifies `ghcr.yml` and our build.
Remove legacy dummy action.
This PR won't pass CI gates until an admin actually unmarks `docker_build_success` as mandatory in branch protection rules.
We don't need to add anything else to branch protection rules because `Integration Tests on Linux`, a mandatory check, depends on `ghcr_build` check.
> Remove legacy dummy action from CI

- agenthub/browsing_agent/response_parser.py
- agenthub/codeact_agent/action_parser.py
- agenthub/codeact_swe_agent/response_parser.py
No Open issues for this bug.
Error log:
File "/google/src/cloud/rajmaheshwari/OpenDevin/google3/experimental/users/rajmaheshwari/OpenDevin/OpenDevin/opendevin/controller/agent_controller.py", line 135, in _start_step_loop
await self.step()
File "/google/src/cloud/rajmaheshwari/OpenDevin/google3/experimental/users/rajmaheshwari/OpenDevin/OpenDevin/opendevin/controller/agent_controller.py", line 339, in step
action = self.agent.step(self.state)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/google/src/cloud/rajmaheshwari/OpenDevin/google3/experimental/users/rajmaheshwari/OpenDevin/OpenDevin/agenthub/codeact_agent/codeact_agent.py", line 209, in step
return self.action_parser.parse(response) …
> [Fix] Minor bug in parse_response of CodeActResponseParser

- evaluation/EDA/run_infer.py
- evaluation/biocoder/run_infer.py
- evaluation/bird/run_infer.py
- evaluation/swe_bench/run_infer.py
Find some code forget to delete after #2775
> chores: remove useless code in eval

- evaluation/swe_bench/scripts/setup/compare_patch_filename.py
https://aider.chat/2024/05/22/swe-bench-lite.html says it finds correct files to edit in 70.3% of benchmark tests. This PR adds a utility script that computes the number for OpenDevin.
Usage Example:
```bash
poetry run python evaluation/swe_bench/scripts/setup/compare_patch_filename.py --od_output_file /Users/liboxuan/workspace/OpenDevin/evaluation/evaluation_outputs/outputs/swe_bench_lite/CodeActAgent/claude-3-5-sonnet@20240620_maxiter_30_N_v1.8-no-hint/output.jsonl
```
`claude-3-5-sonnet@20240620_maxiter_30_N_v1.8-no-hint` result says OpenDevin found correct files to edit in 64% of benchmark tests. The real number might be even lower because I consider success as long as OpenDevin modifies *the* correct file even though it might have modified other files erroneously and caused the test …
> [SWE-bench] Util: Compare files modified between gold patches and OpenDevin patches

- .github/workflows/run-unit-tests.yml
As an alternative approach to increasing the timeout https://github.com/lima-vm/lima/pull/2455#issuecomment-2218167717, added a retry mechanism to the colima start command to check if retries work for handling transient failures.
> CI: Add retry mechanism

- opendevin/core/config.py
- opendevin/core/main.py
- tests/unit/test_arg_parser.py
After #2756, the semantics of `--llm-config` CLI arg becomes ambiguous: what exactly does it mean to provide a LLM config group via CLI, especially when agent delegation is involved?
---
This PR makes it clear that `--llm-config` allows one to override default LLM config (`[llm]` section in `config.toml`) with a given config group. For example, say you have
```config.toml
[llm.eval_gpt4_1106_preview_llm]
model = "gpt-4-1106-preview"
api_key = "XXX"
temperature = 0.0
[llm.eval_some_openai_compatible_model_llm]
model = "openai/MODEL_NAME"
base_url = "https://OPENAI_COMPATIBLE_URL/v1"
api_key = "XXX" …
```
> Rework --llm-config CLI arg

- frontend/package-lock.json
- frontend/package.json
- frontend/src/index.tsx
The React Router package was added in the past and was never utilized beyond initialization. There also does not seem to be any issue or near-term requirement for it.
To avoid including it as a dependency and unnecessarily update it via dependabot, I propose to remove it until required. When required, we will install the latest version anyways.
---
---
> fix(frontend): Remove unused react router package

- opendevin/core/config.py
- opendevin/core/logger.py
This PR removes the global config from `logger.py`.
It does several things:
1. Removes the global config from `logger.py`, and in place adds a global `DEBUG` variable
2. Transitions the loading of the config to a `load_app_config.py` function that loads the app config, and optionally also sets these logging variables
3. Transitions `config.py` to use the OpenDevin logger (previously it was not, probably due to circular dependency issues)
4. Fixes what seems to be a bug in `set_attr_from_env()`
5. Does some automatic formatting of long lines (sorry, I did this accidentally which makes the PR a little …
> Remove global config from logger

- opendevin/server/listen.py
There was a bug with the model list that wasn't caught by my previous testing when incorporating #2954 as pointed out by @mamoodi 
```
mahmoudwork@Mahmouds-Mini OpenDevin % make run
Running the app...
Starting backend server...
Waiting for the backend to start...
10:18:41 - opendevin:INFO: config.py:450 - Attempt to load default LLM config from config toml
ERROR:root:  File "/Users/mahmoudwork/Library/Caches/pypoetry/virtualenvs/opendevin-0q8VcB7c-py3.11/bin/uvicorn", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/mahmoudwork/Library/Caches/pypoetry/virtualenvs/opendevin-0q8VcB7c-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return …
```
> Fix bug with model list

- opendevin/core/config.py
Resolves the `NameError: name 'config' is not defined` bug in
```
opendevin/core/config.py:473: in load_from_toml
sandbox_config = config.sandbox
```
> fix bug in config.py file, update reference to variable

- opendevin/core/config.py
- opendevin/llm/llm.py
I was happily using OpenDevin to build a website for me until it hit Anthropic API's rate limit.
For some reason, the exponential back-off does not work - See log: it retries every 2 seconds, which quickly runs out of retries and breaks the application for me.
---
This PR tries to increase the default backoff strategy to be more aggressive rather than erroring out for user.
---
> [LLM] Increase the default retries for LLM

- opendevin/controller/agent_controller.py
- opendevin/controller/state/state.py
- opendevin/memory/history.py
- tests/integration/conftest.py
- tests/integration/mock/CodeActAgent/test_browse_internet/prompt_005.log
- tests/integration/test_agent.py
We have `iteration` that tracks OpenDevin progress. When OpenDevin exceeds `config.max_iterations`, it pauses execution.
The introduction of agent delegation mechanism essentially makes OpenDevin a multi-agentic system. Without this PR, every agent instance keeps track of their own "local" iterations. What this means is with `max_iterations = 10`, OpenDevin could speak to LLM for 10 * 10 = 100 times in the worst case (root agent delegates 10 times). This defeats the purpose of `config.max_iterations`.
This PR fixes this problem by introducing `local_iteration` that had the same behavior as prior `iteration`. The attribute `iteration` now becomes a global/shared value per task.
Do we really need configs for both `max iterations per task` and `max iterations per subtask`? I don't think so. …
> State: Add local_iteration attribute

- opendevin/server/listen.py
- opendevin/server/session/__init__.py
- opendevin/server/session/agent.py
- opendevin/server/session/manager.py
- opendevin/server/session/session.py
This PR removes global config from the session manager.
1. Removes global config from the session management code, and instead passes in variables
2. Converts some of the lower-level functions to take normal arguments instead of dictionaries
3. Initializes the session manager within the server listener
(I have run this and confirmed that it runs)
Part of #2758
> Remove global config from session

- evaluation/EDA/run_infer.py
- evaluation/agent_bench/run_infer.py
- evaluation/biocoder/run_infer.py
- evaluation/bird/run_infer.py
- evaluation/browsing_delegation/run_infer.py
- evaluation/gaia/run_infer.py
- evaluation/gpqa/run_infer.py
- evaluation/humanevalfix/run_infer.py
- evaluation/logic_reasoning/run_infer.py
- evaluation/miniwob/run_infer.py
- evaluation/ml_bench/run_infer.py
- evaluation/swe_bench/run_infer.py
- evaluation/toolqa/run_infer.py
- evaluation/utils/shared.py
- evaluation/webarena/run_infer.py
- opendevin/core/config.py
- after the global config refactor #2760, `llm_config` inside `EvalMetadata` no longer hides sensitive info when dumped into JSON.
- the `LLM`'s input keyword argument change from `llm_config` to `config`
---
- Hide sensitive info when try to dump `EvalMetadata` into a JSON via `model_dump_json`
- Fix all occurrence of `llm_config=` to `config=` in all `run_infer.py`
---
> Fix: evaluation leaks api_key in metadata; fix `llm_config` argument in run infer

- .github/ISSUE_TEMPLATE/bug_template.yml
- CONTRIBUTING.md
- README.md
- docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/intro.mdx
- docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/troubleshooting/troubleshooting.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/intro.mdx
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/troubleshooting/troubleshooting.md
- docs/modules/usage/troubleshooting/troubleshooting.md
- opendevin/core/const/guide_url.py
Previously we converted the default URL of the docs site to `https://docs.all-hands.dev`, but failed to replace some places in the repo.
This PR fixes these remaining places.
Thanks to @pyrytakala for flagging this.
> Convert docs to new URL

- opendevin/server/session/session.py
The Session instance sets the `api_key` and `model` of the `default_llm_config`, but not the `base_url`.
---
Like the 2 already existing assignments, the base_url should also be set.
---
> (fix) Session: set base_url in default_llm_config

- containers/app/entrypoint.sh
Fixes #3007
Fix the issue where the container cannot restart due to a missing directory error.
* Check if the directory `/home/opendevin/.cache/ms-playwright/` exists before attempting to move it.
* If the directory does not exist, skip the move operation to prevent the error.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/OpenDevin/OpenDevin/issues/3007?shareId=ec3b6bb3-7a2c-4395-8ce0-fb8013e60bd5).
> Fix playwright cache error during container restart

- opendevin/runtime/runtime.py
- tests/unit/test_runtime.py
Fix the issue @mamoodi reported in slack: https://opendevin.slack.com/archives/C06TZ1VCCAD/p1721328419082809?thread_ts=1721247898.211409&cid=C06TZ1VCCAD
```
14:46:37 - opendevin:ERROR: session.py:113 - Error creating controller: cannot access local variable 'key' where it is not associated with a value
Traceback (most recent call last):
File "/Users/mahmoudwork/Desktop/OpenDevin_Forks/tobifork/OpenDevin/opendevin/server/session/session.py", line 105, in _initialize_agent
await self.agent_session.start(
File "/Users/mahmoudwork/Desktop/OpenDevin_Forks/tobifork/OpenDevin/opendevin/server/session/agent.py", line 56, in start
await self._create_runtime(runtime_name, sandbox_config)
File …
```
> Fix: handle the case where env var is empty

- tests/test_fileops.py
- tests/unit/test_ipython.py
This PR removes the global config file from a few remaining tests.
Part of #2758
> Remove global config from tests

- evaluation/swe_bench/swe_env_box.py
`use_host_network` is already removed from the init argument of `SSHBox` yet still in the swe env box, which causes the evaluation to fail to run.
---
Remove `use_host_network` from `swe_env_box.py`
---
> fix: Remove extra arg from swebench ssh box

- evaluation/EDA/run_infer.py
- evaluation/agent_bench/run_infer.py
- evaluation/biocoder/run_infer.py
- evaluation/bird/run_infer.py
- evaluation/browsing_delegation/run_infer.py
- evaluation/gaia/run_infer.py
- evaluation/gorilla/run_infer.py
- evaluation/gpqa/run_infer.py
- evaluation/humanevalfix/run_infer.py
- evaluation/logic_reasoning/run_infer.py
- evaluation/miniwob/run_infer.py
- evaluation/mint/run_infer.py
- evaluation/ml_bench/run_infer.py
- evaluation/swe_bench/run_infer.py
- evaluation/toolqa/run_infer.py
- evaluation/webarena/run_infer.py
- opendevin/core/main.py
`max_budget_per_task` config is now mandatory positional arg, causing SWE-Bench to break.
---
- make max_budget_per_task optional in `run_agent_controller`
- pass `max_budget_per_task` as argument for all evals
---
> fix: make max_budget_per_task optional in `run_agent_controller`

- .github/workflows/run-unit-tests.yml
This PR attempts to fix colima startup by 
- preventing to start colima 2 times in a row (first with brew, then in `for` loop)
- use a docker context to separate docker resources for the runner instance
- use a random port number
---
- removed the initial mangling of colima start and delete, which shouldn't be necessary
- added env variable DOCKER_CONTEXT to be used by colima
> (fix) colima: use a docker context specific to runner; prevent duplicate start

- agenthub/README.md
This PR changes the title of the `agenthub` doc from "Agent Framework Research" to "Agent Hub".
> Change doc title of agent hub

- .github/workflows/ghcr-runtime.yml
Fix error in GitHub action `ghcr_push (od_runtime, amd64)` due to wrongly used image name.
@xingyaoww please let me know, if these changes look alright to you. 😃 
---
- Added steps for a) display of disk space and b) a `Free Disk Space` action.
- Tweaked `Load images and push to registry` to have `docker load` return an error if it fails.
- In the `tags` loop also checked for empty `image_name`
---
Initial successful run shows: "Final size is 7453141642 bytes"
> (fix) fixed ghcr_push use of image name

- .github/workflows/ghcr-runtime.yml
Fixes #3101  
The `ghcr_push` action did not take into account, that the created artifact was being downloaded as `zip` file and needed to be extracted first.
Action error on `mv` statement example:
https://github.com/OpenDevin/OpenDevin/actions/runs/10087360603/job/27893720863#step:7:1
This is not easy to test as that workflow is only triggered on `push` (which makes sense).
---
Added step to unzip the downloaded artifact before trying to move its content,
which should be a .tar file.
---
#3055
> (fix) Runtime yml missing zip handling (fixes #3101)

- .github/workflows/ghcr-runtime.yml
Fixes #3101  #3104 
From an error log where a download link mentioned ".zip" as extention, I mistakenly thought that the download would also have that, but the download-artifact action just downloads the file with the name it was given.
Here: it was uploaded without a file extention.
Thus removed the previously added unzip step again. Instead changed the `mv` command to copy the downloaded file to the expected filename with extension, so that the docker command can pick up that file.
This is cumbesome to test as that workflow is only triggered on `push` (which makes sense).
---
#3101 
#3055
> (fix) ghcr-runtime: no unzip, artifact downloads as-is (followup to #3104)

- poetry.lock
- pyproject.toml
The torch upgrade #3110 will trigger mac test error. Revert it.
---
> Fix: revert torch version

- .github/workflows/run-unit-tests.yml
- tests/unit/test_ipython.py
- tests/unit/test_runtime_build.py
- tests/unit/test_sandbox.py
@tobitege find that `test_runtime_build.py` failed to run, yet all those CI passed.
---
- Fix `test_runtime_build.py` so it matches the current implementation.
- Update `run-unit-tests.yml` so `test_runtime_build.py` is included in the testing.
---
> Fix(test,CI): runtime build tests

- opendevin/controller/agent_controller.py
- opendevin/server/session/session.py
Restore logging of user messages when using cli.
If logging happens only for the server session, it won't be logged when using cli, so this PR moves it a bit so that it happens for all cases.
> Always log user messages

- opendevin/controller/state/state.py
This PR proposes a quick fix for the behavior of `last_error` which is set on a number of errors, but never cleared: clear it at least when loading a session, because after reload we should have the history, including some error at the end if that happened, but behave normally again and eventually succeed new tasks etc (so this flag shouldn't be set).
> Clear last_error when restoring a session

- opendevin/controller/agent_controller.py
- opendevin/core/main.py
This PR proposes a fix for the `max_budget_per_task` attribute when running from CLI: set agent in ERROR state since we cannot use PAUSED (we cannot resume) and use value from config when no user value overrides it from the command line parameters.
> Fix max budget per task error in headless mode

- agenthub/codeact_agent/codeact_agent.py
Since we have an AgentFinishAction sent by the agent in CodeAct, the agent is able to send a lot of messages in the `thoughts` attribute, even a full solution of the task at hand. This needs inserted in the prompt, otherwise the agent is re-doing the task it had done already.
This PR proposes a fix.
Example (session done, ended, followed by session restore)
Before this PR: 
```
write concisely about the moon. very short
----------
Let's get back on track. If you experienced errors before, do NOT resume your task. Ask me about it.
----------
The Moon is Earth's only natural satellite. It orbits Earth and is about 384,400 km away. The Moon's surface is covered with craters, mountains, and plains called maria. It has a significant impact on Earth's tides due to its gravitational pull. The …
```
> Finish action is missing from the prompt

- opendevin/runtime/client/client.py
- opendevin/runtime/docker/ssh_box.py
[Action link](https://github.com/OpenDevin/OpenDevin/actions/runs/10140735788/job/28037474949?pr=3156#step:8:1907) from #3156
---
Parsed the first line
---
> Fix: Parse exit code correctly for background commands

- tests/unit/test_llm.py
This PR was mostly created as an example of how OpenDevin can create a PR for OpenDevin, but it also increases our code coverage by adding a test for a previously untested file (`llm.py`'s init function).
> Add unit tests for LLM init function

- .github/workflows/dummy-agent-test.yml
- .github/workflows/review-pr.yml
- .github/workflows/run-unit-tests.yml
- .github/workflows/solve-issue.yml
- Makefile
- containers/app/Dockerfile
- opendevin/memory/memory.py
- opendevin/runtime/utils/runtime_templates/Dockerfile.j2
- pyproject.toml
---
- Reduce dependency installed for runtime (only `main` and `runtime`) to speed up CI and reduce image size
- Make llama-index an optional dependency (so we don't need to install `torch`). `LongTermMemory` is the only one class that depends on it, but it is not currently used anywhere in OpenDevin.
- Make `LongTermMemory` optional and prompt user to manually install `poetry install --with llama-index` when it is needed.
---
> [Runtime] Reduce dependency to speed up CI and reduce image size

- evaluation/miniwob/run_infer.py
The miniwob evaluation doesn't apply the config's values in its DockerSSHBox initialization, if None is passed in.
---
Added parameters to `get_sandbox` to initialize the docker_ssh_box if None.
---
Follows #3075
> (Eval) Apply config arguments for miniwob ssh box if None is passed

- tests/integration/regenerate.sh
The latest version of regenerate.sh fails on my machine (Mac), because realpath requires existing files. This looks like a regression from [PR 2935](https://github.com/OpenDevin/OpenDevin/pull/2935).
This PR proposes to simply restore the lines with non-existent files/directories, as it worked before PR 2935. The rest appears to work fine.
```
> tests/integration/regenerate.sh
realpath: /Users/enyst/repos/devin/_test_workspace: No such file or directory
```
```
man 3 realpath
...
All components of
file_name must exist when realpath() is called.
```
> Remove the use of realpath when the file doesn't exist

- evaluation/mint/run_infer.py
- opendevin/runtime/client/client.py
- opendevin/runtime/client/runtime.py
- opendevin/runtime/docker/ssh_box.py
- opendevin/runtime/plugins/agent_skills/__init__.py
- opendevin/runtime/plugins/jupyter/__init__.py
- opendevin/runtime/plugins/mixin.py
- opendevin/runtime/plugins/swe_agent_commands/__init__.py
- opendevin/runtime/runtime.py
- opendevin/runtime/server/runtime.py
- tests/unit/test_runtime.py
In order for evaluations to run using the new `EventStreamRuntime`, we need to support `copy_to` method for `Runtime`.
---
- Add `copy_to` for Runtime
- Add tests for `copy_to` in `test_runtime`
---
> [arch] Implement `copy_to` for Runtime

- evaluation/EDA/run_infer.py
- evaluation/agent_bench/run_infer.py
- evaluation/biocoder/run_infer.py
- evaluation/bird/run_infer.py
- evaluation/browsing_delegation/run_infer.py
- evaluation/gaia/run_infer.py
- evaluation/gorilla/run_infer.py
- evaluation/gpqa/run_infer.py
- evaluation/humanevalfix/run_infer.py
- evaluation/logic_reasoning/run_infer.py
- evaluation/miniwob/run_infer.py
- evaluation/mint/run_infer.py
- evaluation/ml_bench/run_infer.py
- evaluation/swe_bench/run_infer.py
- evaluation/toolqa/run_infer.py
- evaluation/webarena/run_infer.py
- opendevin/core/main.py
A general rule (after discussion with @neubig in #3184) is that we try to minimize the overlap between different input arguments.
For example, in `run_controller`, now we have two things:
- `max_budget_per_task` (higher priority), which overlaps with `config.max_budget_per_task`
-  `max_iterations` (higher priority), which overlaps with `config.max_iterations`
---
This PR tries to get rid of this overlap and remove the two extra input arguments to make `run_controller` a relatively simpler interface.
TODO for future PRs (as discussed with @neubig), we should break the gigantic `AppConfig` into …
> [Config] Reduce the duplication in `run_controller` argument

- opendevin/runtime/client/runtime.py
- `EventStreamRuntime` in its initialization did not copy over the passed `config` values to its own `self.config`, thus the base runtime did not get e.g. a changed value like `run_as_devin` as it happens in `test_runtime.py` (see: `test_ipython_multi_user`).
- Added more logging to runtime
- Changed max retry wait from 600 to 60 seconds as it otherwise would wait a painfully long time
---
In `test_runtime.py` several tests will be called twice for `run_as_devin` of True and False (root).
Even though the` _load_runtime` fixture instantiates a new `EventStreamRuntime` each time, the underlying base …
> (fix) EventStreamRuntime: fix config passing on init (fixes test_runtime.py errors)

- opendevin/core/config.py
- opendevin/events/observation/browse.py
- opendevin/runtime/browser/browser_env.py
- opendevin/runtime/browser/utils.py
- opendevin/runtime/client/client.py
- opendevin/runtime/client/runtime.py
- tests/unit/test_runtime.py
Part of https://github.com/OpenDevin/OpenDevin/pull/3230.
---
- Add `browsergym_eval_env` to `SandboxConfig` to specify the browserGym's environment name for evaluation. By default, it is `None` (open-ended browsing environment for the agent).
- Remove the mounted folder hack (cc @frankxu2004) for getting the observation.
- For evaluation: Support getting the goal via `BrowseInteractiveAction(browser_actions='GET_EVAL_GOAL')` AND getting the rewards via `BrowseInteractiveAction(browser_actions='GET_EVAL_REWARDS')`
- Build a MiniWob docker image and add a test case for it.
Example use case in #3230 …
> [Eval, Browser] Refactor Browser Env so it works with `EventStreamRuntime` for Browsing Evaluation

- .github/workflows/deploy-docs.yml
- .github/workflows/ghcr.yml
Attempt to reduce CI workflow execution time, for PR's only, dependent on affected paths.
E.g. we don't need to build images if changes were only in `docs` folder or to `.md` files.
@xingyaoww I have left out the `frontend` folder as that is covered by other tests, and this PR is not touching `push`, so this should be no problem?
---
Applied to the `pull_request` section `paths` and `paths-ignore` criteria.
> (workflow) ghcr.yml with paths/paths-ignore conditions for pull_request

- opendevin/core/config.py
- opendevin/runtime/client/runtime.py
- opendevin/runtime/utils/runtime_build.py
- opendevin/runtime/utils/runtime_templates/Dockerfile.j2
- tests/unit/test_runtime_build.py
Part of #2404, #3230.
For some evaluation (e.g., Logical reasoning, MINT) to work, you have to pre-install dependencies on the "OD's Python interpreter," which is used to power the "IPython."
We allow each eval to use their own `Dockerfile`, so the dependencies can be pre-installed for "bash", but not "IPython," since that's built on top of the user-provided base image on the fly:
https://github.com/OpenDevin/OpenDevin/blob/5469f67cb9a1f1b345dc872a1cdb799451fe5e27/evaluation/logic_reasoning/Dockerfile#L1-L5
---
- Add `od_runtime_extra_deps` to `SandboxConfig`, which allows us to inject dependencies …
> [Arch, Eval] Allowing injecting additional dependency to OD runtime docker image

- .github/workflows/clean-up.yml
- .github/workflows/ghcr.yml
To prevent further out of disk space issues, we have to have some workflow to remove outdated workflow runs and their artifacts. This PR introduces `clean-up.yml` to offer this feature.
- In this first iteration this workflow needs to be dispatched manually as it offers manual filtering. If we want to go full automatic with a cron job, we need to specify the desired values, either in this or a follow-up PR.
- Added `retention-days: 14` flag to the 2 `upload-artifact` occurences in `ghcr.yml`
---
- The new script is closely based on the action's example (see reference below) with removing entries …
> (backend) Added workflow clean-up.yml to remove old workflows and artifacts

- opendevin/runtime/client/runtime.py
Currently if `init_runtime_tools` is called when using the event stream runtime OpenDevin dies. This changes it to a warning (this should be removed when server runtime is deprecated).
> Add init_runtime_tools for event stream runtime

- containers/app/Dockerfile
As per Sonnet, the first line `ARG` command only applies to the first `FROM` Docker section.
Thus added a line to redeclare it, as occasionally runs reported a warning like this:
`UndefinedVar: Usage of undefined variable '$OPEN_DEVIN_BUILD_VERSION' (line 41)`
---
Added `ARG` line for final `FROM` section.
> (fix) Dockerfile for app: re-declare ARG OPEN_DEVIN_BUILD_VERSION

- tests/unit/test_listen.py
`opendevin/server/listen.py` had no unit tests, so in testing OpenDevin I asked it to write some.
Prompt:
```
The repo https://github.com/OpenDevin/OpenDevin/
Please clone it locally and cd into the OpenDevin directory.
Then you can run `poetry install` to install all the dependencies.
Within this larger OpenDevin directory, there is a file opendevin/server/listen.py that has no tests.
Please create a file called tests/unit/test_listen.py and write tests that test the functionality in this directory.
If you need to use a `Runtime` object, try to use `EventStreamRuntime`, which is implemented in opendevin/runtime/client/runtime.py.
You can mock its various …
```
> Improve listen.py test coverage

- containers/app/Dockerfile
Fix https://github.com/OpenDevin/OpenDevin/issues/3283.
---
- Include `pyproject.toml` and `poetry.lock` inside `app` container, since it is required for `EventStreamRuntime` builder to create source code distribution
---
> fix: copy over pyproject and poetry lock for App docker

- .github/workflows/ghcr.yml
Revert #3240 to remove `paths_ignore` option again as this blocked some required workflows.
> (fix) revert #3240 - remove paths_ignore in ghcr.yml again

- .github/workflows/ghcr.yml
Try to fix this error in workflow:
`Error parsing reference: "ghcr.io/opendevin/od_runtime:$DOCKER_IMAGE_TAG_arm64" is not a valid repository/tag: invalid reference format`
---
Processing of tags within the matrix seemed to be the issue. Need to see test runs if this approach by Sonnet works.
---
Example action where this last was observed:
https://github.com/OpenDevin/OpenDevin/actions/runs/10316652985/job/28561146144#step:7:27
> (fix) fix error in ghcr_push_runtime (tags processing)

- docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md
- docs/modules/usage/custom_sandbox_guide.md
persist_sandbox was removed as a setting recently, but it still persisted in some doc.
> Remove some obsolete examples of persist_sandbox in the doc

- .github/workflows/ghcr.yml
This should finally fix this error in workflows on merges:
```Error parsing reference: "ghcr.io/opendevin/od_runtime:$DOCKER_IMAGE_TAG_amd64" is not a valid repository/tag: invalid reference format```
Follow-up to #3311 
---
This line had single-quotes and thus the env vars were not expanded, i.e. they were written "as is" into the tags.txt file:
```echo "$DOCKER_IMAGE_TAG $DOCKER_IMAGE_HASH_TAG" >> tags.txt```
---
https://github.com/OpenDevin/OpenDevin/actions/runs/10318854385/job/28567802141#step:7:26
> (fix) fix wrong quotes around env vars in ghcr.yml

- frontend/src/components/Resizable.tsx
The first time you mouse down to drag resize a panel it does not work. It only works on subsequent mouse down events.
The reason is that the current implementation has a flaw (It is not surprising as this is something difficult to get right)
`onMouseDown` calls `setDividerPosition` which triggers a re-render, making the code inside useEffect obsolete - it is applied to a context which no longer exists.
The update moves the onMouseMove and onMouseUp inside the useEffect and adds a destructor, meaning that:
* `onMouseMove` and `onMouseUp` are not applied and do not exist unless a mouse down has occurred, setting the `dividerPosition`
* `onMouseMove` resizes the ref but does not trigger a re-render.
* `onMouseUp` removes the event listeners and triggers a re-render
* The destructor (Called …
> Bug fix drag resize

- .github/dependabot.yml
Docusaurus requires multiple packages be upgraded at the same time, causing dependabot updates to fail:
- https://github.com/OpenDevin/OpenDevin/pull/3347
- https://github.com/OpenDevin/OpenDevin/pull/3345
- https://github.com/OpenDevin/OpenDevin/pull/3343
This PR uses [dependabot groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) to group these into a single PR, which should hopefully solve the problem.
> Group docusaurus dependabot updates

- .github/dependabot.yml
Followup to #3359 to move the newly added `groups` to proper sections.
---
Previous implementation put the `groups` as sortof "independent" entry, which causes errors.
> (fix) correct dependabot.yml groups

- .github/dependabot.yml
This PR adds a depandabot group for eslint, which should help fix errors in the version upgrade here: https://github.com/OpenDevin/OpenDevin/pull/3368
> Add dependabot group for eslint

- MANIFEST.in
Fixes #3169 to avoid permission errors upon call of `build` (sdist)
---
Added special manifest file to exclude Python cache files and folders from sdist.
These cache files are not needed, but can cause errors at runtime due to different file permissions.
---
> (fix) exclude Python cache files/folders from sdist

- agenthub/codeact_agent/codeact_agent.py
- opendevin/controller/agent_controller.py
- opendevin/events/action/agent.py
- opendevin/events/observation/delegate.py
- tests/unit/test_codeact_agent.py
This PR fixes https://github.com/OpenDevin/OpenDevin/issues/3356 , which was causing CodeAct to die on an `ErrorObservation`, because no message was being produced for this.
This PR makes sure that:
- Adds a message for CodeAct so that it creates a message for ErrorObservation
- Makes it so that a `ValueError` is raised on an unhandled observation in CodeAct, because all observations should be handled
- Adds tests for CodeAct's get message function
- Adds some documentation for AgentDelegateAction, where the arguments were unclear
> Handle error observations in codeact

- opendevin/runtime/client/runtime.py
- opendevin/runtime/utils/runtime_build.py
Attempt to fix #3169 : run the subprocess for build as shell command so that it should inherit permissions.
Also increased minimum wait time in `_ensure_session` to 10 seconds.
---
Same as above.
> _create_project_source_dist: run subprocess as shell

- opendevin/runtime/builder/__init__.py
- opendevin/runtime/builder/base.py
- opendevin/runtime/builder/docker.py
- opendevin/runtime/client/runtime.py
- opendevin/runtime/utils/runtime_build.py
- tests/unit/test_runtime_build.py
We are working on a hosted version of the Runtime environment so that users can have the option to run the sandbox over an API endpoint and do not need to set up docker locally (docker setup is typically not feasible in HPC clusters).
---
- This PR creates a new abstraction, `RuntimeBuilder`, to handle runtime images building utilities. This allows us to build a stable interface for the runtime build, and we can later implement the same interface to build docker images over API.
---
> feat: refactor image building logic into runtime builder

- .github/workflows/deploy-docs.yml
- .github/workflows/dummy-agent-test.yml
- .github/workflows/ghcr.yml
- .github/workflows/lint.yml
- .github/workflows/run-unit-tests.yml
If the deploy docs workflow happens while another workflow is running, it will fail. This makes sure only one workflow runs at a time.
Added comments
---
---
> fix: Only run one deploy docs workflow at a time. Add comments

- containers/app/Dockerfile
Previously added `MANIFEST.in` file needs to be copied into the app container at least.
---
Just added a COPY command.
---
Follow up to #3381
> copy manifest file into container

- opendevin/runtime/client/client.py
Prevent below error during sandbox startup:
```RuntimeError: Failed to create user opendevin: useradd: UID 1000 is not unique```
---
The `_init_user` method now first checks, if the given username (e.g. `opendevin`) already exists.
If yes, it can return early.
Otherwise it'll try to add the user with the given user id (usually 1000) and **IF** that fails with a `not unique` error, it will increase the user id and retry, e.g.
```py
04:57:04 - opendevin:WARNING: client.py:158 - UID 1000 is not unique. Incrementing UID and retrying...
04:57:04 - opendevin:DEBUG: client.py:153 - Added user opendevin …
```
> (fix) RuntimeClient: make _init_user more robust

- evaluation/EDA/game.py
- evaluation/mint/datatypes.py
- evaluation/mint/env.py
- evaluation/mint/run_infer.py
- evaluation/mint/tasks/base.py
- evaluation/mint/tasks/codegen.py
- evaluation/mint/tasks/reasoning.py
- evaluation/mint/utils.py
- opendevin/controller/agent_controller.py
- opendevin/runtime/client/runtime.py
- opendevin/runtime/plugins/agent_skills/agentskills.py
- opendevin/security/invariant/analyzer.py
- opendevin/security/invariant/client.py
- opendevin/security/invariant/nodes.py
- opendevin/security/invariant/parser.py
- opendevin/server/session/agent.py
- opendevin/server/session/manager.py
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython/prompt_001.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython/prompt_002.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython_module/prompt_001.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython_module/prompt_002.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython_module/prompt_003.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython_module/prompt_004.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython/prompt_001.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython/prompt_002.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython_module/prompt_001.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython_module/prompt_002.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython_module/prompt_003.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython_module/prompt_004.log
Since we support python 3.11+, we use generic types (list, tuple) and simpler syntax (| None). But Copilot likes the old capitalized versions from the typing module (List, Tuple), and they sneak in the codebase, so it seems that once in a while we need to clear them out.
For example, older clearing: https://github.com/OpenDevin/OpenDevin/pull/1680
> Use generic types

- .github/workflows/deploy-docs.yml
- .github/workflows/fe-unit-tests.yml
- .github/workflows/py-unit-tests.yml
The split isn't quite necessary but it's a quality of life improvement. Just makes following the different workflows easier.
The real change is: Always run all unit tests. This is a minimum test that should always be run, especially on main (This was being skipped on main pushes that only had the paths-ignore changes.)
---
---
> Split Frontend and Python Unit tests

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/chat/ChatMessage.tsx
- frontend/src/index.css
This is intended to address https://github.com/OpenDevin/OpenDevin/issues/3242
Using remark-gfm to support markdown tables in the chat. I also added some CSS padding to make the look more consistent.
Enter a table in the chat window. e.g.:
```
| Month    | Savings |
| -------- | ------- |
| January  | $250    |
| February | $80     |
| March    | $420    |
```
> Added remark gfm to render markdown tables

- containers/app/Dockerfile
- containers/app/entrypoint.sh
Fix https://github.com/OpenDevin/OpenDevin/issues/3169.
The permission issue is likely caused by weird `.pyc` file that's owned by `opendevin:opendevin`
---
- The `setgid` bit (represented by `2`) ensures that new files and directories created within `/app` will inherit the group ownership (`app`) from the parent directory.
- Add `opendevin` to the group of `enduser` to hopefully address the 
---
> fix: app docker permission issue

- .github/workflows/clean-up.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/dummy-agent-test.yml
- .github/workflows/lint.yml
- .github/workflows/stale.yml
* Concurrency should be used only in places that might cause conflicts if two jobs running cause conflicts with each other (ex: Deploy docs to github)
* Removed unnecessary concurrencies
* Added more comments to workflows
---
---
> Remove unnecessary concurrency and add more comments

- .github/workflows/ghcr.yml
`if` condition for `ghcr_push` and other jobs needed extra checks to not be skipped on PR merge.
---
The `if` condition for this job states that it should only run when:
- The GitHub reference is refs/heads/main (i.e., pushes to the main branch)
- OR when the reference starts with refs/tags/ (i.e., when a new tag is created)
When a **_pull request_** is merged to the main branch, the workflow runs in the context of the pull request, not the main branch itself.
In a pull request context, the github.ref would typically be something like refs/pull/123/merge, not refs/heads/main. 
This means the …
> (fix) jobs need if condition modified to enable run on PR push

- agenthub/browsing_agent/browsing_agent.py
- agenthub/codeact_agent/codeact_agent.py
- agenthub/codeact_swe_agent/codeact_swe_agent.py
- agenthub/delegator_agent/agent.py
- agenthub/dummy_agent/agent.py
- agenthub/micro/agent.py
- agenthub/planner_agent/agent.py
- opendevin/controller/agent.py
- opendevin/controller/agent_controller.py
- opendevin/core/config.py
- opendevin/core/main.py
- opendevin/server/session/agent.py
- opendevin/server/session/session.py
- tests/unit/test_codeact_agent.py
- tests/unit/test_config.py
- tests/unit/test_micro_agents.py
This PR proposes to start adapting agent config to use for each agent options, similarly as we do with LLM / LLMConfig. 
Agent configs will likely have more attributes than today in the near future. I think that in a follow-up PR, we can move embeddings options from LLMConfig to a MemoryConfig, part of agent config (e.g. allow to enable/disable history summarization or caching per agent). Since those are not the same models, they don't quite belong with the completion LLM settings already. Also, LLMConfig is becoming quite large itself, it seems like we can break from it the stuff that is different after all.
- send both llm and agent_config for initialization of an agent.
> Refactor agent to accept agent config

- opendevin/core/config.py
- opendevin/core/main.py
- opendevin/runtime/client/runtime.py
- opendevin/server/session/agent.py
- tests/unit/test_arg_parser.py
There are no issues posted, but this is a fix for a real issue: cannot restore history from the event stream if running headless.
This PR proposes a fix that keeps it simple but is starting to introduce a bit of flexibility in handling command-line sessions:
- a command line arg "-n" or "--name" for the session name
- start using jwt_secret for the sid.
Maybe sometime we'll want a real cli client, this is just a bit on the road. 😄 
Note: this only concerns the sid that is used as name for the event stream. All uses of `create_runtime` in evals create their own `sid` too and send it, so we fix the uniqueness of their respective event stream from there. This PR doesn't change that for the container name there is more unique stuff added.
> Fix restore cli sessions

- opendevin/runtime/client/runtime.py
Revert an extra 1 second delay from a frequently called method in client `runtime`, which added a noticable delay compared to previous versions.
---
This reverts a line added by me in PR #3233
> (fix) revert a 1s sleep from _ensure_session (runtime)

- opendevin/core/main.py
Previously, the [typing](https://github.com/OpenDevin/OpenDevin/blob/b2221f135f36d8a94585c7cf87c451272ac91fe9/opendevin/core/main.py#L78) on `fake_user_response_func` did not match the [actual type](https://github.com/OpenDevin/OpenDevin/blob/b2221f135f36d8a94585c7cf87c451272ac91fe9/evaluation/utils/shared.py#L69) of `codeact_user_response`.
This didn't cause errors in CI because our typing checks in CI are rather lenient, but it's incorrect and was throwing errors in my IDE, so it'd probably be nicer to fix it.
This PR creates a [typing protocol](https://typing.readthedocs.io/en/latest/spec/protocol. …
> Fix typing for fake user response function

- agenthub/browsing_agent/browsing_agent.py
- agenthub/codeact_agent/codeact_agent.py
- agenthub/codeact_swe_agent/codeact_swe_agent.py
- agenthub/planner_agent/agent.py
- opendevin/controller/agent.py
- opendevin/runtime/tools.py
We deprecate `RuntimeTool` since the completion of runtime refactor.
---
This PR removes the remaining occurrence of `RuntimeTool` to clean up the codebase.
---
> chore: remove deprecated RuntimeTool

- .github/workflows/ghcr.yml
Bump outdated `docker/login-action@v2` to v3 to resolve warnings about Node versions.
> (workflow) ghcr.yml: bump docker/login-action@v2 to v3

- docs/modules/usage/how-to/custom-sandbox-guide.md
- openhands/README.md
- openhands/runtime/utils/runtime_build.py
this link in README and comment is wrong: https://docs.all-hands.dev/modules/usage/runtime , it should be: https://docs.all-hands.dev/modules/usage/architecture/runtime
---
---
> Fix wrong doc url

- evaluation/aider_bench/run_infer.py
- openhands/controller/agent_controller.py
Accumulated cost is 0.0 when agent times out.
---
Update metrics with local_metrics when Agent reached ERROR state.
---
> [Fix] Metrics should be updated when agent reaches max iterations.

- docs/modules/usage/llms/llms.md
- docs/modules/usage/llms/openai-llms.md
There was no guide for OpenAI LLMs
---
---
> docs: Update to include guide for OpenAI LLMs

- frontend/package-lock.json
npm (frontend): Fix 1 moderate severity vulnerability in `micromatch` (`frontend/package-lock.json`)
---
```sh
micromatch  <4.0.8
Severity: moderate
Regular Expression Denial of Service (ReDoS) in micromatch - https://github.com/advisories/GHSA-952p-6rrq-rcjv
fix available via `npm audit fix`
node_modules/micromatch
```
> (Sec) npm: fix Regular Expression Denial of Service (ReDoS) in micromatch

- evaluation/aider_bench/README.md
- evaluation/aider_bench/run_infer.py
- evaluation/aider_bench/scripts/run_infer.sh
- evaluation/utils/shared.py
- openhands/core/config.py
- poetry.lock
- pyproject.toml
- tests/unit/test_arg_parser.py
- added `eval_ids` command line argument to provide a comma-separated list of instance id's to run
- updated parser and unit test to account for the added argument
- fixed typos mentioning `agent_bench` instead of `aider_bench` and fixed name of `summarize_results.py`
- extended README.md with new argument
- had to add `dotnet` to `pyproject.toml` file or the `run_infer.py` would error out agenthub dependency
Example:
```sh
./evaluation/aider_bench/scripts/run_infer.sh allhands HEAD CodeActAgent 1 1 "37,74"
```
> (eval) Aider_bench: add eval_ids arg to run specific instance id's

- .github/pull_request_template.md
In an effort to make better CHANGELOGs going forward, we are changing the PR template. 
Maintainers must always make sure that the simple explanation used for CHANGELOG is filled out.
---
---
> Change PR template to enforce a simple description for CHANGELOG

- agenthub/codeact_agent/README.md
- evaluation/utils/shared.py
API key is being exposed in the evaluation outputs.
---
* Also Updated agent_skills in README.md
> [Fix] Stop exposing API key in evaluation outputs.

- openhands/runtime/client/runtime.py
- openhands/runtime/utils/runtime_build.py
EventStreamRuntime will wait for runtime client to be initialized once, for up to 10s. 
---
The runtime starts the client and should wait for its full initialization before resuming normal processing.
This will only be done once and only for up to 10 seconds so to not get stuck.
@xingyaoww Let me know what you think about this approach.
> (feat) runtime: in _wait_until_alive upon start wait for client to have initialized too

- evaluation/aider_bench/README.md
- evaluation/aider_bench/helper.py
- evaluation/aider_bench/run_infer.py
- evaluation/aider_bench/scripts/run_infer.sh
Allow the Aider Benchmark to be run in 2 modes - with/without the Agent having the ability to use unittests to influence its editing accuracy.
> Enabling of unittests in aider benchmark should be optional.

- README.md
- docs/src/components/HomepageHeader/HomepageHeader.tsx
- evaluation/README.md
- evaluation/aider_bench/README.md
- evaluation/aider_bench/run_infer.py
- evaluation/aider_bench/scripts/summarize_results.py
- evaluation/miniwob/README.md
- evaluation/swe_bench/README.md
- evaluation/utils/shared.py
- evaluation/webarena/README.md
- openhands/runtime/utils/system.py
Make Aider-Bench run resumable with optional `SKIP_NUM` env flag
---
- added optional `SKIP_NUM` env flag (int) which specifies the number of instances in the dataset to be skipped first, thus offering to resume a bench
- in `shared.py`, the `prepare_dataset` got a new optional parameter
- in that method, if a `skip_num` was given, it will combine this with the `eval_n_limit` number, so a run could skip the first 42 incidents and then run 10 instances
- temporarily changed links for huggingface evaluations to use the old repo name as the new one while the new one is in the works
> (enh) Aider-Bench: make resumable with skip_num arg

- .github/workflows/regenerate_integration_tests.yml
I really struggle to run the integration tests locally. This script would allow us to run them inside of a GitHub action
Most likely we will need to set an LLM_API_KEY as well.
---
For now, this just makes a minor change to README.md, so I can check the logic of the workflow. But it needs to be checked into main before I can run it manually to test it.
Once it's verified working, I will follow up with another PR that actually gets it to regenerate
---
> add (placeholder) workflow for regenerating the integration tests

- .github/workflows/ghcr_runtime.yml
We don't need to run this build step for non-forks. This should save a few min
---
---
> Fix GitHub action gate for fork build step

- evaluation/aider_bench/run_infer.py
- evaluation/utils/shared.py
Fixes potential logfile name if model has `:` character in it. Improve instruction on how to call the (optional) test case to prevent timeouts.
---
- Any colon `:` in a model name, like `nousresearch/hermes-3-llama-3.1-405b:extended` prevents logging to file as there won't be a folder created.
- If the use of the unit test is enabled (env var option), the LLM's have all different ideas on _how_ to _execute_ that test, which often resulted in timeouts. The instruction to the LLM has been improved to use the same format as the bench would use itself,
e.g. `python -m unittest …
> (fix) Aider bench: logname fix; improve test calling instruction

- openhands/runtime/plugins/agent_skills/file_ops/file_ops.py
Fix a potential issue that might lead to file corruption when edit linting is enabled
---
#3124 introduces a feature for editing: running linter twice before and after the change and only extract new errors introduced by the agent. This has some potential issues and I am working on #3649 to address them, but I feel like I am not gonna finish it in the next few days, and that PR has become harder and harder to review, thus this PR, which only focuses on a small improvement.
So what's the issue? When we run linters on the original file before our edits, we need to copy the original file …
> file_ops: Use tmp file for original linting

- frontend/src/utils/extractModelAndProvider.test.ts
- frontend/src/utils/extractModelAndProvider.ts
- frontend/src/utils/organizeModelsAndProviders.test.ts
- frontend/src/utils/organizeModelsAndProviders.ts
- frontend/src/utils/verified-models.ts
**CHANGELOG**
- Selecting the anthropic provider now points to the correct litellm model
**PROBLEM**
LiteLLM returns two types of model IDs for Anthropic (and actually other providers too). The first type has a pattern as `anthropic.claude-3-5-sonnet-20240620`. The second is of the type `claude-3-5-sonnet-20240620` which is the one we want.
The first pattern is either outdated and incompatible and defaults/assumes a Bedrock configuration or the first pattern is actually for Bedrock configurations.
The helper functions that parse the models were using the first pattern and storing the second under the `other` provider.
**SOLUTION**
The parser now ignores the models with a `.` separator and groups the anthropic models with a `/` separator (e.g., `claude-3-5-sonnet-20240620` is now …
> hotfix: Anthropic provider points to the correct LiteLLM model ID

- openhands/llm/llm.py
Forgot to remove litellm verbose mode from earlier PR
---
Just one line removed in llm.py.
> (fix) revert enabling litellm verbose mode from testing

- evaluation/swe_bench/run_infer.py
---
SWE-Bench originally represents 'PASS_TO_PASS', 'FAIL_TO_PASS' as a string, although it essentially is, and should be better represented as a list of strings. This PR allows for that format.
@xingyaoww should be able to review this :)
---
> Allow Generalized SWE-Bench format for evaluation

- .github/workflows/ghcr_runtime.yml
- .github/workflows/py-unit-tests.yml
- .github/workflows/regenerate_integration_tests.yml
- openhands/runtime/client/runtime.py
- tests/runtime/test_env_vars.py
Reduce workflow runtime by applying specific caching action. Also removed 2 image test from matrix.
---
As per recent discussion in Slack, we have Nikolaik as the main base image and now remove the extra 2 image testing rounds from the workflow to reduce used resources/test times.
- The existing python setup action didn't need caching, it runs only ~10 seconds anyways
- Added cache@v4 action for poetry dependencies, which results in a ~1.1 GB cache entry (vastly different from the one reported in the "setting up python" step!)
- Thus, as long as the `poetry.lock` doesn't change, this …
> (enh) add caching@v4 action in workflows

- openhands/llm/llm.py
- openhands/runtime/client/client.py
- openhands/runtime/client/runtime.py
- tests/integration/mock/eventstream_runtime/BrowsingAgent/test_browse_internet/prompt_001.log
- tests/integration/mock/eventstream_runtime/BrowsingAgent/test_browse_internet/prompt_002.log
- tests/integration/mock/eventstream_runtime/BrowsingAgent/test_browse_internet/prompt_003.log
- tests/integration/mock/eventstream_runtime/BrowsingAgent/test_browse_internet/response_001.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/prompt_002.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/prompt_003.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/prompt_004.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/prompt_005.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/response_001.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/response_002.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/response_003.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/response_004.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/response_005.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython/prompt_001.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython/prompt_002.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython/prompt_003.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython/response_001.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython/response_002.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython/response_003.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_browse_internet/prompt_001.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_browse_internet/prompt_002.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_browse_internet/response_001.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_browse_internet/response_002.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython/prompt_001.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython/prompt_002.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython/response_002.log
- tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython/response_003.log
Fix logging of LLM messages (if enabled) and client readiness detection in EventStreamRuntime
---
- Unfortunately a recent PR of mine broke the logging of LLM messages to file, which caused integration test mock files to miss the user prompt for some agents+test combos.
EDIT: ~~Newer PR's since then started to fail.~~ The regeneration of integration mock files for PR's was problematic.
- For the `EventStreamRuntime` the client readiness detection was moved to the actual `LogBuffer` class. In some situations, depending on timing, OH could've gotten stuck on getting docker container logs. …
> Regression fixes: LLM logging; client readiness (EventStreamRuntime)

- .github/workflows/ghcr_runtime.yml
- openhands/runtime/client/runtime.py
- tests/runtime/conftest.py
- tests/runtime/test_bash.py
- tests/runtime/test_browsing.py
- tests/runtime/test_env_vars.py
- tests/runtime/test_images.py
- tests/runtime/test_ipython.py
Reduce runtime tests duration by running them across CPUs
---
* Remove the python and node matrixes because nikolaik already has all of those installed and we use it as our default runtime
* Reduce runtime tests duration by running them across CPUs using pytest-xdist
---
> Reduce runtime tests duration by running them across CPUs

- .github/workflows/ghcr_runtime.yml
Fail the Runtime tests check if the previous jobs were cancelled or failed
---
If the required tests fail or get cancelled, the last check is skipped which gets treated as success and PRs are able to merge.
---
> Fail the Runtime tests check if the previous jobs were cancelled or failed

- tests/integration/README.md
Documentation update alerting the user to an additional required step when running integration tests locally.
> docs: Update steps for running integration tests in a local environment

- frontend/src/components/modals/settings/ModelSelector.tsx
- frontend/src/services/settings.ts
Fixes an issue where OpenAI models always trigger the "advanced settings" window
---
Removes the optional `openai/` prefix for OpenAI models
---
CC @amanape in case this is a terrible idea. I did test for gpt4-o and 3.5
> fix advanced settings issue

- .github/workflows/pypi-release.yml
Make the publish PyPi manual to fit current release process
---
This workflow currently gets automatically kicked off by a tagged run. However, this doesn't fit our current release process. Making it manual for now until we can automate it
---
> Make the publish PyPi manual to fit current release process

- evaluation/swe_bench/run_infer.py
- evaluation/utils/shared.py
- openhands/runtime/builder/remote.py
- openhands/runtime/remote/runtime.py
- openhands/runtime/utils/request.py
---
- Re-use `send_request` for all `RemoteRuntime` requests
- Be more specific on exception handling
- Add more robust error handling for `run_evaluation`: whenever an instance failed, add the instance back to the queue and retry.
---
> refactor & improve retry for the reliability of `RemoteRuntime` & evaluation

- evaluation/utils/shared.py
**CHANGELOG**
Fix for method in SWE-bench unsupported on Mac
---
```
ERROR:root:  File "/Users/enyst/repos/odie/evaluation/swe_bench/run_infer.py", line 477, in <module>
run_evaluation(
"/Users/enyst/repos/odie/evaluation/utils/shared.py", line 270, in run_evaluation
total_instances = instance_queue.qsize()
"/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/queues.py", line 126, in qsize
return self._maxsize - self._sem._semlock._get_value()
ERROR:root:<class 'NotImplementedError'>:
```
---
> Fix queue length on Mac

- openhands/runtime/client/runtime.py
No longer defer container logs after runtime `run_action` (EventStreamRuntime)
---
- the container logs were not directly updated after a `run_command` in the `EventStreamRuntime`
- this caused a "lagging" of logs showing in dev terminal
Issue is easy to reproduce:
- in `File Explorer` click different files (which can be displayed in the Code Editor) 
- observe that their content appears on the _next_ click in the terminal's docker logs, not immediately after
---
> (fix) Update logs after run_action (EventStreamRuntime)

- docs/modules/usage/llms/groq.md
- docs/modules/usage/llms/openai-llms.md
- openhands/runtime/client/runtime.py
**CHANGELOG**
Just some docs, so we have clear cases what works:
- using provider groq
- using openai proxies
---
@mamoodi TBH Groq is a little strange to add along the other "llms", since it has no models of its own, it just serves [a number of models](https://console.groq.com/docs/models) - presumably to showcase how fast their chips are. But maybe it's better to have a few notes documented than be unsure how it works?
> Add docs for Groq and for OpenAI proxies

- openhands/runtime/client/runtime.py
EventStreamRuntime: tweak _wait_until_alive tenacity and exception handling
---
- extra docker log fetching in `run_action` (PR #3870) commented out and added TODO
- added exception handling to leave method on KeyboardInterrupt
---
Fixes #3876
> (fix) runtime: tweak _wait_until_alive tenacity and exception handling

- openhands/controller/agent_controller.py
- tests/unit/test_agent_controller.py
mainly on refactor the logic in agent_controller to imporve readability. 
---
- on_event: Refactored event processing by splitting it into two distinct functions: _handle_action and _handle_observation
- set_agent_state_to: Consolidated new_state checks into a single if..elif structure, replacing multiple parallel if statements
- _step: Isolated delegate step functionality and integrated traffic limit handling logic
---
> refactor the logic in agent_controller to imporve readability

- openhands/llm/llm.py
- tests/unit/test_llm.py
LLM class: add `safety_settings` for Gemini models (Google only). Improve `max_tokens` defaulting.
---
- Feature: added `safety_settings` to LLM completion for Gemini models (if hosted by Google) as described by litellm [here](https://litellm.vercel.app/docs/providers/gemini#specifying-safety-settings).
Tested with model "gemini/gemini-1.5-flash-latest" (Google as provider). This is **NOT** applied for other providers, like OpenRouter (not supported)!
Fixes #2549 
For the case there is no value provided by either config.toml or env var for `max_output_tokens` for OH:
- The new base …
> (feat) LLM class: add safety_settings for Gemini; improve max_output_tokens defaulting

- openhands/llm/llm.py
Don't send Gemini safety settings when the LLM is not Gemini
---
Tested with llama, AI studio / gemini.
> Don't send gemini settings when the llm is not gemini

- agenthub/browsing_agent/prompt.py
- openhands/controller/agent_controller.py
agent_controller: if delegate is in PAUSED state reduce logspam
---
@enyst this change is aimed to reduce logspam, similar to the fact, that the normal agent doesn't create log entries unless RUNNING.
What do you think?
Ok, also fixed 2 typos along the way.
> agent_controller: in PAUSED state reduce delegate logspam from delegate

- frontend/src/components/chat/ChatMessage.tsx
Make the timestamp less visible by moving it to the hover-hint of the copy button.
---
Followup to #3869 
First attempt to make it less obtrusive was to use it as the chat bubble's title, but that had the annoying effect of constantly showing when e.g. using the mouse to select any text.
Now it'll just be appended to the hint of the copy button and doesn't take any room away.
> ChatMessage: get timestamp out of direct view

- agenthub/codeact_agent/codeact_agent.py
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/prompt_001.log
- tests/integration/mock/eventstream_runtime/CodeActAgent/test_browse_internet/prompt_005.log
Fix content retrieval from AgentDelegateObservation in CodeActAgent
---
In `get_observation_message` the handling of an `AgentDelegateObservation` needs to retrieve the `content` attribute of obs.outputs,
which is a dict.
I wonder if we need to do similar for AgentFinishAction for delegats where a dict with e.g. `summary` is coming back etc.?
Fixes #3969 
CC @ryanhoangt
> (fix) CodeActAgent: use `content` of AgentDelegateObservation

- agenthub/codeact_agent/codeact_agent.py
- config.template.toml
- openhands/core/config.py
Just realize we have 0.5 as the default top_p value - i figure we'd better set this to a more standard default (e.g., following OpenAI's [setting](https://platform.openai.com/docs/api-reference/chat/create))?
---
Set top P and temperature to default 1.0.
---
> change top_p default value to 1.0

- openhands/runtime/plugins/agent_skills/file_ops/file_ops.py
Existing agentskills' editing store backup file in the same directory, which sometimes messes up the `git patch` produced for SWE-Bench evaluation (not in terms of accuracy, but in terms of size).
---
This PR stores those tmp file under `/tmp` instead of the same directory.
---
> Store the file edit backup file in `/tmp`

- frontend/src/components/modals/settings/ModelSelector.tsx
This PR fixes an issue where model names are cut off in the Settings UI, improving the user experience by displaying the full model name on hover. The tooltip ensures that longer model names are fully visible without affecting the layout.
---
This PR introduces a tooltip that appears when hovering over truncated model names in the autocomplete dropdown. It ensures that models with long names are not cut off, providing clarity to the user. The tooltip is added without affecting the existing UI design, maintaining consistency with the overall structure.
---
**Link of any specific issues …
> fix: models cut off in Settings UI (#3900)

- frontend/src/components/modals/settings/SettingsForm.tsx
Clear the base URL when unselecting the advanced options switch
---
**TODO**
> Enable Advanced Options
> Set Base URL
> Remove Base URL
---
Resolves #4013
> hotfix(frontend): Clear base URL when advanced options is unselected

- evaluation/utils/shared.py
- openhands/core/logger.py
- openhands/runtime/remote/runtime.py
Sometimes, if you run an evaluation using RemoteRuntime with too many processes, the LLM will throw rate limit warnings/errors, which only get logged to the file. It makes it hard to figure out whether that error is a rate-limit warning or a fatal LLM error (e.g., the LLM was down - it happened yesterday, and it took me quite some time to find out and recover the eval).
---
- When run in multi-processing, this PR log WARNING and above directly to the console, and add a prefix of `instance_id` to help figure out which instance is having an issue.
---
**Link of any specific issues this …
> [eval] log evaluating warnings directly to console

- openhands/runtime/client/runtime.py
- openhands/server/session/agent_session.py
- openhands/server/session/session.py
**Fix issue where statuses related to startup are all delivered to browser at the same time at the end of startup**
---
Each session has a thread associated with it that is used to run any operations associated with it. This PR moves all code related to startup into this thread.
> Fix startup statuses

- openhands/controller/agent_controller.py
- openhands/server/session/agent_session.py
**Fix for regression when cancelling tasks.**
---
Tasks are not cancelled using `task.cancel` - closing the runtime cancels them.
> Fix for regression

- frontend/src/components/AgentStatusBar.tsx
- frontend/src/services/actions.ts
- frontend/src/state/statusSlice.ts
- frontend/src/types/Message.tsx
- openhands/controller/agent_controller.py
- openhands/server/session/agent_session.py
- openhands/server/session/session.py
In actions.ts: restored handleAssistantMessage the order of handling messages
---
Fixes #4073 
- changed in StatusMessage in frontend the attribute "message" to "status" so that it is distinct from the other 2 types
- In `actions.ts` (frontend file) the order of statements in `handleAssistantMessage` was "restored" so
that `handleObservationMessage` comes last.
- That method is, in spite of its name - potentially acting as a "catch all", even if there's no
"observation" in it, due to its default case.  🤔 
This order was last changed in #3771 
---
**Link of any specific issues this …
> (fix) actions.ts: restored handleAssistantMessage handling order

- tests/runtime/test_bash.py
Add `test_python_version` for runtime image `bash` tests to confirm python
---
Related to #4095 - this adds a simple bash test after the issue is resolved, see result below.
---
> (enh) add test_python_version to test_bash.py runtime tests

- evaluation/utils/shared.py
Fix logging in shared eval file to prevent key disclosure
---
- Fixed in `shared.py` the logging of the metadata to happen _after_ the call to `to_safe_dict` or the API key might be disclosed
> (fix) Fix logging in shared eval file to prevent key disclosure

- openhands/runtime/remote/runtime.py
- openhands/server/session/agent_session.py
---
This provides the option, when running with the remote runtime, to specify a pre-built image rather than just a base image
---
> allow specifying exact remote image

- evaluation/utils/shared.py
EvalOutput current have required llm_completions, which will not be added in SWE-Bench's `eval_infer.py`.
---
make llm_completions optional to fix `eval_infer.py`
---
> fix: make llm_completions optional to fix `eval_infer.py`

- openhands/runtime/builder/docker.py
---
Right now, we check for image existence **without explicitly checking the tag** before build - this adds additional time for docker pull without actually helping speed up building because the pulled docker image may have a different hash.
This PR specifically check for tag in the `image_exists` check.
---
> fix(runtime build): only check for image exist on exact hash tag

- openhands/server/listen.py
** Prevent background task sleeping forever if client does not finish the websocket accept protocol **
---
Consider the following python script:
```
import websockets
async def main():
await websockets.connect("ws://localhost:3000/ws")
asyncio.run(main())
```
On our server, this will initiate a call to `websocket.accept()`, but because the protocol does not finish, the task just hangs around forever in asnycio. This is not a big deal in every day use, but:
* It could be used to clog the server with malicious requests
* If you are running a dev server and you change a file, your server will get stuck at `Waiting for background tasks to complete. (CTRL+C to force quit)`
> Fix: Add timeout on websocket accept

- docs/modules/usage/prompting-best-practices.md
- docs/sidebars.ts
Added documentation for prompting best practices.
---
---
Fixes #4181
> Fix issue #4181: 'Prompting best practices documentation'

- openhands/runtime/utils/runtime_build.py
**Better error message in Development when version number changes.**
---
Every time we release a new version and I do a `git pull` of main without an accompanying `poetry install`, I get the message:
```Source distribution not found at ...```
The message now prompts users to also run a `poetry install`.
> Fix Better error message in development when version number changes.

- evaluation/swe_bench/run_infer.py
- evaluation/utils/shared.py
Improve error handling and retry for swebench inference
---
- Add a shared method `assert_and_raise` to replace the raw `assert` statements which will cause automatic retry to fail
- Use try and finally to properly cleanup runtime when an evaluation fails in the middle
---
> eval: improve swebench infer error handling and retry

- openhands/runtime/remote/runtime.py
**RemoteRuntime now includes same startup events as event stream runtime**
---
Basicaly, I copped events from the EventStreamRuntime. Startup for the remote runtime used to look like this:
Now it looks like this:
> Feat Startup events for the remote runtime

- agenthub/browsing_agent/response_parser.py
- tests/unit/test_browsing_agent_parser.py
Fix browsing agent parsing responses.
---
This PR proposes an adjustment to browsing actions parsing.
Browsing agent responses can be a simple command or set of commands, with no "thoughts", or can contain both, with the thought first. In the first case, no actions were parsed, so its "previous actions" was empty in the prompt. This was tested first with delegation, and it just didn't work at all with several LLMs. Tested after with UI and browsing agent.
Tested with claude, got-4o, gemini. The prompt shows in the Previous Action section a list of previous actions, e.g.
Previously: 
(after several steps of the …
> Fix browsing actions to be more robust

- .github/workflows/ghcr-build.yml
Remove concurrency from ghcr-build so it always runs on main commits
---
This will make it so every commit to main will run these jobs now. Requested by @rbren 
---
> Remove concurrency from ghcr-build so it always runs on main commits

- openhands/runtime/builder/remote.py
- openhands/runtime/client/runtime.py
- openhands/runtime/remote/runtime.py
- openhands/runtime/utils/request.py
**More deliberate timeouts on retry operations**
---
Ever have something not quite work and the server sits there for 5 minutes before the logs even tell you what's wrong? There was a lot of that in my last 24 hours. This has to stop! ;)
* **Renamed the method `send_request` to `send_request_with_retry`** : This more accurately describes what it does.
* **Removed the default timeout on `send_request_with_retry`** : Each operation is different, and there is no one size fits all for these timeouts. Now developers must think about each of these operations deliberately and supply a timeout if they want to use this function
* **Reduced the limit on the exponential backoff** : Time between retries now starts at 4 seconds and maxes out at 20 seconds (Instead of 60 seconds). When something is …
> [Runtime] Audit HTTP Retry timeouts

- frontend/src/api/open-hands.ts
- frontend/src/context/socket.tsx
- frontend/src/utils/get-valid-fallback-host.ts
---
Instead of fixing the fallback to `localhost:3000`, it is dynamically determined by the current host. If the current `hostname` is `localhost`, then it will be set to `localhost:3000` since that is the default port for the server
---
> chore(frontend): Change the backend base url fallback to be dynamic to current host

- frontend/src/api/open-hands.ts
`url.searchParams.append` already escapes the relevant characters, encoding the path produced a different value than what was required
---
Removes the encoding
---
> fix(frontend): Remove unnecessary encoding in `/list-files` API endpoint path param

- docs/modules/usage/how-to/evaluation-harness.md
- evaluation/EDA/run_infer.py
- evaluation/agent_bench/run_infer.py
- evaluation/aider_bench/run_infer.py
- evaluation/biocoder/run_infer.py
- evaluation/bird/run_infer.py
- evaluation/browsing_delegation/run_infer.py
- evaluation/gaia/run_infer.py
- evaluation/gorilla/run_infer.py
- evaluation/gpqa/run_infer.py
- evaluation/humanevalfix/run_infer.py
- evaluation/logic_reasoning/run_infer.py
- evaluation/miniwob/run_infer.py
- evaluation/mint/run_infer.py
- evaluation/ml_bench/run_infer.py
- evaluation/swe_bench/eval_infer.py
- evaluation/swe_bench/run_infer.py
- evaluation/toolqa/run_infer.py
- evaluation/webarena/run_infer.py
- openhands/core/main.py
- openhands/runtime/remote/runtime.py
---
After #4223, sid will be used to reconnect to runtime, which will cause many errors for existing evals (e.g., `Invalid value: \"runtime-some_random_instance_id\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.'`). This PR remove the setting of "sid" in evaluation & change the error logging to debug level to avoid flooding the terminal.
---
> [eval] stop set sid in eval

- openhands/runtime/remote/runtime.py
no need
---
This fixes an edge case where remote runtime crashes when an env var is set hard-coding the image to use
---
> fix container_image when using hard-coded image

- openhands/llm/llm.py
Display in the logs the prompt cache hit or miss for Deepseek Chat.
---
Just a small tweak, display in the logs the cache hit/miss for Deepseek as we are doing for Anthropic.
---
> Log cache hit/miss for deepseek

- evaluation/swe_bench/scripts/eval/convert_oh_output_to_md.py
---
This PR adds a simple script that converts an `output.jsonl` into a folder of markdown files for visualization by re-using `event_from_dict` as well as `__str__` of each action/observations.
---
> [Eval] Add a more lightweight / easier-to-use SWE-Bench output visualizer

- evaluation/utils/shared.py
---
On some really rare occasions, `eval_infer_remote.sh` will get stuck (on both single process & multi-processing settings). It turns out that passing a very large string to `bar.set_postfix_str` is a source of error. This PR introduces a manual truncation of the string to avoid hanging.
---
> [Eval] Fix eval stuck when `result` is too large for pbar

- frontend/src/routes/_index/route.tsx
- frontend/src/routes/_index/task-form.tsx
Right after the user uploads a project, the app focus on the text area.
---
Create a `ref` object to use to trigger a focus event and pass it to the textarea component
---
> feat(frontend) Focus on text area input when the user uploads a project

- openhands/runtime/client/client.py
Really cool to see the remote runtime client! @xingyaoww 
Minor detail that I noticed while reading the code:
Perhaps I'm missing something, but so far, the `max_retries` loop seems to be equivalent to simply using a longer `pexpect` timeout (namely `max_retries * interrupt_timeout`): If `self.shell.expect` terminates: great, we simply return. If not, it only tries to `expect` again. And this could probably even cause a problematic scenario if the timeout occurs just while the `self.__bash_expect_regex` is printing.
I assume you meant to send multiple `Ctrl+C` instead? (that's what this PR is doing)
> Fix: _interrupt_bash to send multiple Ctrl+C

- evaluation/EDA/scripts/run_infer.sh
- evaluation/agent_bench/scripts/run_infer.sh
- evaluation/aider_bench/scripts/run_infer.sh
- evaluation/biocoder/scripts/run_infer.sh
- evaluation/bird/scripts/run_infer.sh
- evaluation/browsing_delegation/scripts/run_infer.sh
- evaluation/gaia/scripts/run_infer.sh
- evaluation/gorilla/scripts/run_infer.sh
- evaluation/gpqa/scripts/run_infer.sh
- evaluation/humanevalfix/scripts/run_infer.sh
- evaluation/logic_reasoning/scripts/run_infer.sh
- evaluation/miniwob/scripts/run_infer.sh
- evaluation/swe_bench/scripts/run_infer.sh
- evaluation/swe_bench/scripts/setup/instance_swe_entry.sh
- evaluation/toolqa/scripts/run_infer.sh
- evaluation/webarena/scripts/run_infer.sh
simplify instance_swe_entry
---
- Support running multiple runs for SWE-Bench run_infer (for pass@k).
- Simplify entry script `evaluation/swe_bench/scripts/setup/instance_swe_entry.sh` - there's a lot of code that were needed in the old architecture but no longer needed now
- Remove `--max-chars 10000000` from all evals since they are no longer used in arg parser
---
> [Eval] Improve SWE-Bench Eval harness: multi-run support & entry script simplification

- evaluation/utils/shared.py
Fix eval output path in case of @ char
---
This is causing issues because the model I'm using is `openai/claude-3-5-sonnet@20240620` and because of the `@` some systems don't accept that as a valid char in directory paths.
Tested the scenario and as long as the `@` is replaced, it works.
---
> Fix eval output path in case of @ char

- openhands/controller/agent_controller.py
- openhands/runtime/runtime.py
- openhands/security/invariant/analyzer.py
- openhands/server/listen.py
- openhands/server/session/agent_session.py
- openhands/utils/async_utils.py
- tests/unit/test_async_utils.py
**Fix lockups in SAAS environment**
---
* Renamed asynci_utils methods for clarity (Added `call` to the start)
* Added new async_utils method for calling a coroutine in a background thread (Yes - this is a bit of a hack, but some of our coroutines are misbehaving and this gives us leverage)
* Create the runtime in a background thread
> Fix for lockup - create the runtime in a background thread

- frontend/src/api/open-hands.ts
Requests were attempting to send JSON data without setting content-type, causing 422's in the server.
---
- Adds `"Content-Type": "application/json"` to the headers of requests that send JSON data
---
Resolves #4348
> fix(frontend): Fix request headers

- frontend/src/utils/get-valid-fallback-host.ts
- frontend/vite.config.ts
none needed
---
Currently the app is broken if you `docker run` on a port other than 3000
---
> fix default host

- containers/app/Dockerfile
- frontend/package.json
- frontend/vite.config.ts
- openhands/server/listen.py
The directory path of the static files served through `listen.py` is `frontend/build/client` which is different than what is used when building with Docker (`frontend/build` only)
---
- Update vite config to "unpack" the client directory
- Change previous reference to reflect this new path
---
> fix(frontend): Update build directory and referenced paths

- openhands/server/listen.py
bugfix: backend freezes when zipping a large directory
---
This turns zip-files into an async call
---
> fix freeze on zip-files endpoint

- .gitignore
Simply ignore any `node_modules` folder, not just the one in the `frontend` folder.
> .gitignore: ignore all `node_modules` folders

- openhands/runtime/client/client.py
---
Runtime API server inside sandbox sometime will throw errors when pexcept run into non-unicode. This PR applies the `codec_errors='replace'` suggestion from https://github.com/pexpect/pexpect/issues/381#issuecomment-312823577 
---
> fix(runtime): replace codec error in pexcept

- frontend/.env.sample
- frontend/global.d.ts
- frontend/public/config.json
- frontend/src/api/open-hands.ts
- frontend/src/api/open-hands.types.ts
- frontend/src/components/modals/connect-to-github-modal.tsx
- frontend/src/routes/_oh._index/route.tsx
- frontend/src/routes/_oh.tsx
---
- Move `VITE_GITHUB_CLIENT_ID` out of `.env.sample` and into `config.json` as `GITHUB_CLIENT_ID`
- Store `GITHUB_CLIENT_ID` in `window.__GITHUB_CLIENT_ID__`
- Handle `GITHUB_CLIENT_ID`-related logic with new window variable
---
> [ALL-571] chore(frontend): Move `saas`-related configs to `config.json`

- frontend/__tests__/components/file-explorer/FileExplorer.test.tsx
- frontend/src/components/file-explorer/FileExplorer.tsx
- frontend/src/components/file-explorer/TreeNode.tsx
- frontend/src/components/project-menu/ProjectMenuCard.tsx
- frontend/src/mocks/handlers.ts
- frontend/src/routes/_oh.app._index/code-editor-component.tsx
- frontend/src/routes/_oh.app._index/route.tsx
- frontend/src/routes/_oh.tsx
- frontend/src/utils/download-workspace.ts
---
FAILED FETCHING SETTINGS DATA
FAILED LISTING FILES
FAILED SAVING FILE
FAILED SELECTING FILE
This does not cover all cases. Some feel improper / risky to modify to support error handling (e.g., requests that occur in data loaders). I hope to cover these soon after setting up some tests for the relevant routes and components
The toasts are default styles, I'll talk with Paul to see what we can come up with
---
> [ALL-594] chore(frontend): Add frontend error handling for failed requests

- frontend/src/components/file-explorer/TreeNode.tsx
> [ALL-570] fix(frontend): Don't wrap filenames in the file explorer

- openhands/runtime/builder/remote.py
- openhands/runtime/utils/request.py
---
- retry on 429 error on remote build
- log HTTPS retries in remote runtime to aid the debugging process
---
> fix(remote runtime): retry on 429 error on remote build & log retries

- openhands/server/session/manager.py
**Closer adherence to best practices for understandability of code**
---
* The session manager is now a dataclass. This eliminates the need for fields as well as an init method (The init method was removed)
* Missing fields are now included (config and file_store)
* Sessions are now cached in the instance rather than globally - this is not a big deal but setting the class level variable to {} is generally considered confusing.
> Feature: Minor refactor of SessionManager to make it a dataclass

- frontend/public/config.json
- frontend/src/routes/_oh._index/route.tsx
The loader runs the same time the layout loader does, so initially the check is false even if the config returns `APP_MODE: "saas"`
---
Calls `getConfig` in the index route as well (but does not set on `window` since that is done in the layout route)
---
> fix(frontend): Fix loader checking unset config variable in window

- openhands/controller/agent_controller.py
- tests/unit/test_agent_controller.py
…l error
---
While running SWE-Bench eval, I found a few cases where FatalErrorObservation didn't really stop the agent controller (see below).
This PR:
- fixes this issue
- add a unit test to make sure this doesn't happen again
```
2024-10-25 21:10:05,132 - INFO - **CmdRunAction (source=None)**
THOUGHT: Now that we've created the script, let's run it to see if we can reproduce the error:
COMMAND:
python /workspace/django__django__3.0/reproduce_error.py
2024-10-25 21:10:22,559 - ERROR - Error during action execution: 404 Client Error: Not Found for url: …
```
> fix(controllor): make agent controller stops when encounter fatal observation

- frontend/src/context/socket.tsx
Only events received from the websocket were recorded
---
Store all events that are sent to the web socket
---
Resolves #4592
> fix(frontend): Record events sent to WS

- openhands/runtime/action_execution_server.py
---
This PR change the action execution server's behavior to only accept one request at a time for exec action requests. 
Otherwise, if there's long running bash command - it may block the action execution server from responding to other requests (e.g., `/server_info`), hence causing instability on RemoteRuntime.
---
> fix(runtime): only accept one request at a time for exec action requests

- openhands/server/listen.py
This PR implements loading the GitHub users list at startup instead of during each authentication request. This change improves the performance of the authentication process.
> Load GitHub users list at startup for improved authentication performance

- openhands/server/listen.py
- openhands/server/middleware.py
This PR includes:
- Move NoCacheMiddleware to a dedicated middleware.py module
- Create LocalhostCORSMiddleware that allows any localhost/127.0.0.1 request while maintaining standard CORS behavior for other origins
- Update listen.py to use the new middleware
The changes improve code organization and make local development easier by automatically allowing any localhost/127.0.0.1 request regardless of port.
> Refactor CORS middleware and enhance localhost handling

- openhands/runtime/builder/docker.py
Only get major, minor version of Docker version
---
Gets the major and minor version of Docker because the tuple expects 2 values (major, minor)
---
#4717
> Fix for #4717

- config.template.toml
- openhands/core/main.py
Make config.trajectories_path support file path apart from folder path
---
This is a follow-up of #4336 
The previous PR adds a config `trajectories_path`. Once configured, a {sid}.json trajectory file would be dumped to that folder once the controller finishes.
There's one thing that's missing, though: it doesn't allow users to specify the trajectory name. In my use case, I'd actually would like to use `traj_{sid}.json` format, thus this PR. If the config path is a file path, then use it; otherwise, use `{sid}.json` as filename.
---
> Make trajectories_path support file path

- frontend/src/routes/_oh.app._index/code-editor-component.tsx
- openhands/runtime/action_execution_server.py
- openhands/runtime/utils/files.py
---
I noticed #1491 has been repetitively going stale; this PR addresses this by enabling viewing of images/videos/pdfs in the workspace. Summary of changes -
1. Selects file from backend and sends base64 encoding to frontend
2. Frontend renders the editor if its text; otherwise it will render the image, pdf, or video accordingly
---
#1491
> Support displaying images/videos/pdfs in the workspace

- docs/modules/usage/llms/llms.md
- frontend/src/mocks/handlers.ws.ts
- frontend/src/services/chatService.ts
- frontend/src/types/core/actions.ts
- frontend/src/types/core/variances.ts
- openhands/agenthub/codeact_agent/codeact_agent.py
- openhands/agenthub/codeact_swe_agent/codeact_swe_agent.py
- openhands/controller/state/state.py
- openhands/events/action/message.py
- openhands/events/serialization/action.py
- openhands/events/serialization/event.py
- openhands/server/listen.py
- openhands/server/session/session.py
- tests/unit/test_action_serialization.py
- tests/unit/test_json.py
Issue #4399 
---
Replaced all occurrences of 'images_urls' to 'image_urls'
---
> Issue #4399 : Replaced all occurences

- frontend/src/routes/_oh.app._index/route.tsx
---
We checks if the selected file matches expected filetypes for assets that aren't code files. In this case we decide not to render the action buttons
---
#4899
> Fix: [Bug]  Do not render editor action buttons (save/discard) when displaying non-code files

- openhands/resolver/issue_definitions.py
- tests/unit/resolver/test_issue_handler_error_handling.py
This PR adds error handling for when referenced issues cannot be fetched from GitHub API. Changes include:
- Added try-catch block around GitHub API calls when fetching referenced issues
- Added unit tests to verify error handling behavior
- Logs warning when an issue cannot be fetched instead of crashing
This builds on top of the changes in #5059 to make issue reference handling more robust.
> Add error handling for issue references

- tests/unit/resolver/test_issue_handler_error_handling.py
Fixed failing tests in test_issue_handler_error_handling.py by:
1. Using PRHandler instead of IssueHandler since the tested method is defined in PRHandler
2. Using correct name mangling for private method access
3. Updated test cases to reflect the correct class usage
> Fix issue handler error handling tests

- openhands/resolver/send_pull_request.py
- tests/unit/resolver/test_send_pull_request.py
---
I usually develop onto my 'feature' branch, but there is no option to merge into the feature branch instead of the default branch
---
> Allow to merge to a specific target branch instead of main

- .github/workflows/openhands-resolver.yml
---
Previously the resolver would only be trigger if the comment body started with the target macro. This PR ensures that the resolver gets triggered when the target macro is present anywhere in the comment body.
---
#5184
> [Resolver] Invoking resolver when macro is present anywhere in comment body

- openhands/llm/llm.py
---
This PR is to:
- Add logging for function call in debugging mode. Currently it only logs message content.
Example output:
```
I'll help you navigate to All Hands AI's GitHub profile using the browser tool.
Function call: browser({"code": "goto('https://github.com/All-Hands-AI')"})
```
---
> Add fn call in response debug logging

- openhands/runtime/impl/runloop/runloop_runtime.py
- Update runloop runtime to generate vscode url to runtime
---
- Update runloop runtime to generate vscode url to runtime, supporting vscode button
- Append this url to token / workspace & return as property
---
> Add vscode url to runloop runtime

- openhands/core/config/app_config.py
- Use backticks for code references in docstrings
- Fix typo in "compatibility"
- Ensure docstring format follows Google style guide
---
---
> docs: align docstrings with Google style

- evaluation/benchmarks/swe_bench/eval_infer.py
- evaluation/benchmarks/swe_bench/scripts/setup/instance_swe_entry.sh
---
This PR is to replace `ln -s` with `mv` from `/testbed` to `/workspace`.
- We only need to do this in `run_infer.py` to grab the diff. In `eval_infer.py` we can still use the original `/testbed` and apply the generated patch there.
I ran on 3 instances and it seemed to work fine out of the box. CC: @xingyaoww 
---
Fix #5526
> Remove symlink use for swebench setup

- openhands/llm/metrics.py
- tests/unit/test_llm.py
---
When response latencies would be negative (possibly due to issues with system timing info), clips to 0 instead.
---
#5658
> fix: Gracefully handling negative response latencies

- .github/dependabot.yml
Extending the Dependabot workflow to update GitHub Actions as well.
---
Reference https://docs.github.com/en/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories
> Add GitHub Actions package ecosystem to Dependabot workflow

- Development.md
- Makefile
---
- Fixes `node.js` version `>=20.x` requirement in `Makefile` and `Development.md`
---
> check node.js req for 20.x or later

- openhands/agenthub/codeact_agent/function_calling.py
The function's name is `web_read`, yet the prompt misspelled it as `webpage_read`.
---
---
> web read function call: Fix typo in prompt

- openhands/llm/fn_call_converter.py
This probably doesn't bug LLMs but it bugs me who's been reading the prompt logs :)
---
Before this PR:
```
--------------------- NEW TASK DESCRIPTION ---------------------
What's 1+1?--------------------- END OF NEW TASK DESCRIPTION ---------------------
```
After this PR:
```
--------------------- NEW TASK DESCRIPTION ---------------------
What's 1+1?
--------------------- END OF NEW TASK DESCRIPTION ---------------------
```
---
> fn_call_converter: Fix newline in in-context learning prompt

- frontend/src/state/chat-slice.ts
This PR fixes #5637 with a simpler approach than PR #5644.
Instead of modifying the backend and adding extensive error detection, we simply check for errors in the content of the IPython output, which is where error messages appear.
The `message` property contains a static string, for an iPython obs; the `content` property should be filled with the actual content.
Changes:
- Modified `chat-slice.ts` to check `ipythonObs.content` instead of `ipythonObs.message` for error detection
This is a minimal change that addresses the core issue while keeping the codebase simpler.
> Fix #5637: Check for errors in IPython content instead of message

- pyproject.toml
- tests/unit/resolver/test_pr_handler_guess_success.py
This PR fixes the linting issues in PR #5950:
- Renamed `mock_llm_response` fixture to `mock_llm_success_response` to avoid redefinition
- Removed unused `mock_llm_response` function
- Fixed formatting in pyproject.toml
> Fix linting issues in PR #5950

- frontend/__tests__/components/chat/chat-input.test.tsx
- frontend/src/components/features/chat/chat-input.tsx
This PR fixes an issue where pressing Enter during IME (Input Method Editor) composition would prematurely submit the message. This was particularly problematic for users typing in Japanese and other languages that use IME for text input.
- Added a check for \`isComposing\` state in the \`handleKeyPress\` function
- Only submit messages when Enter is pressed and not during IME composition
- Added test case to verify IME composition behavior
- Added new test case `should not submit when Enter is pressed during IME composition`
- Verified that existing tests pass
- Manually tested with Japanese IME input
> fix(frontend): Prevent message submission during IME composition

- openhands/runtime/impl/runloop/runloop_runtime.py
Fix field deprecation in runloop runtime client preventing Runloop client from initializing correctly
---
Fix field deprecation in runloop runtime client preventing Runloop client from initializing correctly
`setup_commands` was deprecated in favor of the LaunchParameter `launch_command`
---
> Fix field deprecation in runloop runtime client

- frontend/__tests__/context/ws-client-provider.test.tsx
- frontend/src/context/ws-client-provider.tsx
- frontend/src/i18n/translation.json
- openhands/server/listen_socket.py
---
The changes in #6101 made `ConnectionRefusedError` thrown in `listen_socket.py` display to the client. One of those scenarios is "Settings not found". This change gives those an optional "msg_id" for the translation and adds a user facing message that makes it more clear what action to take.
Another place this could be addressed is in `frontend/src/hooks/query/use-settings.ts`, but I'm not sure how to approach that and making these Websocket errors more first-class seemed like a good direction.
---
ALL-959
> Provide a clearer error message when settings are missing midsession

- openhands/runtime/utils/runtime_templates/Dockerfile.j2
Fix NoEmptyContinuation error in custom runtime builder's template
---
When building a custom runtime image, I realize my Docker build log has this error:
> NoEmptyContinuation: Empty continuation line
Not sure if it has any observable impact but why not fix it? Thus this PR. The improper usage of jinja2 syntax led to blank lines between continuation lines, e.g.
```
RUN apt-get update && \
apt-get install -y --no-install-recommends \
wget curl sudo apt-utils git jq tmux \
libgl1-mesa-glx \
libasound2-plugins libatomic1 curl && \
apt-get clean ...
```
with this PR, it becomes:
```
RUN apt-get update && \ …
```
> Custom runtime builder: fix NoEmptyContinuation error

- openhands/runtime/impl/remote/remote_runtime.py
---
When we need to restart the runtime container, send a status update to front-end that it's starting.
Alternatively we could introduce a new "Restarting" message to be more specific. I'm open to adding that to this change, but there is also a planned followup to show a restart count so that seems like a better time to consider the interface change.
---
> Send status message on runtime restart

- openhands/events/observation/browse.py
- This PR removes an unnecessary variable (`_axtree_str`) in the `BrowserOutputObservation` class, which was not being used.
---
- Removed the unused `_axtree_str` assignment to clean up the code and improve maintainability. This change does not affect any external functionality.
---
> remove useless axtree str

- frontend/__tests__/components/features/sidebar/sidebar.test.tsx
- frontend/src/components/shared/modals/settings/settings-form.tsx
- frontend/src/context/settings-context.tsx
- openhands/server/listen_socket.py
---
The settings modal on the front-end relies on the stored settings -- since the LLM API key is set as a `SecretStr`, it is serialized as a blanked-out value `"**********"`, but the settings form was looking for the value `"SET"`.
---
> fix: Settings modal properly tracks if an API key is set

- openhands/runtime/impl/modal/modal_runtime.py
---
https://github.com/user-attachments/assets/821b76df-54e7-4867-95a1-f2ce50e9b9ff
---
> feat: vscode support for modal runtime

- openhands/runtime/impl/remote/remote_runtime.py
---
Previously, `pod_status` was passed from runtime-api. Recently, new fields were added to provide more detail: `restart_count` (number) and `restart_reasons` list of string. The out of memory scenario (Reason "OOM") is a motivation. This additional logging is intended to act gracefully when one or both of these fields is missing, although going forward they should be there.
---
> Log restart reason if runtime reports it

- openhands/runtime/base.py
- openhands/runtime/impl/action_execution/action_execution_client.py
- openhands/runtime/impl/remote/remote_runtime.py
Fix some situations where conversations could not be resumed after an agent error.
- [ x ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below
---
During interactive usage, `Runtime.close()` should only be called by the conversation manager or `Session.close()`. `<--` *That's an important point, please confirm in review*
There were some scenarios where it was called during error handling, preventing remote runtime from being resumable. This change removes those `close()` calls, because we want those errors to be recoverable when the …
> fix: Don't close runtime on error

- frontend/src/components/features/chat/chat-interface.tsx
- frontend/src/i18n/translation.json
- openhands/controller/agent_controller.py
- openhands/llm/llm.py
- openhands/llm/retry_mixin.py
- openhands/server/session/session.py
- tests/unit/test_agent_controller.py
- tests/unit/test_session.py
Show LLM retries as they happen and allow resume from Rate-Limited state
---
Currently when RateLimitError is thrown during a step, retries happen without visibility to the user and then this is shown.
This PR changes this in two ways. It passes that exception to `_react_to_exception`, which already has handling for it, triggering an Agent State of RateLimited:
Second, we want to show the user the retry loop as it occurs, so a retry_listener is added to LLM class and that is used to update the status bar.
---
> Show LLM retries and allow resume from rate-limit state

- .github/workflows/openhands-resolver.yml
Moved this to my corporate repo. Resolved the request to put the new variable in the inputs.
> LLM_API_VERSION in openhands resolver

- openhands/controller/agent_controller.py
---
Adds `AgentCondensationObservation` to the agent controller's list of filtered events. These events will still trigger a step, but now the user and LLM will not be made aware because the event is not stored in the agent's state.
---
#6634 - removes chat messages mentioned here
> fix: Filter `AgentCondensationObservation` events from agent state

- openhands/runtime/utils/runtime_templates/Dockerfile.j2
---
Poetry asks for confirmation while deleting cache without the -n flag. This is causing runtime builds to break. 
---
Fixes: #6750
Fixes: #6748
> fix: no interaction when clearing poetry cache

- openhands/runtime/action_execution_server.py
- openhands/runtime/impl/action_execution/action_execution_client.py
- openhands/server/routes/files.py
A bunch of problems with the whole download workspace:
- inside `action_execution_server` the entire zip operation (compute intensive, blocking IO), and the entire zip file was read back in memory, on the `async def ...` route handler, blocking that fastapi event loop, fix this by running that route as a sync handler, and not reading the file back in-mem, let `FileResponse` handle streaming it back out asynchronously
- in `action_execution_client` theres unnecessary looping of the content stream, just let `shutil.copyfileobj` handle streaming that raw socket out to the temp file
- in `zip_current_workspace` even though its an async handler, it immediately throws the real work onto call_sync_from_async, so might as well just run this route handler entirely on the fastAPI blocking …
> Fix download workspace zip file event loop hanging

- openhands/memory/condenser/impl/llm_summarizing_condenser.py
There's anecdotal evidence that the current summarization prompt does a poor job of summarizing user messages. This updated prompt seems to perform better (but we don't have any good benchmarks involving lots of user messages), and shows no performance degradation over SWE-bench.
---
---
> fix: LLM summarization prompt handles user messages

- openhands/core/main.py
---
This PR is to fix broken trajectory replay feature due to incorrect `task_str` argument validation.
---
> fix: `task_str` validation not required for trajectory replay

- openhands/controller/agent_controller.py
Anthropic updated the error message they send when a context window limitation has been exceeded, which broke our context window truncation. This PR adds a new case which should capture the new error message.
---
---
#7023
> Fix: Update context window exceeded detection

- openhands/core/logger.py
- poetry.lock
- pyproject.toml
- tests/unit/test_logging.py
Add the option of structured logging in JSON for better observability. You can turn this on by setting the LOG_JSON environment variable. 
---
Add an option to use LOG_JSON env var to switch the main logger to output JSON lines instead of plaintext. This will allow observability pipelines to cleanly read long errors as one event and extract `extra={...}` fields in a structured way.
This is fairly vendor agnostic. Adding the LOG_JSON_LEVEL_KEY env var to rename `level` should be enough to work in AWS, Google Cloud, Splunk and Elastic Stack.
This uses the python library …
> Structured logging mode

- frontend/src/services/observations.ts
- frontend/src/state/chat-slice.ts
- frontend/src/types/core/observations.ts
---
This PR improves the error detection logic to help reduce false positives on the UI.
Before:
After:
---
> Improve error detection for `read` and `edit` observations

- tests/unit/test_agent_session.py
This PR fixes the failing tests related to PR #6909 which refactors prompt extensions into recalled observations.
Changes made:
- Added mock_agent.prompt_manager = MagicMock() to mock_agent fixture
- Added mock_agent.config = {"disabled_microagents": []} to mock_agent fixture
- Changed assert_called_with to assert_any_call for EventStream.subscribe tests
- Updated comments in test_agent_session.py for clarity
> Fix failing tests for Memory component integration

- openhands/agenthub/codeact_agent/prompts/additional_info.j2
- openhands/runtime/base.py
- openhands/runtime/impl/daytona/daytona_runtime.py
- openhands/utils/prompt.py
Tells the agent which URLs to use when responding with links for reaching running apps on Daytona.
---
This PR adds an `additional_instructions` property to runtimes which then gets forwarded to the `PromptManager`.
For Daytona, it is used to pass this message: 
> "When showing endpoints to access applications for any port, e.g. port 3000, instead of localhost:3000, use this format: <port>.<workspace_id>.<node_domain>"
which shows the user a correct link to access the preview URL for a running application.
---
Discussed briefly in #6863
> feat: prompt instructions for runtimes

- tests/unit/test_condenser.py
Adds a simple test to confirm that, when the LLM summarizing condenser sees a smaller history than it's been tracking (likely due to the agent controller truncating the history upon seeing a context window error) that it resets its tracking.
---
---
> Adds unit test for the interaction between agent controller truncation and condenser

- Development.md
- docs/modules/usage/how-to/development-overview.md
- docs/sidebars.ts
- [x ] This change is worth documenting at https://docs.all-hands.dev/
- [ x] Include this change in the Release Notes. If checked, you **must** provide an **end-user friendly** description for your change below
This adds a Development Overview Page to the User Guide documentation. Since most of this is documented in the Git Repository and we don't want to maintain a lot of separate documentation, it acts as a guide with Reference Documents to git.
---
Primary decision was to keep the repo as the Core Developer Documentation, and treat this as a quick reference for Developers to look up specific items. Might …
> docs: Add development overview and documentation resources

- openhands/core/config/app_config.py
- openhands/runtime/impl/daytona/README.md
- openhands/runtime/impl/daytona/daytona_runtime.py
Combines some action execution server setup requests together to save time. Speeds up the initial response time when starting a conversation.
---
Handles the Daytona sandbox being in "stopping" state by waiting it to complete before starting the sandbox back up.
Handles restarting the action execution server as well when restarting the Daytona sandbox if it times out due to inactivity.
Adds a retry policy for executing actions, allowing time for the action execution server to start up after it had already been "connected" for cases where the Daytona sandbox had been stopped in the meantime.
- Temporarily …
> fix: daytona runtime action execution handling

- openhands/runtime/impl/action_execution/action_execution_client.py
`shutil.copyfileobj` on a streaming HTTP response seem to close prematurely and not grab the whole file for some reason
changing to `iter_content` chunking tested to be reliable and I verified with md5 checksums that it's correct on 0-byte file, small file and large files
> fix file chunking corruption

- docs/modules/usage/llms/google-llms.md
Updated the Google model name to Gemini 2.0 Flash (the latest release), rather than Gemini 1.5 Pro (dated release).
---
Update to the documentation.
---
> Updated to reference the new Gemini 2.0 flash model.

- evaluation/benchmarks/gaia/scripts/run_infer.sh
---
Fixed a missing fi statement in the GAIA benchmark scripts/run_infer.sh script. This syntax error would cause the script to fail execution. Adding the missing fi statement ensures proper conditional logic execution.
---
> Fix missing 'fi' statement in GAIA benchmark scripts/run_infer.sh

- openhands/agenthub/codeact_agent/tools/llm_based_edit.py
---
This PR fixes incorrect position descriptions in script comments on lines 12, 24, and 48, changing "this is the end of the file" to "this is the beginning of the file" to accurately reflect their actual positions in the file.
---
> Fix incorrect file position descriptions in script comments

- Makefile
No. Now it should just work.
For Developers: make now automatically selects npm dev_wsl in an wsl environment.
---
the make recipe *start-frontend* now detects if it is running in a wsl and then uses dev_wsl to start npm. 
---
> build(make) Automatically use dev-wsl

- Development.md
The Makefile was updated last month to require NodeJS 22.x however this was not updated to reflect the update. Doing this now.
---
Updates the required version of Nodejs in DEVELOPMENT.md to reflect what is required by Makefile.
---
> Update NodeJS Version Requirement

- docs/modules/usage/installation.mdx
N/A
---
This PR fixes a broken markdown link in the installation documentation. The link to Anthropic's billing settings page was missing a closing bracket, which caused the markdown to render incorrectly when searching for 'console.anthropic.com/settings/billing'.
Changed from:
`[Set up billing(https://console.anthropic.com/settings/billing)`
To:
`[Set up billing](https://console.anthropic.com/settings/billing)`
---
N/A
> Fix broken markdown link for Anthropic billing settings

- containers/app/Dockerfile
---
This pull request includes a small change to the `containers/app/Dockerfile` file. The change ensures that the `apt-get` package lists are cleaned up after installing the necessary packages to reduce the image size. 
* [`containers/app/Dockerfile`](diffhunk://#diff-6cc49007fe4e6fbd7d1eda5a7304a69961b59cfcc59a248890fdcf287015e5d5L51-R52): Added a command to remove `/var/lib/apt/lists/*` after installing packages to clean up package lists and reduce image size.
> Clean up apt temporary files in app Dockerfile

- openhands/storage/memory.py
---
Two tests failed on my machine, when ran from VSCode Test. 
On my windows machine, test_memory_multiple_repo_microagents would fail, if run after test_memory_repository_info. The reason was, that while each had an instance of InMemoryFileStore, they both shared the same underlying dict. 
Not sure, why this happens only on my machine, but it was consistent. 
---
> fix(unittest): Parallel Test failure because of shared memory

- .github/workflows/ghcr-build.yml
---
Currently: The runtime tests use the image built by the previous job in the workflow. On non-forks, that image is uploaded to ghcr, but on forks that can't be done so it is passed by an artifact. However, that artifact is very large and takes a significant fraction of total build time to upload and download.
This PR sends the dockerfile and source distribution as artifact and rebuilds it. The blacksmith cache should make the rebuild near instant, effectively performing the same copy more quickly.
---
> chore - Rebuild docker image in fork CI instead of using artifacts

- openhands/core/cli.py
- Folder security dialog text content not visible in terminals with white color schemes
---
- Update the folder security dialog styling to display the text content properly in terminals with white color schemes
- Remove unnecessary agent state change action event when folder security confirmation prompt is rejected by the user
---
> fix: Update folder security dialog styling

- frontend/scripts/check-unlocalized-strings.cjs
When  checking for unlocalized strings pre-commit, it is possible for tag names to be upper case, 
and/or contain attributes, so ensure that we catch those in the regexp
> fix(check-unlocalized-strings): make HTML tag test case-insens

- openhands/controller/agent_controller.py
Makes the code simpler and debuggable at no cost in performance
Maybe I am misunderstanding something, but seems like `AgentController.step` was an unnecessary and even harmful indirection. The creation of an asyncio task (instead of awaiting) means the core logic of the step was not debuggable. It drove me a bit crazy to find out why things never stopped at breakpoints. At the same time, it seems that this was pointless, since the only call of step was within `_on_event`, and the only call of that one was wrapped by `run_until_complete`, so the results of `step` were actually always "awaited" in the synchronous `AgentController.on_event`, and the indirection over the task creation had no benefits.
I may …
> Minor refactoring: remove step and task-creation in AgentController

- openhands/agenthub/codeact_agent/function_calling.py
> replace erroneous rstrip() with removesuffix()

- Makefile
- openhands/runtime/impl/local/local_runtime.py
Fixes an issue where the application, when running using the local runtime, would throw a generic exception if `tmux` is not available
---
- Add exception handling and logging to indicate `tmux` unavailability
- Add a step in Makefile to check `tmux` availability
---
> fix: Add error handling for scenarios where tmux is unavailable

- openhands/runtime/utils/bash.py
Code:
```py
import libtmux
session = libtmux.Server().new_session(session_name="my_session")
pane = session.attached_pane
```
Output: `<stdin>:1: DeprecationWarning: Session.attached_pane() is deprecated in favor of Session.active_pane()`
> chore: Use recommended functions

- openhands/runtime/utils/bash.py
---
This PR adds the missing output of the last PS1 match when combining all matches into the raw command output. This also seems to help resolve all the `test_bash_session` failures I got locally.
---
> Add missing last ps1 match output into combined output

- openhands/core/cli.py
- openhands/core/cli_commands.py
- openhands/core/cli_tui.py
- tests/unit/test_cli_commands.py
- tests/unit/test_cli_pause_resume.py
- tests/unit/test_cli_tui.py
Add support for agent pause and resume functionality in the CLI
- Pause the agent during a long-running task using Ctrl-P
- While the agent is paused, resume the agent using /resume
---
- Implement agent pause and resume in CLI by sending AgentState.PAUSED and User.MessageAction events
---
> feat: Add CLI support for agent pause and resume

- openhands/memory/conversation_memory.py
> fix(memory): Fix empty string content handling in ConversationMemory

- frontend/src/components/features/images/thumbnail.tsx
- frontend/src/components/features/images/upload-image-input.tsx
Ensure that only images are uploaded on the frontend, by filtering on MIME type
> fix(image-input): enforce image types on upload

- openhands/core/cli.py
- openhands/core/cli_tui.py
- tests/unit/test_cli_pause_resume.py
- Enable support for agent pause/resume functionality alongside confirmation mode.
- Minor styling changes for the CLI command completer and agent pause/resume messages.
---
- Refactor and enhance state handling in the CLI by leveraging local state variables alongside the agent state.
---
n/a
> refactor: Refactor pause/resume functionality and improve state handling in CLI

- openhands/agenthub/codeact_agent/codeact_agent.py
- openhands/agenthub/readonly_agent/readonly_agent.py
- openhands/controller/agent.py
- tests/unit/test_agents.py
* make prompt_manager an `@property` of base `Agent` class, which can be overridden in children
* make `response_to_actions` a proper instance method rather than an attribute
Both of these changes have the effect that `__init__` behavior should no longer need to be redefined in most child implementations, for example in `ReadOnlyAgent`.
* Override `_get_tools` and `prompt_manager` in `ReadOnlyAgent` so that it can re-use the parent class `__init__`.
> Small refactor to improve (CodeAct)Agent extensibility

- openhands/cli/tui.py
- tests/unit/test_cli_tui.py
- Improve the order in which agent output is printed in the CLI
- Rename 'session' to 'conversation' for consistent terminology
---
Adds a lock in the `display_event` function to ensure agent events are printed in the order they are received.
---
> refactor: Refactor CLI agent output display order and verbiage

- docs/sidebars.ts
---
Currently the MCP documentation is not shown in the sidebar of OH doc. This PR adds it under "Advanced Configuration":
---
> chore: add MCP doc to sidebar

- openhands/cli/main.py
- openhands/cli/tui.py
- tests/unit/test_cli_tui.py
- Introduce an `always` option for confirmation mode that, when selected, bypasses future confirmation prompts for agent actions within the current conversation.
- Minor visual and usability improvements.
---
- Implement an always option within the confirmation mode feature. If a user chooses this option, all subsequent actions initiated by the agent will be automatically confirmed for the duration of that conversation.
- Improve clarity on agent state changes by showing more messages.
- Improve the readability of `FileRead` action output by removing ^I characters.
- Enable Ctrl-C and Ctrl-D to function as agent pause …
> feature: Add CLI support for `always` confirm mode

- openhands/core/config/agent_config.py
Added support optional `extended` property to agent configuration, for implementations that require additional config not in the default schema.
For example:
```toml
[agents.CustomAgent.extended]
foo = "bar"
```
---
This is the minimal change to get some customizability in agent configuration. However, longer term I would love to have support for custom config schemas too, similar to how the `AgentConfig.condenser` supports a union of different config types for different condensers.
In particular, I would propose having the Agent class include a class-level attribute (e.g. `Agent.config_class = AgentConfig`) that can be …
> [feature] add optional extended field to agent config

- openhands/server/routes/manage_conversations.py
This small PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> Resolve warnings of logger library

- frontend/src/routes/conversation.tsx
---
In #8243, after introducing `TabContent` component, we use both it and react-router's `Outlet`, which renders two versions of the same components and causes conflicts in shared state processing.
In fact it seems we can remove the `Outlet` component without affecting the behavior of `react-router`. I tested manually and this seems to help resolve the bash commands run by the agent not shown in "Terminal" tab.
---
> fix: remove duplicate rendering of tab components

- evaluation/benchmarks/swe_bench/run_infer.py
---
This code checks if a list of selected repos is provided in the config data of swe-bench. If so, it filters the dataset to only include rows where the repo matches one of the selected repositories, logs the filtering process, and evaluate only on the filtered subset.
---
> Update run_infer.py to incorporate selection of task based on repo

- openhands/core/config/mcp_config.py
---
For SSE server configs, we allow both plain string and an object to be passed to the "sse_servers" array, but currently this only works when loading from `config.toml` because we handle both types separately in `from_toml_section`. When passing something like `"sse_servers": ["https://example-mcp-server.com/sse"]` and saving on the UI, it throws 422 error.
Instruction on the UI:
```
Example: { "sse_servers": ["https://example-mcp-server.com/sse"], "stdio_servers": [{ "name": "fetch", "command": "uvx", "args": ["mcp-server-fetch"] }] }
```
---
> fix: validation error when saving SSE MCP server url on the UI

- openhands/runtime/action_execution_server.py
- openhands/runtime/impl/action_execution/action_execution_client.py
- openhands/runtime/utils/log_capture.py
---
This PR captures and exposes partial MCP server addition failure logs when attempting to update the MCP router with the config inside the runtime.
---
Fix #8514
> Expose partial MCP server addition failure logs

- frontend/src/components/features/home/repo-selection-form.tsx
- frontend/src/components/features/home/tasks/task-suggestions.tsx
Claro! Aqui está um exemplo de texto em inglês para o Pull Request (PR):
---
**What was changed:**
* Updated the `title` prop from:
```tsx
title={taskGroup.title}
```
to:
```tsx
title={decodeURIComponent(taskGroup.title)}
```
**Why:**
* Task group titles were being passed as URL-encoded strings, causing display issues (e.g., `%20` instead of spaces).
* `decodeURIComponent` ensures the title is properly rendered for the user.
**Impact:**
* UI improvement for task group titles.
* No breaking changes expected.
---
---
> fix: url repo encode

- .devcontainer/devcontainer.json
…n issue
Fixes a networking issue in the devcontainer setup where the app failed to connect to the runtime container, resulting in connection refused errors.
---
Adds "runArgs": ["--network=host"] so the app can access the localhost-bound port exposed by the runtime container.
---
> fix(devcontainer): configure host networking to fix runtime connection

- openhands/runtime/utils/request.py
Reduces timeout errors during runtime download or git clone by increasing the default request timeout from 10s to 60s.
---
Increases the default timeout in send_request from 10 to 60 seconds.
---
> feat: increase requests timeout to 60s

- openhands/server/utils.py
This small PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
Please note that we addressed these issues previously in PR #8432, but PR #8936 introduced another instance. It would be helpful to document this tip somewhere to avoid reintroducing deprecated methods into the codebase.
> Migrate to modern logger interface in server utils

- .dockerignore
- .github/dependabot.yml
- containers/app/Dockerfile
- evaluation/benchmarks/scienceagentbench/Dockerfile
- Updated Docker base images
---
- Let Dependabot update Docker weekly
- Warning: pyproject.toml allows Python 3.13 but it wasn't possible to build containers/app on arm64
- dive: `Potential wasted space: 127 MB`
- Why are write permissions needed for 318 Python source files, 14 Markdown files and 1.5 GB .venv files?
---
> chore(docker): update docker base images

- evaluation/benchmarks/miniwob/run_infer.py
- evaluation/benchmarks/webarena/run_infer.py
Description:  
This pull request corrects a typo in the comments of two files: evaluation/benchmarks/miniwob/run_infer.py and evaluation/benchmarks/webarena/run_infer.py. The word "accurancy" has been replaced with the correct spelling "accuracy" to improve clarity and maintain code quality.
> Fix Typo: Change "accurancy" to "accuracy" in Evaluation Benchmark Comments

- .devcontainer/setup.sh
Prevents Git dubious ownership errors in containers due to ownership mismatch on mounted project folders (more likely on Windows/WSL2).
Fixes issue #5529
---
Adds the repo to git's safe.directory to avoid ownership errors in Dev Containers.
---
> fix(devcontainer): mark workspace as safe dir

- openhands/cli/commands.py
- openhands/cli/main.py
- openhands/cli/settings.py
- openhands/cli/tui.py
- openhands/core/config/__init__.py
- openhands/core/config/cli_config.py
- openhands/core/config/openhands_config.py
- tests/unit/test_cli_commands.py
- tests/unit/test_cli_tui.py
- tests/unit/test_cli_vi_mode.py
This change introduces optional vi-style keybindings for confirmation prompts navigating menus (`j` and `k`) in the command-line interface. Users can enable this feature by setting the `CLI_VI_MODE` environment variable to `true`. This provides a more familiar and efficient way for users accustomed to vi editors to interact with the CLI.
---
This PR adds unit tests for the new `vi_mode` feature. It ensures that the VI keybindings (`j` and `k`) are correctly handled in confirmation prompts. The PR also includes necessary fixes to existing tests that were broken by the new `config` object being passed to CLI functions to …
> feat(cli): Add vi mode support

- openhands/llm/llm.py
We've been seeing this error when using bedrock:
```
litellm.exceptions.ServiceUnavailableError: litellm.ServiceUnavailableError: BedrockException - {"message":"The system encountered an unexpected error during processing. Try your request again."}
```
This seems like a pretty safe things to blindly retry.
---
Adds ServiceUnavailableError to retryable errors
---
> Fix: Retry on Bedrock ServiceUnavailableError

- openhands/cli/main.py
Fixes a bug where the terminal could be left in a broken state (raw mode) after exiting the CLI, due to improperly restored terminal settings.
---
Ensures process_agent_pause is only started once, preventing multiple conflicting state snapshots and conflicting restores at shutdown.
---
> fix(cli): avoid race condition from multiple process_agent_pause tasks

- openhands/cli/main.py
- openhands/cli/tui.py
- tests/unit/test_cli_pause_resume.py
Fixes terminal input lag/loss on Windows
Fixes CPR warnings after ctrl-c
Fixes exit through ctrl-c still leaving terminal in raw mode
---
Adds start&stop functions stop the agent pause listener
Stops the agent pause listener when the agent is not in running/paused state.
Adds a finally block to ensure raw mode is always exited.
---
> fix(cli): fix terminal input lag on Windows by start&stopping pause task

- frontend/src/components/features/settings/secrets-settings/secret-list-item.tsx
**Description:**
The layout of the Secret Settings page breaks when a secret with an excessively long name is added.
---
**Steps to Reproduce:**
1. Navigate to the **Secret Settings** page.  
2. Create a new secret with a **very long name**.
---
**Current Behavior:**
- The layout of the Secret Settings page becomes distorted or broken when displaying the long secret name.
---
**Expected Behavior:**
- The layout should remain intact and responsive, regardless of the length of the secret name.
---
**Additional Information:**
- 📹 A video demonstrating the issue:  
https://github.com/user-attachments/assets/7926a4d1-e94c-46e1-bb74-f9cfd7cb0e28
---
**Summarize what the PR does, explaining any …
> fix(frontend): The secret settings layout will be broken if the secret name is too long.

- openhands/llm/llm.py
Support for gemini-2.5 with added thinking feature.
---
Added gemini-2.5-flash and gemini-2.5-pro to REASONING_EFFORT_SUPPORTED_MODELS.
LiteLLM converts OpenAI's reasoning_effort into Gemini's thinking parameter.
https://docs.litellm.ai/docs/providers/gemini#usage---thinking--reasoning_content
https://ai.google.dev/gemini-api/docs/thinking?hl=ja
---
> ADD gemini-2.5 to REASONING_EFFORT_SUPPORTED_MODELS

- frontend/__tests__/components/features/home/repo-selection-form.test.tsx
- frontend/src/components/features/home/repo-connector.tsx
- frontend/src/components/features/home/repo-selection-form.tsx
- frontend/src/components/features/home/tasks/task-suggestions.tsx
- frontend/src/routes/home.tsx
The **Suggested Tasks** section currently filters tasks based solely on the repository’s title. This causes incorrect behavior when multiple repositories share the same title but come from different Git providers—filtering becomes unreliable or incorrect in such cases.
---
- Filtering should correctly consider **both** the repository title **and** its Git provider to uniquely identify repositories.
---
- Filtering is based **only** on the repository title, leading to incorrect or ambiguous results when duplicate titles exist across providers.
---
1. Create or connect multiple repositories that share the same title but are hosted on different Git providers.
2. Open the **Suggested Tasks** section. …
> fix(frontend): The suggested tasks section only filters the tasks by the repository’s title.

- frontend/src/components/features/home/tasks/task-group.tsx
- frontend/src/components/features/home/tasks/task-item-title.tsx
Currently, the **Suggested Tasks** section displays only the repository titles. This makes it difficult to quickly identify which Git provider a repository belongs to—especially when multiple repositories share the same name but originate from different Git providers.
---
- Show Git provider **icons** alongside repository titles in the **Suggested Tasks** section.  
- This enhancement would improve scannability and user experience, allowing users to quickly differentiate between repositories.
---
- Only the repository title is shown, making it hard to distinguish between similarly named repositories from different providers.
---
1. Connect multiple repositories with the same title from different …
> refactor(frontend): Show the git providers on the suggested tasks

- frontend/src/components/features/jupyter/jupyter.tsx
When initiating a new conversation, users expect to see a loading state in the **Jupyter** tab while the agent is connecting. Currently, no such feedback is shown, which may confuse users or make the app feel unresponsive.
The **Jupyter** tab does not display the message **"Waiting for runtime to start..."** during the agent connection phase.
---
- The **Jupyter** tab should display the message:  
**"Waiting for runtime to start..."**  
when connecting to an agent.
---
- The **Jupyter** tab remains blank or static and does **not** display any loading message while waiting for the agent runtime to initialize.
---
1. Create a new conversation.
2. Navigate to the **Jupyter** tab.
3. Observe the tab …
> refactor(frontend): The Jupyter tab is not showing "Waiting for runtime to start..." when connecting to an agent

- .gitignore
- openhands/cli/settings.py
- tests/unit/test_cli_settings.py
**CLI /settings now shows the path to the configuration file.**
---
**Added the Path of 'config' object in  the corresponding 'labels_and_values' list within 'display_settings' function of  'settings.py'.
Added Test Class 'TestSettingsCommandShowsConfigFilePath'.**
---
**Link of any specific issues this addresses: **
Fix #9386
> fix (cli): issue 9386 - show settings.json path in /settings

- openhands/llm/llm.py
We were matching only on the full pinned version but some providers (like anthropic) do not offer the pinned model name.
---
Match both the pinned and unpinned claude sonnet 4 model name.
---
> Update llm constants to match on unpinned `claude-sonnet-4`

- openhands/cli/main.py
- openhands/cli/tui.py
User gets a multiple choice menu which can be navigated using the arrow keys instead of a simple prompt to which he was asked to answer with a single char 'y', 'n' or 'a'. Additionally a new option that was not previously available is provided that gives the user the possibility to give alternative instructions for the next operation the agent shall perfom instead of what the agent currently was planning.
---
Conditionally grouped 'n' and (former) 'edit' option in main.py and tui.py since the edit option did not have any difference as to how the agent was handling it compared to the 'n'. At the moment the user sees a 4th …
> feat: [CLI] 9392 cli improve confirmation ux - revisited

- frontend/__tests__/components/features/home/home-header.test.tsx
- frontend/__tests__/components/features/home/repo-connector.test.tsx
- frontend/__tests__/components/features/home/task-card.test.tsx
- frontend/__tests__/routes/home-screen.test.tsx
- frontend/__tests__/routes/llm-settings.test.tsx
- frontend/tests/repo-selection-form.test.tsx
---
`__tests__/components/features/home/home-header.test.tsx`
`__tests__/components/features/home/repo-connector.test.tsx`
`__tests__/components/features/home/task-card.test.tsx`
- included missing trailing `undefined` in createConversation args
`frontend/tests/repo-selection-form.test.tsx`
`__tests__/routes/home-screen.test.tsx`
- wrapped disabled buttons assertions in a `waitFor`
- mocked `mutate `to update `useIsCreatingConversation` immediately
`__tests__/routes/llm-settings.test.tsx`
- used awaited `findByTestId `to await async renders
---
> fix(tests): fix tests missed by failing frontend test workflow and other flaky tests

- frontend/.husky/pre-commit
Fixes the pre-commit hook failure that occurs when following the development setup instructions.
The husky pre-commit hook was calling `pre-commit` directly, but pre-commit is installed in the poetry virtual environment and not available in the system PATH. This caused commits to fail with:
```
husky - pre-commit script failed (code 127)
husky - command not found in PATH=...
```
Changed the pre-commit hook to use `poetry run pre-commit` instead of `pre-commit` directly, ensuring it runs within the correct virtual environment.
- Modified `frontend/.husky/pre-commit` line 11 to use `poetry run pre-commit`
- Verified the fix works by successfully committing changes
- Pre-commit hooks now run properly and validate code before commits
Fixes #9933
> fix: use poetry run for pre-commit in husky hook

- openhands/agenthub/codeact_agent/codeact_agent.py
---
Update the `step` method documentation in CodeActAgent to include all possible Action types that can be returned. Added 7 missing Action types to the Returns section.
**Where these Actions are introduced.**
- `CondensationAction`: Returned directly at line 184 when condenser returns a Condensation object
- `FileReadAction`, `FileEditAction`, `AgentThinkAction`, `CondensationRequestAction`, `BrowseInteractiveAction`, `MCPAction`: Generated in `function_calling.py:response_to_actions()` method (lines 168-230) and returned via `pending_actions.popleft()` at lines 167 or 207
**Why this matters.**
The previous documentation was incomplete and could mislead developers/AI about what Action types the `step` method …
> docs: update CodeAct agent step method Returns documentation

- openhands/runtime/impl/docker/docker_runtime.py
Fixes "ports are not available" error message on Windows
---
Changes default port ranges on Windows to avoid overlap with ephemeral ports (49152 - 65535)
---
Closes #9202
> fix(docker-runtime): adjust default port ranges to avoid Windows ephemeral ports

- openhands/cli/commands.py
- openhands/cli/main.py
- tests/unit/test_cli_commands.py
- tests/unit/test_cli_pause_resume.py
- tests/unit/test_exit_reason.py
Previously, users could attempt to use the `/resume` command even when the agent was not paused, which would have no effect and could be confusing. This PR adds validation to ensure `/resume` only works when the agent is actually paused, providing clear feedback when the command is used inappropriately.
---
This PR enhances the `/resume` command by adding proper state validation to prevent its use when the agent is not in a paused state.
- Add `agent_state` parameter to `handle_commands` and `handle_resume_command` functions
- Implement validation to only allow `/resume` when agent is in `PAUSED` state
- Display error …
> feat(cli): add agent state validation to /resume command

- frontend/__tests__/components/feedback-actions.test.tsx
- frontend/src/components/features/chat/chat-interface.tsx
- frontend/src/components/features/trajectory/trajectory-actions.tsx
We should remove the “Export Conversation” button located above the chat input area, as the same functionality is already available in the context menu at the top-left corner of the screen. This change will simplify the UI and reduce redundancy.
- The “Export Conversation” button above the chat input is completely removed.
- The export functionality remains accessible from the top-left context menu.
---
The PR removes export conversation button from chat input area.
---
> feat(frontend): remove export conversation button from chat input area.

- frontend/src/components/features/chat/action-suggestions.tsx
- frontend/src/components/features/suggestions/suggestion-item.tsx
When the chat interface is in full width, the suggestions are currently centered. We should update them to span the full width instead.
---
The PR make the suggestions take full-width. We can refer to the image below for more information.
---
> feat(frontend): update the action suggestions (chat interface)

- frontend/src/components/features/chat/chat-message.tsx
- UI breaks when user message contains codeblock that's too wide
---
The PR set the max width for the chat message.
We can refer to the video below for the output of the PR.
https://github.com/user-attachments/assets/de98bbf7-702f-45e0-b408-0324c01b488f
---
Resolves #10272
> fix(frontend): UI breaks when user message contains codeblock that's too wide

- frontend/src/components/features/terminal/terminal.tsx
When toggling the expand icon, the terminal disappears.
- Toggling the expand icon should correctly expand the terminal without removing it from view.
We can refer to the video below for more information.
https://github.com/user-attachments/assets/d4929280-ff9a-4720-b0ab-3dcae2bd15d2
---
The PR fixes terminal disappears after toggling expand icon.
We can refer to the video below for more information.
https://github.com/user-attachments/assets/dc51ab13-1414-401c-a841-f6697002b3d9
---
> fix(frontend): terminal disappears after toggling expand icon

- openhands/cli/settings.py
- openhands/cli/tui.py
---
1. Removes unused mouse support from the CLI to allow scrolling
2. Fixes settings autocomplete so it no longer stops at hyphens
Screenshot of the now-working autocomplete:
---
> fix(cli): remove unused mouse support and fix settings autocomplete

- frontend/src/utils/status.ts
The agent’s status message displays as `STATUS$ERROR` instead of showing a meaningful, user-friendly error message.
---
- Show a clear and descriptive error message instead of `STATUS$ERROR`.
---
- Status message is missing and appears as `STATUS$ERROR`.
---
1. Navigate to the **Conversation** page.
2. Trigger an error scenario for the agent.
3. Observe the status message displayed.
---
Refer to the image below for details:
---
The PR adds the missing status message.
---
Resolves #10348
> fix(frontend): status message missing

- frontend/src/components/common/react-select-styles.ts
- frontend/src/components/features/home/repo-selection-form.tsx
- frontend/src/i18n/translation.json
**Acceptance criteria:**
- Vertical gap is too wide.
- Dropdown input styles are inconsistent.
- Padding adjustments needed.
- Gap between icon and placeholder/text is incorrect.
- Heading capitalization should be consistent.
- Verify expected font sizes and colors.
---
The PR updates the styling for menu repository selector.
We can refer to the image below for the output of the PR.
---
> refactor(frontend): update the styling for menu repository selector.

- frontend/src/components/features/controls/git-tools-submenu.tsx
- frontend/src/components/features/controls/macros-submenu.tsx
- frontend/src/components/features/controls/tools-context-menu-icon-text.tsx
- frontend/src/components/features/controls/tools-context-menu.tsx
- frontend/src/components/features/conversation/conversation-name-context-menu-icon-text.tsx
- frontend/src/components/features/conversation/conversation-name-context-menu.tsx
- frontend/src/utils/constants.ts
- Context menu divider takes full width when it should be partial width just like the other context menus.
---
The PR improves the context menu provider.
We can refer to the video below for more information.
https://github.com/user-attachments/assets/2a16b6e6-3440-4957-b5a9-c5b56da819d0
---
> refactor(frontend): improve context menu provider.

- openhands/cli/commands.py
---
The regular `toml.dump()` automatically converts arrays of dictionaries to array-of-tables format (`[[mcp.stdio_servers]]`) instead of the required inline array format (`stdio_servers = [{...}]`). This PR uses `tomlkit` with inline tables for proper formatting of MCP config arrays.
After the fix I tested and the addition/removal seems to work as expected:
---
Fix #10173
> [CLI] Fix MCP toml formatting issue

- frontend/src/components/features/jupyter/jupyter.tsx
- frontend/src/routes/changes-tab.tsx
- frontend/src/routes/served-tab.tsx
According to the image above, we need to remove scrollbar background on all canvas screens.
**Acceptance criteria:**
- The scrollbar background should be removed on all Canvas screens.
---
The PR removes scrollbar background on all canvas screens.
> - VSCode uses its default scrollbar, which does not have a background.  
>- The scrollbars in the **App** and **Browser** tabs belong to the rendered application.  
>  Therefore, we do not need to make any changes for those tabs.
We can refer to the video below for the output of the PR.
https://github.com/user-attachments/assets/1284fd3d-e6ce-4315-a1e3-706b9f53ad8e
---
**Link …
> refactor(frontend): remove scrollbar background on all canvas screens

- frontend/src/components/common/react-select-styles.ts
According to the image above, we need to move the drop arrow to the right (repo-selection form)
- The drop arrow in the repo-selection form should be moved to the right.
---
The PR moves the drop arrow to the right (repo-selection form).
We can refer to the image below for the output of the PR.
---
> refactor(frontend): move the drop arrow to the right (repo-selection form)

- frontend/__tests__/components/features/home/repo-selection-form.test.tsx
- frontend/src/components/features/chat/git-control-bar-branch-button.tsx
- frontend/src/components/features/chat/git-control-bar-repo-button.tsx
When no repository or branch is selected, the repo and branch buttons appear misaligned/inconsistent with the current style.
We can refer to the image below for more information.
- Update the styling of the repo and branch buttons so they look consistent even when no repository or branch is selected.
---
The PR fixes the styling for the repo and branch buttons.
We can refer to the image below for more information.
---
> fix(frontend): styling for the repo and branch buttons

- frontend/__tests__/components/features/home/repo-selection-form.test.tsx
- frontend/src/components/common/react-select-styles.ts
Currently, the input text color in the repository and branch search fields is black. Update it to `#A3A3A3` so it aligns with the existing style.
We can refer to the image below for visual guidance.
The input text color should be changed from black to `#A3A3A3`.
---
The PR updates input text color in repo-selection-form.
We can refer to the image below for the output of the PR.
---
> fix(frontend): update input text color in repo-selection-form

- openhands/memory/conversation_memory.py
- tests/unit/memory/test_conversation_memory.py
---
Looking into the code, it seems the `ImageContent`s filtering in `ConversationMemory.process_events` is not needed, as we also remove them when serializing `Message` into dict. This PR:
- Keep `vision_is_active` parameter for `TextContent` adaptations
- Remove `vision_is_active` filtering for `ImageContent` (always include images)
- Let `Message` serialization handle image filtering based on `vision_enabled`
---
Fix #10632
> Remove image content filtering in ConversationMemory

- openhands/agenthub/browsing_agent/browsing_agent.py
- openhands/agenthub/codeact_agent/codeact_agent.py
- openhands/agenthub/visualbrowsing_agent/visualbrowsing_agent.py
- openhands/llm/llm.py
---
This PR adds support for passing list of Message into LLM.completion, which makes it easy for accessing the list of Message in the completion to make routing decision, if we want to make Router inherit LLM.
In the previous PR #10650 I forgot to override the existing `messages` of kwargs with the formatted one:
```py
messages: list[dict] = []
if messages_list and isinstance(messages_list[0], Message):
messages = self.format_messages_for_llm(
cast(list[Message], messages_list)
)
else:
messages = cast(list[dict[str, Any]], messages_list)
kwargs['messages'] = messages
```
I tested this locally it works normally now.
--- …
> Add support for passing list of `Message` into LLM `completion`

- openhands/agenthub/codeact_agent/function_calling.py
---
The crash occurred because some LLMs were not following the JSON schema correctly and were passing `task_list` as a list of strings instead of a list of dictionaries. This PR fixes it by adding normalization for task items that are strings and raising validation errors otherwise.
---
Fix #10584
> fix: validate `task_list` schema for task tracker

- evaluation/benchmarks/swe_bench/run_infer.py
Fixes a bug where the values selected for the [agent] and [llm] config groups were not loaded from config.toml unless the default location "./config.toml" was used, but not via `--config-file` or `--agent-config` / `--llm-config`.
---
Two things:
* pass the args.config_file into the different config loaders.
* Also add config loading for the AgentConfig, which enables e.g. choosing a file for the system prompt template.
---
> Fix swe-bench `run_infer.py` config parsing from config.toml

- openhands-cli/openhands_cli/agent_chat.py
- openhands-cli/openhands_cli/user_actions/utils.py
---
1. run `make run`
2. type `/exit` 
3. select `Yes, proceed`
4. press any arrow keys on the keyboard, they will display raw escape sequences for arrow keys (^[[A, ^[[B, ^[[C, ^[[D)
This PR 
1. standardizes the user of app exit so prompt toolkit can clean up prompt applications properly
2. even after implementing part 1 we still see arrow keys not being restored. for this reason we add `restore_tty` as a workaround to turn off application cursor keys and bracketed paste if they were left on
We should open an issue upstream with prompt toolkit to fix the improper cleanup
---
**Link of any specific issues this …
> CLI(V1): restore terminal state
