.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/technical_proposal.md
Solves https://github.com/OpenDevin/OpenDevin/issues/19
=> Add issue templates

frontend/.env, frontend/.eslintrc, frontend/.gitignore, frontend/README.md, frontend/index.html, frontend/package-lock.json, frontend/package.json, frontend/src/components/Terminal.tsx, frontend/tsconfig.json, frontend/vite-env.d.ts, frontend/vite.config.ts
Patches [old PR](https://github.com/OpenDevin/OpenDevin/pull/24#issue-2190126867) implementing minimal changes.
=> Frontend: changed build tooling from cra to vite

frontend/src/components/Terminal.tsx
Resolves https://github.com/OpenDevin/OpenDevin/issues/52
=> Bug Fix: UI layout changes as you switch between tabs

.gitignore
Add Python gitignore from https://github.com/github/gitignore/blob/main/Python.gitignore
=> Add Python gitignore

server/README.md, server/requirements.txt, server/server.py
This just creates an "agent" using a websocket echo server. The basic flow is this:
* Client connects to server
* Client sends `start` command
* Server starts up an agent inside a docker container
* Server connects to agent websocket
* Server forwards all messages between client and agent
* Client disconnects
* Server closes connections and stops the docker container
=> add websocket handshake to server

requirements.txt
=> Updated requirements.txt 

CONTRIBUTING.md, README.md
=> doc: add contribution docs

opendevin/README.md, opendevin/requirement.txt, requirements.txt
As title, add some instructions when start working on sandbox. Most instructions are the problem I meet when begenning.
=> doc(sandbox): add more instructions for starting on sandbox work

opendevin/README.md
pip install -r requirements.txt instead of pip install -r requirement.txt
=> Fix Readme file typo

opendevin/main.py
Guessing this breaks the linter... 👀
=> Fix agenthub import

opendevin/server/listen.py
This is needed to register the agents
=> Add agenthub import to listen.py

agenthub/codeact_agent/README.md, frontend/.env, frontend/.eslintrc, frontend/src/App.tsx, frontend/src/components/ChatInterface.css, frontend/src/components/ChatInterface.tsx, frontend/src/components/CodeEditor.tsx, frontend/src/components/Errors.css, frontend/src/components/Errors.tsx, frontend/src/components/Terminal.tsx, frontend/src/services/chatService.ts, frontend/src/state/chatSlice.ts, frontend/src/state/codeSlice.ts, frontend/src/state/errorsSlice.ts, frontend/src/state/socket.ts, frontend/src/state/taskSlice.ts, frontend/src/store.ts, opendevin/server/listen.py, opendevin/server/session.py
This PR wires up the frontend to the working backend for an end-to-end OpenDevin.
[Screencast from 03-24-2024 08:39:30 PM.webm](https://github.com/OpenDevin/OpenDevin/assets/46636043/8f9ee289-6299-4b4c-8aba-8c82bb0363e3)
=> Wire up frontend

README.md
In response to https://github.com/OpenDevin/OpenDevin/issues/155
=> Add requirements to readme

dev_config/python/.pre-commit-config.yaml
`storage/` was deleted from CI but not pre-commit
=> updated pre-commit so it works

agenthub/README.md
Resolves https://github.com/OpenDevin/OpenDevin/issues/152
=> Update AgentHub README for the New Agent Abstraction

agenthub/langchains_agent/__init__.py, opendevin/controller/__init__.py, opendevin/server/session.py
Also adds some better error handling
=> fix bad observation check

frontend/src/components/ChatInterface.tsx
Removed attach button as described in #183
=> fix(frontend): Removed attach button

README.md
Implemented here: https://github.com/OpenDevin/OpenDevin/blob/main/opendevin/llm/llm.py#L5
=> Fix env vars in README

opendevin/controller/__init__.py
Ran into an issue where the LLM tries to read a non-existent file
=> add error handling for action running

agenthub/langchains_agent/utils/prompts.py
Fixes two issues mentioned in https://github.com/OpenDevin/OpenDevin/issues/166
=> Fix summaries

opendevin/action/fileop.py, opendevin/observation.py
Noticed that the base dir was getting included in the logs a bunch, and confusing the LLM
=> fix file write observations

opendevin/sandbox/sandbox.py
```Go
type StdType byte
const (
// Stdin represents standard input stream type.
Stdin StdType = iota
// Stdout represents standard output stream type.
Stdout
// Stderr represents standard error steam type.
Stderr
// Systemerr represents errors originating from the system that make it
// into the multiplexed stream.
Systemerr
stdWriterPrefixLen = 8
// ...
)
```
So the response from docker exec will return 8 bytes(1sign3zero4msglen) in the prefix to indicate the std type and the message length. like this:
```bash
"\x01\x00\x00\x00\x00\x00\x00'hello.py\nhello_world.py\nhello_world.sh\n"
"\x02\x00\x00\x00\x00\x00\x00\x19This is an error message\n"
```
references:
[https://github.com/moby/moby/blob/8b79278316b532d396048bc8c2fa015a85d53a53/pkg/stdcopy/stdcopy.go#L14](https://github.com/moby/moby …
=> fix: delete the docker exec output prefix(8 bytes).

frontend/package-lock.json, frontend/package.json
Upon trying to commit get error:
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
❯ package.json — 1 file
❯ src/**/*.ts* — 1 file
✖ eslint --fix [FAILED]
◼ prettier --write
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...
✖ eslint --fix:
Oops! Something went wrong! :(
ESLint: 8.57.0
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".
(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/home/anon/OpenDevin/frontend".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
npm install @typescript-eslint/eslint-plugin@latest --save-dev
Installed eslint to fix error
=> fix: Add eslint to package.json

frontend/src/App.css, frontend/src/App.tsx, frontend/src/components/Browser.css, frontend/src/components/Browser.tsx, frontend/src/components/ChatInterface.css, frontend/src/components/ChatInterface.tsx, frontend/src/components/CodeEditor.tsx, frontend/src/components/Planner.tsx, frontend/src/components/Terminal.tsx
This issue fixes #186 .
Changed the layout of all tabs as well
=> Fixed terminal padding in addition to UI enhancement

README.md, opendevin/README.md
As shown in #261, I find many beginners will miss the docker image details. So add some instructions for it.
=> docs: add docker image docs

frontend/src/App.tsx, frontend/src/components/BannerSettings.css, frontend/src/components/BannerSettings.tsx, frontend/src/services/settingsService.ts, opendevin/server/session.py
Implementation to resolve https://github.com/OpenDevin/OpenDevin/issues/208, hardcoding model strings and agent names
=> Add model and agent options in frontend

frontend/tailwind.config.js
We will want to support light mode later, but for now this fixes https://github.com/OpenDevin/OpenDevin/issues/307
=> Force dark mode

frontend/README.md
Frontend readme updated - for terminal section
=> doc (frontend) : Update README.md

frontend/src/components/ChatInterface.css
=> feat: pref message send box style

opendevin/controller/agent_controller.py, opendevin/controller/command_manager.py, opendevin/server/session.py
=> feat(server): Make sandbox_image configurable via the initialize event 

frontend/src/components/BannerSettings.tsx, frontend/src/services/settingsService.ts, opendevin/agent.py, opendevin/server/listen.py
Instead of hard coding the list of agents on front end, this change focuses on getting the list of availble agents from the backend making it more dynamic and focuses on resolving the bug raise in https://github.com/OpenDevin/OpenDevin/issues/398
=> feat(frontend): adding functinality to get agents from backend server

agenthub/README.md
=> Fix Agent README.md

CONTRIBUTING.md
Fix wrong link in `CONTRIBUTING.md` file where the link to server is given wrongly.
=> doc: fix wrong link to server in contributing.md

agenthub/langchains_agent/utils/monologue.py
Quick fix for https://github.com/OpenDevin/OpenDevin/issues/420
=> Remove unexpected backticks from the LLM

CONTRIBUTING.md
Added mock server to "How to begin" section
=> doc: add mock server to list in CONTRIBUTING.md

opendevin/server/session.py
https://github.com/OpenDevin/OpenDevin/issues/445 reports a hard crash here. I haven't tried to repro the original issue, but we should definitely not throw an exception here.
=> Send error response instead of crashing

.github/workflows/ghcr.yml, evaluation/SWE-bench/Makefile, opendevin/sandbox/Makefile
=> ci: check if the image exists in ghcr.io to avoid repeat building and pushing

frontend/src/components/ChatInterface.tsx
fix https://github.com/OpenDevin/OpenDevin/issues/460
Before:
After:
=> fix: fix chat bubble width

frontend/src/components/ChatInterface.tsx
https://github.com/OpenDevin/OpenDevin/assets/5690524/cd2e636a-4060-4ea5-84ee-f3cb7d3740e1
=> feat: make input for message autoresize

Pipfile, agenthub/langchains_agent/utils/json.py
Left:  repaired Json
Right: original Json
This is a potential fix for #420 #421 #430
Tested an seems to work.
=> Automatic repair of json for langchains agent

frontend/package-lock.json, frontend/src/services/settingsService.ts, frontend/src/socket/socket.ts, frontend/vite.config.ts, opendevin/mock/listen.py
fix https://github.com/OpenDevin/OpenDevin/issues/441
`VITE_WS_URL` and `VITE_API_URL` is not necessary now
- `http://localhost:3001/api`(frontend) -> `http://localhost:3000/`(backend)
- `ws://localhost:3001/ws`(frontend) -> `ws://localhost:3000/ws`(backend)
=> Fix API with vite proxy

evaluation/regression/conftest.py, evaluation/regression/run_tests.py, opendevin/plan.py, opendevin/server/session.py
Added documentation to the code in Googles Style Guide.
=> doc - Added code documentation for clarity

Pipfile
This PR addresses issue #520 by adding numpy to the Pipfile dependencies.
=> Add numpy as a dependency

Makefile
This adds a host command to the makefile to allow the backend to accept local traffic from the frontend.
Fixes https://github.com/OpenDevin/OpenDevin/issues/508
=> Add a host command to the makefile

README.md
=> fix: badges need to be centered

frontend/vite.config.ts
Fix https://github.com/OpenDevin/OpenDevin/issues/508
=> fix: use 127.0.0.1 for api proxy

opendevin/server/session.py
Proposed in #449, support setting `max_iterations` when init.
=> feat(session): add max_iterations setting in initialization

opendevin/sandbox/sandbox.py
=> fix(sandbox): fix sandbox utf-8 encode error

evaluation/regression/run_tests.py
When checking the regression test logic, find the code for getting input looks obscure. Do little refactor.
=> refactor(regression test): refactor the parameters input code

frontend/.eslintrc, frontend/src/components/SettingModal.tsx, frontend/src/services/settingsService.ts, frontend/src/socket/socket.ts, frontend/src/state/settingsSlice.ts, frontend/src/store.ts, opendevin/server/session.py
Fixes https://github.com/OpenDevin/OpenDevin/issues/500.
Incidentally fixes https://github.com/OpenDevin/OpenDevin/issues/418. Since we now wait for the `initialize` event to initialize, the GET requests for `/litellm-models` and `/litellm-agents` go through immediately.
=> fix: apply settings without explicit change

Makefile
=> fix: make run conditional logs removal

README.md
The table of contents in README.md appears to be outdated and the in-page navigation is also broken.
In this PR I updated the table of contents to match the latest updates of the README.md contents and fixed the in-page navigation links.
=> chore: update and fix broken links in table of contents in README.md

frontend/src/components/Workspace.tsx
Fixing problem with unnecessary re-rendering of components
=> Fix terminal output disappears after switching tabs

Pipfile, Pipfile.lock, Pipfile.torchidx
Fixes https://github.com/OpenDevin/OpenDevin/issues/624
=> Add playwright to pipenv

.github/workflows/run-tests.yml
=> Stubborn pipenv

frontend/.eslintrc, frontend/src/components/SettingModal.tsx, frontend/src/services/settingsService.ts, frontend/src/socket/socket.ts, frontend/src/state/settingsSlice.ts, opendevin/mock/listen.py, opendevin/server/listen.py
Fixes https://github.com/OpenDevin/OpenDevin/issues/617 (parent https://github.com/OpenDevin/OpenDevin/issues/603)
Settings will only be saved to localStorage when the settings are explicitly changed by the user. Otherwise, the initialization arguments are left blank to respect the server's defaults.
=> Send initialization arguments only when stored in localStorage

opendevin/config.py, opendevin/controller/agent_controller.py, opendevin/main.py, opendevin/server/session.py
Add max_iterations to the config. https://github.com/OpenDevin/OpenDevin/issues/664
=> Make max_iterations configurable

frontend/src/components/ChatInterface.tsx, frontend/src/hooks/useTypingEffect.ts, frontend/src/services/chatService.ts, frontend/src/state/chatSlice.ts
highlight active assistant text and maintain chat seq
[new typing seq.webm](https://github.com/OpenDevin/OpenDevin/assets/97225946/8ed6ffb7-5986-443e-b9e2-48013216f007)
for #476 
This PR instead of #531
=> fix frontend : highlight active assistant text and maintain chat seq | for  #476

opendevin/llm/llm.py
=> clean up debugging comments

README.md
This was mentioned in several discussions (example: #728) and experienced this myself, would be very helpful to provide this in the docs to pre-empt this. Not sure if there's a code based way to solve this, since it's a config in advanced settings of docker desktop.
=> docs: Updating readme with common MacOS docker issues #1

opendevin/server/listen.py
#591 #649 #259 multi issues discuss this problem, i just merged the `model_list` and `model_cost.keys()`(community-maintained) to solve this problem for now.
=> fix: add the community-maintained model list

tests/test_action_serialization.py
Seeing if this format is acceptable
If this is mergable, I'll do observation_serialization too :D
=> Added tests for other action subclasses in test_action_serialization

frontend/src/App.tsx
fix https://github.com/OpenDevin/OpenDevin/issues/758
=> fix: fix chat overflow

frontend/src/components/CodeEditor.tsx
Translating 2 comments to english, leaving the original comments in place for referencing purposes of the original author
=> chore: adding english translations to comments

frontend/src/components/SettingModal.tsx
we only support the selectable items right now. but we need to support the user inputting the model like this:
=> fix: enable custom model.

agenthub/codeact_agent/codeact_agent.py
=> Remove seed=42 to fix #813

Makefile
=> Fix awk error for the WSL users

.github/workflows/build_run-tests.yml, Makefile, poetry.lock, pyproject.toml
This PR try to build make the github action build and run tests check all the possible platforms (macos, linux) and python version that we support (3.11, 3.12)
=> add github action for project build on macos and linux

frontend/src/components/ChatInterface.tsx, frontend/src/hooks/useTypingEffect.ts, frontend/src/services/chatService.ts, frontend/src/state/chatSlice.ts
fix #768 
[chat_typing_new.webm](https://github.com/OpenDevin/OpenDevin/assets/97225946/47fec4df-6bc2-4db9-987e-f6f399d9d42b)
=> fix frontend: chat ui | for #768

opendevin/logging.py
=> quick fix default

opendevin/controller/command_executor.py, opendevin/controller/command_manager.py, opendevin/sandbox/sandbox.py
In preparation for creating alternatives to Docker based sandbox for command executions.
Some alternatives in-flight are:
* E2B https://github.com/OpenDevin/OpenDevin/pull/727
* Local Filesystem https://github.com/OpenDevin/OpenDevin/issues/110#issuecomment-2041177406
See also: https://github.com/OpenDevin/OpenDevin/pull/727#pullrequestreview-1983821196
=> Create a CommandExecutor abstract class

agenthub/monologue_agent/utils/json.py, agenthub/monologue_agent/utils/prompts.py
This extracts out the cleanup logic so it's more consistent
Fixes https://github.com/OpenDevin/OpenDevin/issues/718
=> fix up json parsing in MonologueAgent

README.md
Just to make it clear, for some beginners
=> Add installation warning to readme

frontend/src/App.tsx, frontend/src/components/AgentStatusBar.tsx, frontend/src/components/ChatInterface.tsx, frontend/src/components/SettingModal.tsx, frontend/src/i18n/index.ts, frontend/src/services/actions.ts, frontend/src/services/settingsService.ts, frontend/src/services/socket.ts, frontend/src/state/chatSlice.ts, frontend/src/state/settingsSlice.ts, frontend/src/types/ConfigType.tsx, frontend/src/utils/storage.tsx
=> feat: add agent status bar.

frontend/src/i18n/index.ts, frontend/src/i18n/translation.json
add support for 繁體中文 and adjust the translation for "agent" from "代理" to "智能体"
=> i18n : Add zh-TW 繁體中文

README.md
Fixes https://github.com/OpenDevin/OpenDevin/issues/622
Fixes https://github.com/OpenDevin/OpenDevin/issues/628
=> Add caveats and warnings to readme

frontend/src/App.tsx, frontend/src/components/Resizable.tsx
https://github.com/OpenDevin/OpenDevin/assets/5690524/b7d5d6e4-ffb7-48e0-8c6c-210f4a1b8d87
=> feat: make panes resizable

agenthub/monologue_agent/utils/json.py, agenthub/monologue_agent/utils/monologue.py
Small refactoring as follow-up to json cleaning: 
- move another function that was guarding responses from "bad" json.
Once moved, it seems to me that it is redundant? I think its intention was start/end json, and the { } is better.
=> More json cleaning

opendevin/logger.py
=> make mypy happy

.github/workflows/lint.yml, opendevin/controller/agent_controller.py, opendevin/llm/llm.py, opendevin/logger.py, opendevin/plan.py, opendevin/sandbox/sandbox.py, opendevin/server/agent/manager.py, opendevin/server/auth/auth.py, opendevin/server/session/msg_stack.py, opendevin/server/session/session.py
When I run main right now, I get this error:
```bash
✖ poetry run python opendevin/main.py -d ./workspace/ -t "write a bash script that prints hi"
Traceback (most recent call last):
File "/home/rbren/git/opendevin/opendevin/main.py", line 1, in <module>
import asyncio
File "/home/rbren/.asdf/installs/python/3.12.2/lib/python3.12/asyncio/__init__.py", line 8, in <module>
from .base_events import *
File "/home/rbren/.asdf/installs/python/3.12.2/lib/python3.12/asyncio/base_events.py", line 18, in <module>
import concurrent.futures
File "/home/rbren/.asdf/installs/python/3.12.2/lib/python3.12/concurrent/futures/__init__.py", line 8, in <module>
from concurrent.futures._base import (FIRST_COMPLETED,
File "/home/rbren/.asdf/installs/python/3.12.2/lib/python3.12/concurrent/futures/_base.py", …
```
=> Fix logger import

frontend/src/components/ChatInterface.tsx
=> fix: make chat colors match figma

opendevin/controller/agent_controller.py
Fixes https://github.com/OpenDevin/OpenDevin/issues/1000
=> Fix `raise` condition for loop errors

frontend/src/state/settingsSlice.ts
for  lint-frontend
Unexpected console statement
=> lint-frontend settingsSlice.ts

frontend/src/components/ChatInterface.tsx, frontend/src/components/CodeEditor.tsx, frontend/src/components/Files.tsx, frontend/src/components/Input.tsx, frontend/src/components/Terminal.tsx, frontend/src/components/Workspace.tsx
fix https://github.com/OpenDevin/OpenDevin/issues/914
=> fix: fix some of the styling to more closely match figma

frontend/src/i18n/index.ts, frontend/src/i18n/translation.json
Add Italian, Spanish and Português
=> Add Italian, Spanish and Português

README.md, docs/documentation/AZURE_LLM_GUIDE.md
=> Add Azure configuration doc

docs/documentation/AZURE_LLM_GUIDE.md
=> Formatting Azure LLM Guide

opendevin/sandbox/ssh_box.py
fix https://github.com/OpenDevin/OpenDevin/issues/1050#issuecomment-2051696107
=> fix: print the wrong ssh port number

frontend/src/components/CodeEditor.tsx, frontend/src/components/Files.tsx, frontend/src/components/IconButton.tsx, frontend/src/components/Workspace.tsx, frontend/src/index.css
In this PR, I have addressed some of the feedbacks provided by @openartist in the previous discussion [thread](https://github.com/OpenDevin/OpenDevin/pull/826#issuecomment-2043546011). The key changes include:
- Updated the sidebar design to match the latest [sidebar ui](https://www.figma.com/file/iM5UBG1lnpg2sgE3cFnF1P/OpenDevin?type=design&node-id=7595%3A36144&mode=design&t=IkaOirz618UGlKcU-1) & improved the overall layout and visual consistency of the sidebar.
- Changed the font to SF Pro, providing a more modern and readable typography.
- Made minor adjustments to the color palette ensured that the colors used are in line with the brand guidelines.
- Refactored the codebase to improve readability and maintainability.
https://github.com/OpenDevin/OpenDevin/assets/23031065/02629679-b5c9- …
=> style (editor): ui enhancements and code refactor

opendevin/controller/command_manager.py
Fix https://github.com/OpenDevin/OpenDevin/issues/1082
=> Throw error if an illegal sandbox type is used

opendevin/sandbox/exec_box.py
=> Added to sudo group

opendevin/sandbox/sandbox.py
Added docstring to BackgroundCommand in opendevin/sandbox/sandbox.py
closes #1083
=> refactor: Added docstrings to BackgroundCommand(#1083)

frontend/src/i18n/index.ts, frontend/src/i18n/translation.json
=> Adding: Turkish language

.github/workflows/dogfood.yml
I've added an OpenAI API key to this env--this should let us start experimenting
For now I'll have to approve any workflows here--not sure where it will wait for me, but we'll find out.
=> Set environment for dogfood action

.github/ISSUE_TEMPLATE/question.md
=> feat: add `question.md` template for community Q&A

frontend/src/components/Files.tsx
for lint-frontend exhaustive deps
=> lint-frontend  Files.tsx

Makefile
=> Add build-frontend to build

Makefile, config.toml.template
fix https://github.com/OpenDevin/OpenDevin/issues/1136
=> build: fix workspace variable name in dev setup

opendevin/sandbox/ssh_box.py
Solves #1156 
Thanks to @souravzzz for the suggestion in https://github.com/OpenDevin/OpenDevin/issues/1068#issuecomment-2053736909
=> Corrected SSH port

Development.md
Document LLM prompt and response logging.
=> Document LLM logs

README.md
Pretty sure `latest` will point to people's feature branches sometimes 😅
=> Set default tag to `main`

opendevin/logger.py
=> Logging: Less Verbose in agent controller

opendevin/server/listen.py
Thanks for @Umpire2018 's suggestion, cc @rbren , modify the response format to the same like 
```
return JSONResponse(
status_code=status.HTTP_200_OK,
content=models,
)
return JSONResponse(
status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
content={'error': error_msg},
)
```
previous pr: https://github.com/OpenDevin/OpenDevin/pull/1158
=> modify all api response to the same format (JSONResponse with status_code and content set)

opendevin/server/listen.py
fix https://github.com/OpenDevin/OpenDevin/issues/1194
=> fix: fix path traversal vulnerability

README.md
`main` is pretty unstable right now--noticing a few bugs
=> Specify version 0.3.1 in the readme

opendevin/server/agent/agent.py
Currently model and agent aren't getting reset--this was due to a merge conflict
=> fix initialize events

opendevin/action/fileop.py
An observation made after FileRead action was constructed with the full path.
=> Path in observation

frontend/src/components/AgentControlBar.tsx, frontend/src/components/AgentStatusBar.tsx, frontend/src/components/ChatInterface.tsx
=> feat: align status bar with control bar

opendevin/action/fileop.py
Fixes https://github.com/OpenDevin/OpenDevin/issues/1239
=> fix manager ref

docs/guides/LocalLLMs.md
Fixes https://github.com/OpenDevin/OpenDevin/issues/1202
=> Fix local LLM guide

frontend/src/components/Workspace.tsx, frontend/src/state/browserSlice.ts, frontend/src/state/codeSlice.ts
fix https://github.com/OpenDevin/OpenDevin/issues/1230
=> feat: add change indicator to workspace tabs

docs/guides/LocalLLMs.md
=> fix: correct port number in `LocalLLMs.md`

frontend/src/components/ChatInterface.tsx
Implement this comment: https://github.com/OpenDevin/OpenDevin/pull/1235#issuecomment-2068164191
=> style: flip controls and status message for chat

Development.md
=> Note on model name

frontend/src/App.tsx, frontend/src/components/AgentControlBar.tsx, frontend/src/components/ChatInterface.tsx
=> refactor: move leftnav and agent controls to new play bar

docs/guides/GoogleLLMs.md
Added documentation for using both AI Studio gemini, as well as Vertex AI (GCP).
=> Add docs for using Google LLMs

.github/workflows/ghcr.yml, containers/app/Dockerfile
For NPM patch: https://github.com/npm/cli/issues/7231#issuecomment-2062032218
For Disk space issue: https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
=> Applied npm patch for build errors

agenthub/monologue_agent/utils/prompts.py, opendevin/controller/agent_controller.py
Catch and send JSON parsing exceptions back to the LLM
=> Send JSON parsing exceptions to LLM

agenthub/micro/postgres_agent/prompt.md, agenthub/micro/verifier/prompt.md
I missed a couple comments on the original PR...fixing here
=> fix up microagent prompts

docs/guides/AzureLLMs.md
Add note about saving the actual model in the UI.
=> Doc: update Azure guide with setting model in the UI

frontend/package-lock.json, frontend/package.json, frontend/src/components/ChatInterface.tsx, frontend/tailwind.config.js
Resolves https://github.com/OpenDevin/OpenDevin/issues/1378
By default, Tailwind strips list discs and other styling. The `prose` class from `@tailwindcss/typography` handles this.
=> Render messages in markdown

Makefile
Inform the user when they set the model that they need to set it in the UI.
=> message in setup-config about model

opendevin/sandbox/docker/local_box.py
Allow interaction with a local box by running `python3 opendevin/sandbox/docker/local_box.py` for ease of local box development (e.g., https://github.com/OpenDevin/OpenDevin/issues/1428).
=> Allow interaction with local box

Makefile
Fixes https://github.com/OpenDevin/OpenDevin/issues/1435
=> Add playwright install to makefile

agenthub/monologue_agent/agent.py
Monologue agent forgot its initial thoughts after reset(), this PR lets it re-learn them.
=> Re-initialize monologue agent after reset

.github/workflows/run-unit-tests.yml, Makefile
close #1088 
Thanks to @foragerr
=> feat(makefile): add capability to skip Docker image pull

.github/workflows/run-unit-tests.yml, Makefile
Reverts OpenDevin/OpenDevin#1463
Unit tests appear to be broken unfortunately, not sure what went wrong
=> Revert "feat(makefile): add capability to skip Docker image pull"

README.md, docs/docusaurus.config.ts, docs/modules/usage/about.md, docs/modules/usage/intro.mdx, docs/src/pages/faq.tsx, tests/unit/test_action_github.py
Working on new Discord link...
=> Update social links

frontend/src/services/settings.ts, opendevin/core/config.py
Need to get this in ahead of updating the docs about 0.5.0
=> default to codeact agent

opendevin/core/config.py, opendevin/core/schema/config.py, opendevin/llm/llm.py
Fix #963 and allow top-p arg additionally
=> feat: ability to configure temperature and top-p sampling

Makefile, frontend/.husky/pre-commit, frontend/package.json, frontend/src/components/modals/settings/SettingsModal.test.tsx
=> Add frontend tests to pre-commit and Makefile.

containers/app/Dockerfile, containers/app/entrypoint.sh
Fixes https://github.com/OpenDevin/OpenDevin/issues/1582
=> be more dynamic around uid generation

docs/modules/usage/llms/localLLMs.md
This pull request addresses the issue #1591.
=> Add to Local LLM README.md -e SANDBOX_USER_ID=$(id -u)

README.md, docs/modules/usage/intro.mdx, docs/modules/usage/llms/localLLMs.md, docs/modules/usage/troubleshooting/troubleshooting.md, docs/src/components/Code/Code.tsx
fix #1603
Reference:
https://docs.docker.com/reference/cli/docker/container/run/#add-host
=> Fix: Compatible with older docker version for --add-host

opendevin/events/action/files.py
fix: check (and create if necessary) dir before write file
=> fix: check (and create if necessary) dir before write file

poetry.lock, pyproject.toml
solving https://github.com/OpenDevin/OpenDevin/issues/1618
=> fix: Add dependency boto3 to solve issues#1618

poetry.lock
Updated poetry.lock to download newer versions of dependencies
=> refactor: Updated poetry.lock

frontend/src/components/chat/ChatInput.test.tsx, frontend/src/components/file-explorer/FileExplorer.test.tsx, frontend/src/components/modals/settings/SettingsModal.test.tsx, frontend/vitest.setup.ts
Refactor test files and setup test file to run test without throwing any errors, allowing for clearer visuals and more robust tests.
=> (fix|test)(frontend): fix warnings during test runs

docs/modules/usage/intro.mdx
user will get error if this value is not provided
=> add sandbox_user_id to run command which is neccesary

agenthub/codeact_agent/codeact_agent.py
=> Fix typo in codeact_agent.py

frontend/src/components/Jupyter.tsx, frontend/src/hooks/useScrollToBottom.ts, frontend/src/i18n/translation.json
@amanape @Sparkier 
I have written a react hook to support stopping automatic scrolling to bottom and displaying a "To Bottom" button. It is currently effective in Jupyter. Please take a look at it. If everything is fine, I will apply it to the chat UI. 😁
=> feat: support for stopping automatic scrolling to bottom and add "to bottom" button

opendevin/runtime/docker/exec_box.py, opendevin/runtime/docker/local_box.py, opendevin/runtime/docker/ssh_box.py, opendevin/runtime/e2b/sandbox.py, opendevin/runtime/sandbox.py, tests/unit/test_sandbox.py
Fixes https://github.com/OpenDevin/OpenDevin/issues/1648
=> Allow setting env vars inside sandboxes

agenthub/micro/_instructions/actions/message.md, agenthub/micro/_instructions/actions/think.md, agenthub/micro/coder/prompt.md, agenthub/micro/postgres_agent/prompt.md, agenthub/micro/repo_explorer/prompt.md, agenthub/micro/study_repo_for_task/prompt.md, agenthub/micro/typo_fixer_agent/prompt.md, agenthub/micro/verifier/prompt.md, agenthub/planner_agent/prompt.py, frontend/src/services/planService.ts, opendevin/core/schema/action.py
Fix this bug:
@rbren pls review this pr, thanks.
=> fix: AgentThinkAction deleted caused bug.

opendevin/core/config.py
Noticed USE_HOST_NETWORK suddenly set to true in my env, tracked it down to this
=> cast bools better in config.py

opendevin/controller/agent_controller.py
After add the Microagents and Delegation https://github.com/OpenDevin/OpenDevin/pull/1238 ，the _is_stuck won't be used to check if the micro agent is stuck.
This pr will solve the problem.
replace this pr: https://github.com/OpenDevin/OpenDevin/pull/1596, it's closed since too many conflicts to resolve...  
@rbren pls review.
=> feat: new delegate stuck check.

opendevin/runtime/plugins/mixin.py
Plugins output are clustering the logs
https://github.com/OpenDevin/OpenDevin/issues/1649#issuecomment-2104637116
=> Removed logging output of plugin installation

opendevin/llm/llm.py, opendevin/server/listen.py
Still pydantic warnings arises https://github.com/OpenDevin/OpenDevin/issues/1682#issuecomment-2103914521
Workaround from https://github.com/plasma-umass/ChatDBG/pull/38/commits
=> Ignore any warnings LiteLLM might emit on import

opendevin/runtime/plugins/mixin.py
Should fix https://github.com/OpenDevin/OpenDevin/issues/1700
=> fix: do not raise error when failed to delete ~/.bashrc

agenthub/monologue_agent/utils/memory.py
Fixes https://github.com/OpenDevin/OpenDevin/issues/1654
=> Disable ChromaDB telemetry

opendevin/core/config.py
=> Fixed bool config having int value

poetry.lock
Can't believe new dependency versions are coming out this fast.
=> Updated poetry.lock again

tests/unit/test_sandbox.py
Looks like auto-merge didn't respect the sandbox tests--working on fixing that
=> Fix the tests

tests/integration/mock/CodeActAgent/test_ipython/prompt_002.log, tests/integration/mock/CodeActAgent/test_ipython/response_001.log, tests/integration/mock/CodeActAgent/test_ipython/response_002.log, tests/integration/regenerate.sh, tests/integration/test_agent.py
Follow-up of #1728, which passed all tests, but then failed on main after merge. Also fixed a few small things.
=> Fix test_ipython

docs/modules/usage/about.md, docs/modules/usage/intro.mdx, docs/modules/usage/llms/llms.md, docs/modules/usage/llms/localLLMs.md, docs/modules/usage/troubleshooting/windows.md
Made some small fixes to the documentation and removed extra words.
=> doc: Small fixes to documentation

docs/modules/usage/agents.md
https://arxiv.org/abs/2402.13463 is RefuteBench: Evaluating Refuting Instruction-Following for Large Language Models
https://arxiv.org/abs/2402.01030 is Executable Code Actions Elicit Better LLM Agents
=> Fix CodeAct paper link

opendevin/runtime/server/files.py
Fixes https://github.com/OpenDevin/OpenDevin/issues/1476
=> change error message to something more descriptive

.github/ISSUE_TEMPLATE/bug_template.yml, opendevin/core/logger.py
The logs will be stored in the 'logs/llm/default' folder. For each run, the folder will be emptied.
=> Enabled LLM logs by default

agenthub/dummy_agent/agent.py
As titled.
For better e2e integration tests
=> add BrowseInteractiveAction in dummy agent

containers/sandbox/Dockerfile
Fix https://github.com/OpenDevin/OpenDevin/issues/1857
=> Add iproute2 to sandbox

frontend/package.json, frontend/src/components/AgentStatusBar.tsx, frontend/src/i18n/translation.json
1. fix a word typo
2. refactor agent status component
3. add i18n support
4. modify start command: add `npm run make-i18n` before run `vite`
=> refactor agent status component and add i18n support

opendevin/server/session/msg_stack.py
Reverts OpenDevin/OpenDevin#1812
#1820 is the correct PR
Solves #1851
=> Revert "Fix/attribute error"

containers/app/entrypoint.sh
=> Checked for enduser in Docker

opendevin/core/main.py
Fix logging of full llm_config (leaks api key)
Fixes #1936
=> fix logging of full llm_config (leaks api key)

README.md
Our most recent results on swe-bench lite are 25%, so this updates the README accordingly.
=> Update README.md SWE-bench score

Development.md
As title, find many contributors blocked by our poetry, add some doc.
=> doc: update documentation about poetry update

tests/unit/README.md
=> doc: add more cmd in unit test documentation

Makefile
This addresses #879 #1569 and others
=> build: Add poetry command to use Python 3.11 for environment setup

opendevin/core/utils/json.py, tests/integration/mock/CodeActAgent/test_ipython/prompt_001.log, tests/integration/mock/CodeActAgent/test_ipython/prompt_002.log, tests/integration/mock/CodeActAgent/test_ipython_module/prompt_001.log, tests/integration/mock/CodeActAgent/test_ipython_module/prompt_002.log, tests/integration/mock/CodeActAgent/test_ipython_module/prompt_003.log, tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_001.log, tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_002.log, tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_003.log, tests/integration/mock/MonologueAgent/test_write_simple_script/prompt_001.log, tests/integration/mock/MonologueAgent/test_write_simple_script/prompt_002.log, tests/integration/mock/MonologueAgent/test_write_simple_script/prompt_003.log, tests/integration/mock/MonologueAgent/test_write_simple_script/prompt_004.log, tests/unit/test_json.py
We removed `to_dict` a few PRs back, which broke our custom `dumps`
=> fix json encoding

docs/modules/usage/intro.mdx
=> Added links in docs

opendevin/runtime/plugins/agent_skills/agentskills.py
The multi-modal tools introduced in https://github.com/OpenDevin/OpenDevin/pull/2016 requires the user to set `SANDBOX_ENV_OPENAI_API_KEY` to expose multi-modal tool that requires access to OpenAI API. This creates an environment variable inside sandbox named `OPENAI_API_KEY` for the functions to involve the use of tools like `parse_images` that require calling to OpenAI API.
This, in the long run, will be replaced by refactoring it into a new architecture:
> I think these tools are primarily needed for GAIA (https://github.com/OpenDevin/OpenDevin/pull/1911) to perform well as proposed in https://github.com/OpenDevin/OpenDevin/pull/1914
> In the default case, we should just disable these tools for the agent, and only enable them for evals now. In the case for GAIA evaluation, we can just …
=> Make sure the `OPENAI_API_KEY` is detected by `agentskills`

opendevin/runtime/docker/ssh_box.py, poetry.lock, pyproject.toml
=> feat: use retry decorator instead of retrying in a loop

frontend/package-lock.json, frontend/package.json, frontend/src/index.tsx
This PR addresses #2055 by adding React Router while maintaining the existing UI as the main index screen.
=> feat(frontend): Added React Router

opendevin/runtime/docker/ssh_box.py
put `create_ssh` and `ssh_login` into ONE function for retry.
Otherwise, when `create_ssh` is successful and first attempt of `ssh_login` failed, it is possible for this issue to come up https://github.com/pexpect/pexpect/issues/271, since we are calling `.login` on the same `pxssh.pxssh` instance twice, which is not supported
=> refractor ssh login into one function

opendevin/server/listen.py
=> Fix: serve UI from fastAPI app

opendevin/llm/llm.py
=> Parsed model_name for model_info

README.md, docs/modules/usage/intro.mdx
* Remove old `-e LLM_API_KEY`
* Move warning
* Make ssh pwd a one-liner
=> Adjust docs a bit

opendevin/controller/agent_controller.py
=> style: Update agent_controller.py to clean log

Makefile
=> Fixed makefile

opendevin/runtime/docker/ssh_box.py
This is a partial revert of #1998
Fixes #2165, #2157
=> Fix ssh box hung issue

opendevin/runtime/docker/ssh_box.py
Helps to debug quicker in https://github.com/OpenDevin/OpenDevin/issues/2165#issuecomment-2143292242
=> Detailed logs for ssh_box

opendevin/runtime/server/runtime.py
Fix https://github.com/OpenDevin/OpenDevin/pull/2117/files#r1617737723
=> Fix: Avoid bash backtick eval in runtime commands.

README.md, docs/modules/usage/about.md, docs/modules/usage/intro.mdx, docs/src/components/CustomFooter.tsx, docs/src/pages/faq.tsx
The slack link had expired, this PR updates it to be valid.
=> Update slack invite link to make it valid

opendevin/runtime/docker/ssh_box.py
Need to keep track of users if not restricted.
=> Restricted persistent sandbox to opendevin user only

evaluation/README.md
(AgentBench, BIRD, LogicReasoning)
=> Add supported benchmarks to evaluation README

evaluation/EDA/game.py, evaluation/EDA/run_infer.py, evaluation/EDA/scripts/run_infer.sh
Minor fix. The eval harness can be tested following [here](https://github.com/OpenDevin/OpenDevin/blob/main/evaluation/EDA/README.md)
=> [Eval, EDA] modify the exiting logic and reward calculation, delete unused function

evaluation/EDA/run_infer.py, evaluation/agent_bench/run_infer.py, evaluation/bird/run_infer.py, evaluation/gaia/run_infer.py, evaluation/humanevalfix/run_infer.py, evaluation/logic_reasoning/run_infer.py, evaluation/mint/run_infer.py
This PR is to add cost metrics to evaluation outputs for all benchmarks.
=> Add cost metrics to evaluation outputs for all benchmarks

README.md, docs/modules/usage/intro.mdx
0.6 is the latest version, so this updates the docs to 0.6.
=> Bump docs to 0.6

frontend/src/i18n/translation.json
Updated existing and added several German translations.
=> fix: German translations added/updated

README.md, docs/modules/usage/intro.mdx
Currently, it generates a random name.
Helps #2200
=> Named docker app container

.github/workflows/review-pr.yml
Post at here #2211, it seems we have not run `dogfood` action for a log time. And the github action become out of date. 
This PR fix the python environment problem. 
But it seem we still meet network problem when call openai api. Next to fix it in future PR.
See example [here](https://github.com/OpenDevin/OpenDevin/actions/runs/9355360905/job/25750320534?pr=2237)
=> fix: fix dogfood action

docs/modules/usage/intro.mdx
https://github.com/OpenDevin/OpenDevin/pull/2189#discussion_r1625437201
=> Quick doc fix 

evaluation/agent_bench/helper.py, evaluation/agent_bench/run_infer.py
=> fix: add an early exit check for agent answers in agent bench.

evaluation/swe_bench/swe_env_box.py
Helps https://github.com/OpenDevin/OpenDevin/issues/2165#issuecomment-2149291436
=> Improved logs

containers/app/entrypoint.sh
=> Solved Hugging Face cache issue.

agenthub/README.md
=> Update AgentHub README.md

.gitignore, agenthub/browsing_agent/browsing_agent.py, frontend/src/components/file-explorer/FileExplorer.tsx, opendevin/runtime/plugins/agent_skills/agentskills.py, tests/integration/mock/BrowsingAgent/test_browse_internet/prompt_001.log, tests/integration/mock/CodeActAgent/test_browse_internet/prompt_003.log, tests/integration/mock/CodeActAgent/test_browse_internet/prompt_004.log, tests/unit/test_agent_skill.py
For tracking down an issue where backticks get escaped in file operations, I've added a test for `_print_window` method and one more multiline edit_file test, both containing especially backticks.
More tests to come in separate PR for `run_ipython` in a new test file when I have the time.
The .gitignore change was only to add ".cursorignore" and moving some entries to better fitting sections instead of just added to end of file.
Example log for the backticks issue (note in the middle the IPythonRunCellObservation where backticks are escaped now):
```bash
16:33:13 - opendevin:INFO: agent_controller.py:278 - CodeActAgent LEVEL 0 STEP 8
16:33:29 - opendevin:WARNING: llm.py:294 - Cost calculation not supported for this model.
16:33:29 - opendevin:INFO: llm.py:229 - Cost: 0.00 USD | …
```
=> tests: more Agentskills tests; updated .gitignore

frontend/src/components/chat/ChatInterface.tsx, frontend/src/components/modals/base-modal/BaseModal.tsx
Fixes https://github.com/OpenDevin/OpenDevin/issues/2236
=> fix: remove bottom chatbox fade (frontend)

tests/integration/conftest.py
Reported by https://github.com/OpenDevin/OpenDevin/pull/1943#issuecomment-2156532627
The issue is, when we call `sys.exit(1)`, pytest will print out all local variables, which might include our LLM key. The solution is to not print out any variables when exiting.
=> conftest: Exit without revealing secrets

evaluation/EDA/run_infer.py
The `openai_api_key` leaks in metadata.
=> Fix llm key leaks bug

evaluation/swe_bench/README.md, evaluation/swe_bench/run_infer.py
1. Set `max_budget_per_task = 4` for inference
2. save inference log to `infer_logs` to avoid conflict with https://github.com/OpenDevin/OpenDevin/pull/2085
=> Minor SWE-Bench inference config tweak

frontend/src/components/modals/settings/SettingsModal.test.tsx
=> fix the failed unit test.

agenthub/monologue_agent/agent.py, agenthub/monologue_agent/response_parser.py, agenthub/monologue_agent/utils/prompts.py, agenthub/planner_agent/agent.py, agenthub/planner_agent/prompt.py
=> Refactor MonologueAgent, PlannerAgent add response parser 

README.md, docs/modules/usage/intro.mdx, frontend/src/i18n/translation.json
Fixes https://github.com/OpenDevin/OpenDevin/issues/2408
In this issue, it became clear that our doc incorrectly referred to OPENDEVIN_WORKSPACE when it should be WORKSPACE_BASE.
The code in this PR was written by OpenDevin
=> Replace all instances of OPENDEVIN_WORKSPACE with WORKSPACE_BASE

opendevin/controller/agent_controller.py, tests/unit/test_is_stuck.py
This PR proposes to adjust the check for identical (action, obs) down from 4 of them (current behavior) to 3 of them, before it stops.
Backported from https://github.com/OpenDevin/OpenDevin/pull/2355
I'm seeing reports that it's hard to get 4 (identical) steps, where the loop stops, but the agent is obviously stuck and will stop, just later than it feels like it could have. I think we can stop it at 3 steps. We used to do that (sort of) and it has worked in the past, it's probably not easy to do by accident.
Example issue that takes too long:
https://github.com/OpenDevin/OpenDevin/issues/2238
=> Adjust is-stuck check for the same steps to 3 until it's stopped

agenthub/delegator_agent/agent.py, agenthub/dummy_agent/agent.py
The previous description is false, change it.
=> chores: fix DelegatorAgent description

opendevin/runtime/docker/ssh_box.py
Required for smooth integration of #2413
=> Stopped persisted container on closing to prevent port issues.

.github/pull_request_template.md.
This pull request adds a Pull Request Template to standardize the format for future PRs. The template includes sections for description, and related issues, aiming to ensure all necessary information is provided consistently. This will help streamline the review process and improve documentation quality.
=> Added Pull Request Template

CONTRIBUTING.md, Development.md
This doesn't exactly resolve this https://github.com/OpenDevin/OpenDevin/issues/2386 as described, however, it does resolve the main issue which is informing the user of each document. I first tried to merge them but it didn't look good TBH.
Notable Changes:
* Updated both Development.md and CONTRIBUTING.md beginning sentences to make user aware that each doc exists
* Formatting and consistency changes for both documents
* Some additional changes in Development.md regarding configuration variable precedence
=> docs: Update Development and CONTRIBUTING docs

opendevin/runtime/docker/exec_box.py, opendevin/runtime/docker/ssh_box.py
Find a FIXME, remove useless code.
=> chores: remove useless code

opendevin/core/config.py, opendevin/core/logger.py, tests/unit/test_config.py, tests/unit/test_logging.py
The logger shall mask sensitive configuration data. This PR adds to the existing masking.
If I put some keywords in the wrong place, please let me know. @enyst 
This is a followup to PR https://github.com/OpenDevin/OpenDevin/pull/1943
Additional masking of sensitive data applied, incl. unit test update.
=> fix: logger with more masking of sensitive data

tests/integration/mock/CodeActAgent/test_ipython/prompt_001.log, tests/integration/mock/CodeActAgent/test_ipython/prompt_002.log, tests/integration/mock/CodeActSWEAgent/test_ipython/prompt_001.log, tests/integration/mock/CodeActSWEAgent/test_ipython/prompt_002.log, tests/integration/test_agent.py
Fixes: https://github.com/OpenDevin/OpenDevin/issues/2474
The integration test `test_ipython` was wrongly skipped due to wrong logical operator in test setup.
=> fix: test_ipython being skipped

opendevin/runtime/docker/ssh_box.py
Due to this line `https://github.com/OpenDevin/OpenDevin/issues/897` in the logs, the  https://github.com/OpenDevin/OpenDevin/issues/897 issue is getting polluted with mentioned messages.
=> Reworded port forward msg

README.md, docs/modules/usage/intro.mdx
=> Bump docker version

containers/sandbox/Dockerfile
#2101 
As previous PR mentioned, I plan to use global bashrc file to replace ~/.bashrc, it will help me to reduce the intrusiveness of opendevin on the sandbox environment, and better accommodate both the root and opendevin users. For specific details, please refer to the discussion in #2101.
=> feat: add environments in global bashrc file

evaluation/swe_bench/README.md
=> Update SWE-Bench README.md

.github/workflows/ghcr.yml, containers/build.sh
Build is broken on main branch due to tags in upper case: https://github.com/OpenDevin/OpenDevin/actions/runs/9569731256/job/26384552101
This was introduced by #2456
=> Fix Docker tagging issue with upper case

frontend/package.json, frontend/vite.config.ts
[To enable hot reload.](https://stackoverflow.com/questions/70996320/enable-hot-reload-for-vite-react-project-instead-of-page-reload)
[Docs](https://vitejs.dev/config/server-options#server-watch)
=> Add dev config for frontend for WSL

opendevin/controller/agent_controller.py
=> Show relevant error in UI

CONTRIBUTING.md
Just some formatting on the CONTRIBUTING.md
It does not fix any open issues
=> docs: Fix formatting in CONTRIBUTING

evaluation/swe_bench/README.md
=> Polish the visualization guidance

evaluation/swe_bench/README.md
=> docs: Add visualizer instruction for SWE-Bench

.github/workflows/run-unit-tests.yml
https://github.com/abiosoft/colima/issues/913#issuecomment-2022638213
[Failed action](https://github.com/OpenDevin/OpenDevin/actions/runs/9598922020/job/26471463040?pr=2532)
=> Fix Mac OS CI test

opendevin/runtime/docker/image_agnostic_util.py
Fix https://opendevin.slack.com/archives/C078L0FUGUX/p1718898950148509?thread_ts=1718893390.852169&cid=C078L0FUGUX
=> Fix od_sandbox's docker image rename rule

opendevin/runtime/docker/ssh_box.py
Pull always  for smoother integration
=> Always pull sandbox image

evaluation/TUTORIAL.md, evaluation/agent_bench/README.md, evaluation/miniwob/README.md, evaluation/swe_bench/README.md, evaluation/swe_bench/scripts/docker/Dockerfile.builder, evaluation/webarena/README.md, opendevin/runtime/docker/image_agnostic_util.py, tests/unit/test_image_agnostic_util.py
[The misunderstood Docker tag: latest](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375)
https://github.com/OpenDevin/OpenDevin/issues/2436
=> Use :main instead of :latest

.github/workflows/run-unit-tests.yml
[Action link](https://github.com/OpenDevin/OpenDevin/actions/runs/9607736887/job/26499400916?pr=2539)
Enabled `--network-address` and used the development version of Colima
[docker not listening on port on OSX - colima](https://stackoverflow.com/a/72810370)
https://github.com/abiosoft/colima/issues/458#issuecomment-2171006045
=> Fix Mac OS CI - usernet unable to resolve IP for SSH forwarding

.github/workflows/run-unit-tests.yml
https://github.com/OpenDevin/OpenDevin/pull/2556#issuecomment-2182396017
Need to unlink colima for installing dev version.
=> Fix Mac CI Test

frontend/src/i18n/translation.json
Resolves #2429 
Updates the feedback modal content to adhere to GDPR requirements 
> [...] the request for consent shall be presented in a manner which is clearly distinguishable from the other matters, in an intelligible and easily accessible form, using clear and plain language.
Updates the modal content
See the relevant GDPR article [here](https://gdpr-info.eu/art-7-gdpr/)
=> Update feedback modal content

Development.md
https://github.com/OpenDevin/OpenDevin/issues/1977#issuecomment-2183960361
=> Mention Ubuntu supported versions

docs/modules/usage/feedback.md
This PR attempts to better document the data usage and privacy around submitting feedback. Specifically, it explains:
1. Who is collecting and storing data
2. How we plan to release it
3. How people can request their data to be removed after they submit feedback
Discussion is welcome!
**Other References**
Part of: https://github.com/OpenDevin/OpenDevin/issues/2429
=> Update documentation regarding feedback data usage

frontend/src/components/chat/ChatInterface.tsx, frontend/src/components/modals/feedback/FeedbackModal.tsx
Resolves #2581 
Prevents the feedback action buttons from hiding when the modal opens
=> fix(frontend): Prevent actions from disappearing before sending data

frontend/src/components/modals/settings/SettingsModal.tsx, frontend/src/services/session.ts
Replaces `console.error` with `toast.error`. Also removes lint warning (`Unexpected console statement`)
=> fix(frontend): Replace console errors with toast errors

evaluation/swe_bench/scripts/eval/update_output_with_eval.py, evaluation/swe_bench/scripts/eval_infer.sh
Add a `report` field to `output.jsonl` for SWE-Bench output after running `eval_infer.sh` to ease of analyses.
=> [Evaluation] Update SWE-bench output with eval results

docs/modules/usage/custom_sandbox_guide.md
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?** 
This provides documentation in the form of a markdown file which explains how to create and run a custom docker sandbox for OpenDevin. 
The pull request simply adds one single markdown file. 
n/a
=> Added Documentation for How To Run Custom Sandbox Image 

docs/modules/usage/custom_sandbox_guide.md
Applying suggested changes in https://github.com/OpenDevin/OpenDevin/pull/2637
=> docs: Update custom_sandbox_guide.md

docs/docusaurus.config.ts, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/troubleshooting/troubleshooting.md, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/troubleshooting/troubleshooting.md, docs/modules/usage/troubleshooting/troubleshooting.md
Using "docs.all-hands.dev" to replace the docs domain "https://opendevin.github.io/OpenDevin/" to make it easier to remember.
=> Update docusaurus.config.ts for a changed Doc URL

evaluation/swe_bench/scripts/setup/process_output_json_file.py, opendevin/controller/agent_controller.py
Removed redundant `str()` conversion in f-string.
https://github.com/OpenDevin/OpenDevin/pull/2516#discussion_r1645827295
=> refactor: Simplify message formatting

README.md, docs/modules/usage/intro.mdx
Version 0.7.0 has been released. Update tag to use in README and docs to 0.7
=> Update tag to use in README and docs to 0.7.0

docs/modules/usage/about.md, docs/modules/usage/agents.md, docs/modules/usage/architecture.mdx, docs/modules/usage/custom_sandbox_guide.md, docs/modules/usage/llms/llms.md, docs/modules/usage/troubleshooting/troubleshooting.md, docs/modules/usage/troubleshooting/windows.md
No it doesn't resolve any open issues. This is for consistency.
* Remove unnecessary words and sections
* Update troubleshooting docs for better readability 
=> docs: Update documentation with some consistency

opendevin/core/logger.py, opendevin/runtime/plugins/mixin.py
Small followup to https://github.com/OpenDevin/OpenDevin/pull/2244:
Simplify line handling which covers all platform line endings.
In addition, since line endings are removed, it'll add a space between lines instead
in order to avoid words running into each other.
=> mixin: improve logging

docs/i18n/fr/code.json, docs/i18n/fr/docusaurus-plugin-content-docs/current/python/sidebar.json, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md, docs/i18n/zh-Hans/code.json, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md, docs/modules/usage/custom_sandbox_guide.md
- fix incorrect format in sidebar.json
- add custom_sandbox_guide.md to other language folders
In the previous version, switching to other languages, such as Simplified Chinese, resulted in an untranslated homepage. This PR addresses and resolves that issue.
- Before
- After
> Powered by Qwen-2 to complete the translation work.
=> fix(docs): translate missing parts in `zh-Hans` and `fr`

config.template.toml
=> feature: Add config template.

frontend/src/components/file-explorer/FileExplorer.test.tsx
=> Fix the FE failed unit test.

docs/modules/usage/architecture.mdx, opendevin/README.md
=> chore: Add architecture diagram.

README.md, docs/modules/usage/intro.mdx, pyproject.toml
No it does not fix any issues.
Updated the README getting started.
Update pyproject to 0.7.1
=> Update README for release 0.7.1

evaluation/EDA/run_infer.py, evaluation/agent_bench/run_infer.py, evaluation/biocoder/run_infer.py, evaluation/bird/run_infer.py, evaluation/gaia/run_infer.py, evaluation/gorilla/run_infer.py, evaluation/gpqa/run_infer.py, evaluation/humanevalfix/run_infer.py, evaluation/logic_reasoning/run_infer.py, evaluation/miniwob/run_infer.py, evaluation/mint/run_infer.py, evaluation/ml_bench/run_infer.py, evaluation/swe_bench/run_infer.py, evaluation/toolqa/run_infer.py, evaluation/utils/shared.py, evaluation/webarena/run_infer.py
Follow up of https://github.com/OpenDevin/OpenDevin/pull/2775 and https://github.com/OpenDevin/OpenDevin/pull/2805.
1. Pass the entire `config` to `metadata`, instead of llm config
2. Set `max_iterations` to global `config` (I've found a bug on previous `main` branch code due to this)
3. Standardize that the `agent` should be created inside `process_instance` function, so that we can avoid the `ERROR:root:<class 'AttributeError'>: Can't pickle local object 'LLM.__init__.<locals>.wrapper'` occurred in https://github.com/OpenDevin/OpenDevin/pull/2805 when trying to run eval in multi-processing. …
=> [Evaluation] Simplify eval & and multi-processing related fixes

docs/modules/usage/custom_sandbox_guide.md
Current custom image docs is outdated. Need to update.
Update the docs.
=> Update custom sandbox usage guide

.github/ISSUE_TEMPLATE/bug_template.yml
Helps to quickly solve issues like #2825
=> doc: Mention negative feedback feature in bug report.

evaluation/EDA/run_infer.py, evaluation/agent_bench/run_infer.py, evaluation/biocoder/run_infer.py, evaluation/bird/run_infer.py, evaluation/gaia/run_infer.py, evaluation/gorilla/run_infer.py, evaluation/gpqa/run_infer.py, evaluation/humanevalfix/run_infer.py, evaluation/logic_reasoning/run_infer.py, evaluation/miniwob/run_infer.py, evaluation/mint/run_infer.py, evaluation/ml_bench/run_infer.py, evaluation/swe_bench/run_infer.py, evaluation/toolqa/run_infer.py, evaluation/webarena/run_infer.py
It seems that https://github.com/OpenDevin/OpenDevin/pull/2810 might have introduced two errors into swe-bench eval that cause it not to run. This PR aims to fix these.
=> Two fixes to swe bench eval

.github/workflows/dummy-agent-test.yml
Fixes #2618
Checked for exit code
=> CI: Check exit code for E2E test

opendevin/controller/state/task.py
=> Bugfix: add missing f in f-string for logging debug message in task creation

README.md, docs/modules/usage/about.md, docs/modules/usage/architecture.mdx, docs/modules/usage/custom_sandbox_guide.md, docs/modules/usage/feedback.md, docs/modules/usage/troubleshooting/troubleshooting.md
The update to the README fixes this issue: https://github.com/OpenDevin/OpenDevin/issues/2729
The rest of the changes are to the documentation which is mostly reordering the sidebar based on importance.
=> docs: Reorder docs and small update to README

opendevin/runtime/client/client.py, opendevin/runtime/client/runtime.py
Forget to open the websocket, open port 8080 here. Fix some chores.
=> chores: open the websockets ports for port mapping and remove chores.

opendevin/runtime/utils/image_agnostic.py
remove Miniforge after installation, otherwise it's left in the workspace, consuming space + introducing weird problems
=> Fix instance agonistic: remove Miniforge after installation

docs/modules/usage/llms/azureLLMs.md, docs/modules/usage/llms/localLLMs.md
https://github.com/OpenDevin/OpenDevin/issues/2866#issuecomment-2223132367
=> Doc: Fix Azure Guide

frontend/src/components/VolumeIcon.tsx
- Restore the last mute setting
- Delete the cookie correctly by setting expire time in the past.
=> Ref: Restore last mute setting

docs/modules/usage/llms/localLLMs.md
Resolves #419, Resolves #2415 
Model TheBloke\phi-2-GGUF\phi-2.Q4_K_S.gguf
=> Doc: LM Studio Guide

opendevin/server/session/agent.py
Bug fix for #2756, discovered by @mamoodi [here](https://opendevin.slack.com/archives/C078L0FUGUX/p1720799535109299?thread_ts=1720798810.563929&cid=C078L0FUGUX)
The issue is, when `config.toml` is absent, the backend purely relies on the configurations set by user via web GUI. This works, but the config isn't passed to delegates. The consequence is delegation no longer works due to missing API key. This PR fixes this bug.
Demo (I don't have config.yaml):
=> Fix delegator LLM config when config is set from UI

opendevin/runtime/docker/ssh_box.py
Added the info from #2159. SSH problems occur in docker too #2911
=> Fix: hostname in logging

CODE_OF_CONDUCT.md, README.md, docs/modules/usage/changelog.md, pyproject.toml
=> chore: Release 0.8.0

.github/pull_request_template.md
- Reworded brief to succinct
- Added HR for visual separation
[Can I say "a short summary" or just "summary"?](https://ell.stackexchange.com/a/154479)
=> chore: Update wordings in pull request template

Makefile
After #2641, these lines are redundant.
=> Ref: Remove make-i18n from makefile

Development.md
This PR changes the directions in development.md to run all tests.
Note that I opted to explicitly specify `test_*.py` instead of doing test discovery so it's obvious that you can also specify specific files.
=> Run all tests in development.md

opendevin/core/config.py, tests/unit/test_sandbox.py
Hit some issue with global var in `test_sandbox` in https://github.com/OpenDevin/OpenDevin/pull/2933
---
- Remove the use of global variable in `test_sandbox`
- Fix an undefined variable
---
=> Refactor: remove the use of global variable in test_sandbox

docs/modules/usage/openshift-example.md
docs-issue-#2887: Create openshift-example.md
docs-issue-#2887: Create openshift-example.md
---
Create openshift example documentation
---
=> docs-issue-#2887: Create openshift-example.md

.github/workflows/run-unit-tests.yml
Solves #2992 
Applied the [suggestion ](https://github.com/OpenDevin/OpenDevin/pull/2989#discussion_r1682736087) from @tobitege
=> Fix: Run Unit Test

config.template.toml, evaluation/TUTORIAL.md, evaluation/agent_bench/README.md, evaluation/biocoder/biocoder_env_box.py, evaluation/bird/README.md, evaluation/gpqa/README.md, evaluation/humanevalfix/README.md, evaluation/logic_reasoning/README.md, evaluation/ml_bench/README.md, evaluation/swe_bench/README.md, opendevin/core/config.py, opendevin/runtime/client/client.py, opendevin/runtime/client/runtime.py, opendevin/runtime/docker/ssh_box.py, opendevin/runtime/server/runtime.py, opendevin/runtime/utils/runtime_build.py, tests/unit/test_ipython.py, tests/unit/test_runtime.py, tests/unit/test_sandbox.py
Fix https://github.com/OpenDevin/OpenDevin/issues/2992.
---
- Move `use_host_network` to `SandboxConfig` so it is easier to support in the new Runtime & adjust documentations accordingly
- Add support for `EventStreamRuntime` to run without `use_host_network`
- Add instruction for running `use_host_network` on Mac OS: You need to upgrade to the latest docker desktop and enable that feature manually - https://docs.docker.com/network/drivers/host/#docker-desktop
- Make `test_runtime.py` tests running without `use_host_network` to avoid issues.
---
=> fix: runtime test for mac

frontend/src/components/modals/feedback/FeedbackModal.tsx
We updated the visualization website (well, opendevin itself partially did it) - see demo here: https://www.all-hands.dev/share-opendevin?share_id=d3cb93a06ad73cfc2e42282ccf9375fbd3a33a2c88c4f05cd9ca3ad8a2f2138d
---
- Update the visualization URL base for Share OpenDevin
---
=> frontend: update url for share opendevin trajectory visualization

.github/ISSUE_TEMPLATE/bug_template.yml, CONTRIBUTING.md, README.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/intro.mdx, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/troubleshooting/troubleshooting.md, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/intro.mdx, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/troubleshooting/troubleshooting.md, docs/modules/usage/troubleshooting/troubleshooting.md, opendevin/core/const/guide_url.py
None of the docs links work. This fixes them.
=> fix docs links

frontend/.husky/pre-commit
Update the husky pre-commits according to [`husky`'s latest update](https://github.com/typicode/husky/releases) (bump from #2996)
=> husky: Run package commands directly

pyproject.toml
=> chore: Release 0.8.1

opendevin/controller/agent_controller.py, opendevin/runtime/server/files.py, opendevin/runtime/server/runtime.py
Removes global config from files.py.
Part of #2758
=> Remove config from files

containers/app/Dockerfile
```plain
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)                                                     0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 13)                                                    0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 31)                                                    0.0s
```
---
---
=> Update Dockerfile casing

.github/workflows/run-unit-tests.yml
[Action link](https://github.com/OpenDevin/OpenDevin/actions/runs/10025171262/job/27708063377#step:6:386) 
---
Applied suggestion from https://github.com/lima-vm/lima/issues/124#issuecomment-886368863
---
https://github.com/abiosoft/colima/issues/381#issuecomment-1223561114
=> CI: Force stop colima

agenthub/codeact_agent/codeact_agent.py
Modify codeAct paper link.
---
---
=> Modify codeAct paper link

README.md
Our paper is finally released 😄
=> Update paper link in README.md

frontend/src/components/FileIcons.tsx, frontend/src/utils/utils.test.ts, frontend/src/utils/utils.ts
The existing `switch...case` setup bloated the component.
---
Reduce the component size and outsource/test the function for obtaining a files extension.
---
=> (test|refactor)(frontend): Refactor and test the `FileIcon` component

.github/workflows/ghcr-runtime.yml
Try to fix workflow: https://github.com/OpenDevin/OpenDevin/actions/runs/10100131182/job/27933167421
Based on: https://github.com/OpenDevin/OpenDevin/pull/3105
---
---
=> fix (ghcr push): add missing extension

.github/workflows/ghcr-runtime.yml
https://github.com/OpenDevin/OpenDevin/pull/3120 did not fixed the problem..
---
Fix the name of the tar file. (I hope this is the last ghcr push fix 😢 )
---
=> fix (ghcr-runtime): fix filename for docker image tar

docs/modules/usage/llms/localLLMs.md
A command in the docs was fixed, the changes are very minor, but will help new users.
=> [Docs] fixed broken shell command

evaluation/swe_bench/scripts/docker/pull_all_eval_docker.sh
---
Support SWE-Bench pull from custom namespace
---
=> [Eval] Support SWE-Bench pull from custom docker namespace

agenthub/dummy_agent/agent.py
DummyAgent was broken for weeks and the CI test never failed, still.
---
Processing of steps in the agent fixed. Now it goes through all 9 steps.
Excerpt:
=> (fix) Fix DummyAgent (used in E2E test)

opendevin/runtime/client/README.md
---
- move arch diagram to the front
- update the documentation with recent changes
---
=> [docs] Update README.md for new OpenDevin Runtime

pyproject.toml
=> chore: Release 0.8.2

evaluation/swe_bench/run_infer.py, evaluation/swe_bench/swe_env_box.py
Fix config parameter passing for SWE-bench sandbox.
Ref: https://github.com/OpenDevin/OpenDevin/pull/3099 refactored SWEBenchSSHBox to use a mandatory config parameter.
=> Fix swe-bench sandbox config parameter

docs/modules/usage/custom_sandbox_guide.md
Added a consideration note for nikolaik docker images as base for custom images.
Helps #3185 
---
https://hub.docker.com/r/nikolaik/python-nodejs
=> (docs) Update custom sandbox guide: added nikolaik image consideration

README.md, pyproject.toml
=> Release 0.8.3

frontend/src/components/file-explorer/ExplorerTree.tsx, frontend/src/components/file-explorer/FileExplorer.tsx
Currently, we don't show the file explorer if there are 0 files in the workspace. That prevents you from e.g. uploading a file
---
Now we show the file explorer with a zero-state explaining that there are no files
---
=> better zero state for file list

poetry.lock, pyproject.toml
I tried to set up from scratch today, and hit an error with `jwt` missing.
---
Adds `pyjwt` to the pyproject.toml
---
=> Add pyjwt to pyproject

poetry.lock
---
Bump the SWE-Bench version to the latest commit. It increases our latest CodeAct v1.8 score from 78 to 80 resolved (26.67%)!
---
=> Bump swebench version

tests/integration/README.md
---
Update integration tests README.md to reflect recent changes in EventStreamRuntime integration tests.
---
=> Update integration tests README.md

README.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/about.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/intro.mdx, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/about.md, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/intro.mdx, docs/modules/usage/about.md, docs/modules/usage/custom_sandbox_guide.md, docs/modules/usage/intro.mdx, docs/modules/usage/openshift-example.md, docs/src/components/CustomFooter.tsx, docs/src/pages/faq.tsx
People were complaining that the slack link wasn't working, so this updates with a new one that should work.
=> Update slack link

docs/modules/usage/evaluation_harness.md
---
- Fix copy-pasta from Claude 😓 
- Add Emoji for title
---
=> [docs] Clean up evaluation docs

docs/docusaurus.config.ts, docs/modules/usage/runtime.md, docs/package-lock.json, docs/package.json
---
- make sure mermaid flowchart is displayed correctly
---
=> (docs) make sure mermaid flowchart is displayed correctly

.github/workflows/clean-up.yml, .github/workflows/deploy-docs.yml, .github/workflows/dummy-agent-test.yml, .github/workflows/ghcr.yml, .github/workflows/lint.yml, .github/workflows/review-pr.yml, .github/workflows/run-unit-tests.yml, .github/workflows/solve-issue.yml
No does not fix any issues.
---
Functionally I did not change anything.
* Made all the workflows consistent in terms of formatting.
* No empty line between steps
* Single quotes for strings
* An empty line between workflow "name", "concurrency", "on", and different jobs
* Added high level comments on what the workflow does
* Added comments for jobs on workflows that contain multiple jobs
---
=> Make all workflows consistent formatting and some more comments

frontend/src/index.css
Lists in the message content were not properly rendered. In particular, consecutive line breaks and bullet points were not shown.
---
Adjustment of the CSS to allow for proper formatting of lists and line breaks.
---
Example
content="Title\n\n*Item1\n*Item2"
=> fix: correct list rendering for chat window

frontend/README.md, opendevin/server/README.md
I found the existing instructions a little difficult to follow for getting the projects running - there were some missing steps. I updated the readme to hopefully cover these and help folks get up and running faster.
=> Chore Readme updates

containers/runtime/config.sh, opendevin/runtime/utils/runtime_build.py
Add comments to the runtime_build script so it can be followed a little bit easier. I wanted to understand this script as I was looking into the flaky test and thought maybe this will help the next person.
---
---
=> Add comments to the runtime_build script

tests/unit/test_condenser.py
Adds tests to the memory condenser to increase test coverage.
(commit by OpenDevin)
=> Add unit tests for MemoryCondenser in test_condenser.py

agenthub/codeact_swe_agent/codeact_swe_agent.py
Follow-up on https://github.com/OpenDevin/OpenDevin/pull/3383
If we now need ErrorObservation in CodeAct, we likely need it in CodeAct SWE as well.
Even if it won't occur for it, the alternative is missing it and that's hard to debug, so I think we may as well have it in. We didn't need it for CodeAct for long, after all, and then we suddenly did with the new runtime. 
Please note that I couldn't yet replicate the issue in the other PR, so I'm not sure it fixes it.
=> Add error obs to codeact SWE

opendevin/core/main.py, opendevin/llm/llm.py
Quick logging fixes
- fix https://github.com/OpenDevin/OpenDevin/issues/3377
- the funniest python bug... indentation of course 😅 
- fix the wrong logging of an exception (crashes runs on cli)
=> Two small logging fixes

docs/modules/usage/custom_sandbox_guide.md, docs/modules/usage/evaluation_harness.md, opendevin/README.md
---
- Add imports to eval harness docs
- Remove out-dated technical content on the custom sandbox guide and link to updated runtime description
---
=> docs: improve documentation

agenthub/README.md, opendevin/controller/agent_controller.py, opendevin/controller/state/state.py
Added docstrings for `agent_controller` and `state`, adjusted and added to the agent Readme.
=> Additions to agent docs

frontend/src/index.css
Numbered lists in chat messages were missing the numbers.
---
Tweak some CSS.
Follow up to #3273
=> tweaks to chat message CSS stylings for lists

README.md
Fix "Credits" icon in README.md
---
---
=> chore: fix "Credits" in README.md

docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/llms/localLLMs.md, docs/modules/usage/llms/local-llms.md
=> Leftover from renaming

.github/workflows/ghcr_app.yml, tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython_module/prompt_002.log, tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython_module/prompt_003.log, tests/integration/mock/eventstream_runtime/CodeActAgent/test_ipython_module/prompt_004.log, tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython_module/prompt_002.log, tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython_module/prompt_003.log, tests/integration/mock/eventstream_runtime/CodeActSWEAgent/test_ipython_module/prompt_004.log
=> fix: integration tests

.github/workflows/ghcr_app.yml, .github/workflows/ghcr_runtime.yml
---
Fix push CI image again 😢
---
=> fix: CI push image

.github/workflows/ghcr_app.yml
=> fix: last_tag of matrix in CI

opendevin/core/const/guide_url.py
There's one file left from the renaming, will remove it now.
---
---
=> chore: remove extra guide url file

README.md
This PR acknowledges that this repo used to be called OpenDevin, to reduce confusion for those who may have heard of OpenDevin before.
=> Update README.md to acknowledge OpenDevin

frontend/package-lock.json, frontend/package.json
The frontend package files still had 0.1.0 in it, bumped to 0.8.3.
=> (fix) bump frontend version from 0.1.0 to 0.8.3

Makefile, README.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/intro.mdx, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/llms/localLLMs.md, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/intro.mdx, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/llms/localLLMs.md, docs/modules/usage/how-to/openshift-example.md, docs/modules/usage/llms/azure-llms.md, docs/modules/usage/llms/local-llms.md, evaluation/swe_bench/run_infer.py, evaluation/swe_bench/scripts/setup/prepare_swe_utils.sh, openhands/runtime/utils/runtime_build.py
Textual replacements for opendevin (mostly links).
(replaces previous PR attempt #3473 )
=> (fix) Rename last opendevin occurences

openhands/runtime/utils/runtime_templates/Dockerfile.j2, poetry.lock, pyproject.toml
Attempting to use Anthropic models via Vertex fails with dependency error.
Fixes #3505 (ideally 😁 )
---
Added an additional dependency to the `pyproject.toml` file.
---
https://docs.anthropic.com/en/api/claude-on-vertex-ai#install-an-sdk-for-accessing-vertex-ai
=> (fix) add Anthropic dependency for Vertex

README.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/about.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md, docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/intro.mdx, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/about.md, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md, docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/intro.mdx, docs/modules/usage/about.md, docs/modules/usage/how-to/custom-sandbox-guide.md, docs/modules/usage/how-to/openshift-example.md, docs/modules/usage/intro.mdx, docs/src/components/CustomFooter.tsx, docs/src/components/HomepageHeader/HomepageHeader.tsx
Slack link expired again. I set it to no expiration this time
---
---
=> fix slack links

.github/workflows/ghcr_app.yml, .github/workflows/ghcr_runtime.yml
* This should make all main commits run all workflows
* The create manifest step was doing everything the same except for a single command so I merged it into push
---
---
=> Remove concurrency and cleanup workflows

evaluation/aider_bench/README.md, evaluation/aider_bench/create_dataset.py, evaluation/aider_bench/helper.py, evaluation/aider_bench/run_infer.py, evaluation/aider_bench/scripts/run_infer.sh, evaluation/aider_bench/scripts/summarize_results.py
=> [Feat] Aider Benchmark

openhands/runtime/client/client.py
occurence -> occurrence
---
---
=> chore: update client.py

README.md, frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.9.0

frontend/src/components/terminal/Terminal.test.tsx, frontend/src/hooks/useTerminal.ts, frontend/src/utils/parseTerminalOutput.test.ts, frontend/src/utils/parseTerminalOutput.ts
Parses the new terminal output to reduce terminal clutter and better UI. Resolves #3557
---
Parses the output into the actual output and symbol.
---
=> feat: parse new terminal output

.github/workflows/ghcr_app.yml, .github/workflows/ghcr_runtime.yml, containers/build.sh
Forked PRs don't have permission to push to our GHCR repo. 
---
This changes the workflow in those cases to only build the image.
---
=> [WIP] Fix docker push issues

docs/modules/usage/about.md, docs/modules/usage/agents.md, docs/modules/usage/architecture/runtime.md, docs/modules/usage/feedback.md, docs/modules/usage/how-to/custom-sandbox-guide.md, docs/modules/usage/how-to/evaluation-harness.md, docs/modules/usage/how-to/openshift-example.md, docs/modules/usage/llms/llms.md, docs/modules/usage/troubleshooting/troubleshooting.md, docs/modules/usage/troubleshooting/windows.md
More consistent documentation
---
* Made documentation more consistent in terms of formatting
* Removing unnecessary sections, sentences and words
---
=> docs: More consistent documentation

evaluation/swe_bench/run_infer.py, evaluation/swe_bench/scripts/setup/instance_swe_entry.sh, openhands/runtime/client/client.py
EOF fixes for SWE-Bench evaluation
---
* Fix EOF error when running SWE-Bench Eval
* Close runtime for each instance run
---
=> (eval) EOF fixes for SWE-Bench evaluation

openhands/runtime/builder/docker.py, openhands/runtime/utils/runtime_build.py
Startup handling and logging of docker images tweaked to be clearer to user.
---
Docker image was potentially pulled even though it already existed locally.
Improved logging of steps so there is no impression of some process hanging during startup.
---
Helps #3551  #3644
=> (fix) startup handling and logging of docker images tweaked

.github/workflows/ghcr_app.yml, .github/workflows/ghcr_runtime.yml, .github/workflows/stale.yml
Issues with tracked label should not go stale.
---
---
=> Added stale exemption for tracked issues

agenthub/codeact_agent/micro/github.md
Micro agent: improve `github.md` with more API commands with less code duplication.
---
Overall added a couple more useful API commands, but reduced repeated code/URL duplication by introducing a baseline command and appropriate instructions.
At least Sonnet told me it is all understandable and was able to produce example code to make use of it.
---
Follow up to #3511
=> Micro agent: improve github.md with more API commands (CodeActAgent)

frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.9.1

.github/workflows/regenerate_integration_tests.yml, README.md
Confirmed that the commit back to the repo works!
---
This PR actually implements regenerate.sh. Users can manually trigger the regeneration via the Actions tab in GitHub
---
=> implement GitHub action for integration regeneration

Makefile, openhands/memory/memory.py
- add another four embed models Ollama supports.
=> feat: add more embed models that Ollama supports recently

evaluation/README.md
=> fix eval README link

README.md
Add the github trending top1 logo into readme.
---
---
=> Docs: add logo to repo

frontend/src/components/file-explorer/TreeNode.tsx
- FIX: Files now display updated content
Resolves #3580
=> fix(frontend): Files display updates

README.md, frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.9.2

frontend/src/components/modals/feedback/FeedbackModal.tsx, frontend/src/utils/utils.ts
=> hotfix(frontend): Remove unwanted (large) keys when sharing feedback

README.md, docs/modules/usage/getting-started.md, docs/modules/usage/how-to/cli-mode.md, docs/modules/usage/how-to/custom-sandbox-guide.md, docs/modules/usage/how-to/headless-mode.md
* The CLI and headless commands for the docker method were not correct
* Added export when setting WORKSPACE_BASE
---
---
=> docs: fix cli and headless commands

README.md, docs/modules/usage/getting-started.md
The current runtime tags seem to be broken, I believe due to an architecture issue. These tags should work better.
---
---
=> fix runtime image

README.md, docs/modules/usage/getting-started.md
Changes the suggested runtime image in the default instructions.
Turns out we're publishing these runtime tags properly! This is a better path forward.
---
---
=> fix runtime tags in docs

docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/llms/localLLMs.md
You don't have to understand Chinese to review this PR :)
=> Fix wrong mention of Devin in localLLMs.md

README.md, docs/src/components/HomepageHeader/HomepageHeader.tsx, evaluation/README.md, evaluation/miniwob/README.md, evaluation/swe_bench/README.md, evaluation/webarena/README.md
=> fix link for huggingface evaluation benchmark

frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.9.3

docs/modules/usage/llms/azure-llms.md, docs/modules/usage/llms/google-llms.md, docs/modules/usage/llms/groq.md, docs/modules/usage/llms/openai-llms.md, docs/sidebars.ts
Add Groq to the documentation
---
* This was originally done by enyst but missed this sidebar change so it shows up
* Made all LLM docs consistent 
---
=> Missed adding Groq to sidebar so it shows up

openhands/runtime/builder/docker.py
Update Docker pull data in place, instead of outputting data for the same layer on different lines.
---
- output docker pull infos in-place
---
this is current docker pull output, same layer outputs on different lines:
after added in-place output:
=> (enh) Update Docker pull data in place

docs/modules/usage/llms/azure-llms.md, docs/modules/usage/llms/google-llms.md, docs/sidebars.ts
Add providers section in documentation and put current docs under it
---
This adds a Providers section under the LLMs which is more accurate
---
=> Add providers section in documentation and put current docs under it

evaluation/swe_bench/README.md
=> Small fix in readme

docs/sidebars.ts
Reorder sidebar doc by bringing LLMs higher up
---
Just putting LLM higher because it makes more sense this way
---
=> Reorder sidebar doc by bringing LLMs higher up

Development.md, Makefile, compose.yml, containers/dev/Dockerfile, containers/dev/README.md, containers/dev/compose.yml, containers/dev/dev.sh
Add docker files for developing inside container.
---
+ docker files are added for building inside the container. This eliminates all requirements but the Docker itself,
another way for building this app.
+ Set conditional default for BACKEND_HOST in Makefile and rename the original to BACKEND_HOST_PORT. this is to allow access to the backend server from host so `make docker-run` works inside container as-is.
+ New targets make docker-run/make docker-dev
---
None.
=> chore: Add docker files for developing inside container.

docs/src/css/custom.css
Some links aren't appearing underlined. This should fix it
---
---
=> fix documentation links

openhands/runtime/builder/docker.py
After pull the image from function `image_exists()`, the same pull process appeared in `build()` function, which outputed numerous log infos of downloading process. So I unified the whole log output.
the log is as follows:
whole log:
[docker_pull.log](https://github.com/user-attachments/files/17062885/docker_pull.log)
after unified, they looks like:
docker pull from  function  `image_exists():
docker pull from `build()`:
---
- unify the log output in docker build process
---
=> (enh) unify the log output in docker build process

evaluation/swe_bench/eval_infer.py, evaluation/swe_bench/scripts/eval/convert_oh_output_to_swe_json.py
=> [eval] fix evaluation git patch post-processing

frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.9.4

docs/modules/usage/llms/azure-llms.md, docs/modules/usage/llms/google-llms.md, docs/modules/usage/llms/groq.md, docs/modules/usage/llms/llms.md, docs/modules/usage/llms/openai-llms.md, docs/modules/usage/llms/openrouter.md, docs/sidebars.ts
Add OpenRouter provider docs
---
* Add OpenRouter provider docs
* More consistency across llm provider docs
---
=> Add OpenRouter provider docs

evaluation/swe_bench/README.md
=> [eval] update swe_bench/README.md

openhands/runtime/README.md
This PR adds some mention of the different runtime types to the runtime README.md
=> Update README.md for runtime

evaluation/utils/shared.py
Another attempt to solve the "hanging" issue towards the end of each evaluation runs..
---
Replace `ProcessPoolExecutor` with more low-level `mp.Pool` with the hope that it will be little bit more "bug-free" 😢 
---
=> [eval] use mp Pool instead ProcessPoolExecutor

docs/modules/usage/getting-started.mdx, frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.9.5

agenthub/codeact_agent/README.md
---
- Cleanup some out-of-dated content
---
=> Update README.md for CodeAct

docs/modules/usage/llms/llms.md, openhands/llm/async_llm.py, openhands/llm/debug_mixin.py, openhands/llm/llm.py, openhands/llm/retry_mixin.py, openhands/llm/streaming_llm.py, tests/integration/conftest.py, tests/unit/test_acompletion.py, tests/unit/test_llm.py
Refactor llm.py
---
This PR proposes a refactoring of llm.py to split out:
- specific features (async completion, streaming) 
- and specific concerns (prompt/response logging, retries).
I admit, personally I love it being half the amount the code. 😅 
- also, removed the disabling of Gemini safety settings, since they're now disabled by default and I see providers have updated the Gemini version
I can confirm that retries and logging work. Async/streaming are not currently in use. I believe we have unit tests for them.
Please note I need to check Gemini.
=> Refactor llm.py

README.md, docs/modules/usage/getting-started.mdx, frontend/package.json, pyproject.toml
Updates versions to 0.9.6. Also explicitly does a `docker pull` before running the app, to ensure runtime matches the app
---
---
=> Release 0.9.6

evaluation/swe_bench/scripts/eval_infer.sh
---
fix eval_infer.sh to correctly copy SWE-Bench logs
---
=> fix eval_infer.sh to correctly copy SWE-Bench logs

frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.9.7

openhands/server/session/agent_session.py
Better error messages when sessions fail to start
---
We were swallowing errors in the coroutine here--this (I think) should help. CC @tofarr for pointers
---
=> Handle errors when starting session

docs/sidebars.ts
Restructure documentation to be in an easier-to-follow format
---
Mostly self-explanatory, see #4136 for details
---
Fixes #4136
=> Fix issue #4136: 'Restructuring documentation'

openhands/linter/utils/__init__.py, openhands/linter/utils/cmd.py, openhands/runtime/browser/browser_env.py, openhands/runtime/builder/remote.py, openhands/runtime/client/client.py, openhands/runtime/remote/runtime.py, openhands/runtime/utils/request.py, openhands/runtime/utils/runtime_build.py, openhands/runtime/utils/shutdown_listener.py, openhands/server/session/session.py, pyproject.toml, tests/unit/linters/conftest.py
Run pre-commit checks on all files.
---
We have pre-commit checks, but apparently they had not been run on all files. This PR runs pre-commit on all files, fixing some residual linting issues, etc.
=> Run pre-commit

.github/pull_request_template.md
---
Small reordering of PR template
---
=> Small reordering of PR template

openhands/server/session/agent_session.py
max_interations -> max_iterations
=> chore: update agent_session.py

frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.9.8

.github/workflows/ghcr-build.yml, containers/build.sh
no need for release notes
---
See https://github.com/orgs/community/discussions/26325 for context
I noticed that the SHA tag on the images I was building was totally incorrect during PRs 🙃 This should fix it
---
=> Fix for sha detection for docker tags

openhands/llm/async_llm.py, openhands/llm/llm.py
---
Small fix to use the right variant of litellm completion for the async_llm.
---
=> Fix to use async variant of completion

CREDITS.md
Corrected possessive form, improved sentence clarity, and ensured consistency in terminology within the CREDITS.md file.
=> Fix grammar, typos, and consistency in CREDITS.md

README.md
---
Update README to installation guides for system requirements
---
=> Update README to installation guides for system requirements

docs/modules/usage/getting-started.mdx
---
Small changes to getting started
---
=> Small changes to getting started

frontend/README.md
---
Updates the README according to the new changes
---
=> docs(frontend): Update README

frontend/src/routes/app.tsx
There are some cases when the user attempts to use the app with an outdated stored token 
---
- End session (clear token) and redirect to the main screen when the server returns an invalid token error
---
Resolves #4257
=> fix(frontend) End session and redirect to main screen if token is invalid

frontend/src/root.tsx
---
Sets a min width in the root route. Smaller screens now have to horizontally scroll the screen rather than view squished elements. 
---
Resolves #4256
=> fix(frontend): Set min width so it doesn't squish on smaller screens

frontend/src/components/project-menu/ProjectMenuCard.tsx, frontend/src/routes/app.tsx
---
Updates the push to GitHub action prompt
---
=> chore(frontend): Update push to GH action prompt

frontend/src/components/modals/modal-backdrop.tsx
---
Backdrop opacity increased from 50% to 80%
**BEOFRE:**
**AFTER:**
---
=> style(frontend): Make modal backdrop darker

.github/ISSUE_TEMPLATE/bug_template.yml
Update issue template to make it less noisy
---
It was mentioned that the issue template is quite daunting so hopefully this makes it more simple
---
=> Update issue template to make it less daunting

.github/workflows/deploy-docs.yml, .github/workflows/dummy-agent-test.yml, .github/workflows/fe-unit-tests.yml, .github/workflows/ghcr-build.yml, .github/workflows/lint.yml, .github/workflows/py-unit-tests.yml
Cancel previous commit builds on PRs but not on main
---
---
=> Cancel previous commit builds on PRs but not on main

Development.md, tests/unit/test_agent_skill.py
---
Added an explanation about how to use a pre-built image when running the app (in any of the ways to run open hands).
This is something that can shorten the run time when in development mode where changes were not made in the runtime client component.
I have also remove a method that appeared twice in a test function
---
This is created after a discussion in the Q&A Discord channel [link to thread](https://discord.com/channels/1222935860639563850/1222936861534720021/threads/1293263832310874256)
@neubig FYI
=> Add docs about using pre-built image + remove duplicated method

frontend/src/routes/app.tsx
As indicated in the Figma designs, the chat interface does not have a header label.
---
=> feat(frontend): Remove chat interface header label

frontend/package-lock.json, frontend/src/components/account-settings-context-menu.tsx, frontend/src/components/context-menu/context-menu-list-item.tsx, frontend/src/components/user-avatar.tsx
As suggested by Paul, when the user clicks on the user avatar, always open the context menu even when the user is not logged in.
---
Any feedback and suggestions are welcomed.
=> feat(frontend): Always show user context menu

openhands/runtime/client/runtime.py
---
**Fix for regression made this morning**
The logger statement was being called incorrectly.
=> Fix build error

tests/unit/test_runtime_build.py
**Faster unit tests.**
---
We should test only our own code in unit tests. (If we need end to end testing, integration tests is the place for this). By effective use of mocks to test only our own code, we speed up our tests and therefore our builds.  Local changes have shown this takes ~15 seconds of the test time (When using a single worker).
I'd like to expand this out to our other tests. After this, the slowest are (measured using --duration):
```
5.25s setup    tests/unit/test_memory.py::test_add_event_with_action
3.28s call     tests/unit/test_security.py::test_unsafe_python_code
3.11s call     tests/unit/test_memory.py::test_add_event_increment_thought_idx
2.41s call     tests/unit/test_security.py::test_unsafe_bash_command
2.02s call …
```
=> Feat Faster unit tests

tests/unit/test_async_utils.py
**Removed flaky test**
---
I had an alarm in my head after adding this one yesterday - tests based on time are often a problem. Removing this test until I can come up with a better one.
=> Fix: Removed flaky test

frontend/src/routes/_oh._index/route.tsx
This PR adds the workflow scope to the GitHub authentication URL, allowing the application to access GitHub Actions workflows.
=> Add workflow scope to GitHub authentication URL

.github/workflows/py-unit-tests.yml
This PR proposes to bump Mac version to macOS-14, we were using a really old version now
=> Bump Mac version in CI

frontend/src/routes/_oh.tsx
App throws and does not recover after #4423
---
- Add fallback
---
=> fix(frontend): Catch config fetch error and set default fallback

Makefile
no changelog
---
`npm run start` runs a prod-ish frontend. We probably want to run the dev frontend
This also fixes the current setup, where FE traffic isn't proxied properly
---
=> run in dev mode in makefile

README.md, docs/modules/usage/how-to/cli-mode.md, docs/modules/usage/how-to/headless-mode.md, docs/modules/usage/installation.mdx, frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.10.0

CONTRIBUTING.md
no changelog needed
---
This removes some of the GH-specific docs in favor of an external article. It also lists out a few ways that people might want to contribute
---
=> update contributing docs

README.md
Update leftover versions. Too many of these but forgot the most important one 
---
---
=> Update leftover versions

frontend/src/utils/user-is-authenticated.ts
---
Prevents the user from being redirected to `/waitlist` in a dev environment 
---
=> fix(frontend): Fix waitlist logic

evaluation/README.md
---
This PR updates the structure of the evaluation README.md to make it a bit more clear where to look for information that is useful to specific types of people.
=> Update evaluation README.md structure

frontend/__tests__/components/context-menu/account-settings-context-menu.test.tsx, frontend/__tests__/components/context-menu/context-menu-list-item.test.tsx, frontend/__tests__/components/settings/ai-config-form.test.tsx, frontend/__tests__/components/settings/dropdown-input.test.tsx, frontend/__tests__/components/settings/model-selector.test.tsx, frontend/__tests__/components/user-actions.test.tsx, frontend/__tests__/components/user-avatar.test.tsx, frontend/__tests__/hooks/use-click-outside-element.test.tsx, frontend/__tests__/routes/_oh.test.tsx, frontend/src/components/account-settings-context-menu.tsx, frontend/src/components/context-menu/account-settings-context-menu.tsx, frontend/src/components/context-menu/context-menu-list-item.tsx, frontend/src/components/context-menu/context-menu.tsx, frontend/src/components/modals/LoadingProject.tsx, frontend/src/components/user-actions.tsx, frontend/src/components/user-avatar.tsx, frontend/src/routes/_oh.tsx
---
- Create multiple test todos
- Break down old `UserAvatar` to `UserAvatar` and `UserActions`
- Test test test
---
=> test(frontend): User actions and friends

frontend/src/routes/_oh._index/route.tsx
=> [ALL-469] fix(frontend): Indicate that import projects require zips

frontend/src/api/open-hands.ts
=> [ALL-597] fix(frontend): Fetch `config.json` locally

README.md, docs/modules/usage/how-to/cli-mode.md, docs/modules/usage/how-to/headless-mode.md, docs/modules/usage/installation.mdx, frontend/package-lock.json, frontend/package.json, pyproject.toml
=> Release 0.11.0

frontend/src/api/open-hands.ts, openhands/server/listen.py
Bugfix for loading the `/app` page directly
---
Makes sure we load the app for any route that isn't explicitly an API route
---
=> add catch all route, disable caching

evaluation/mint/tasks/reasoning.py, openhands/agenthub/codeact_agent/codeact_agent.py, openhands/agenthub/codeact_swe_agent/codeact_swe_agent.py, openhands/controller/stuck.py, openhands/events/serialization/utils.py, openhands/runtime/impl/remote/remote_runtime.py
=> Refactor: shorter syntax

openhands/controller/agent_controller.py
no changelog
---
This log is spamming every second
---
=> Remove verbose log from agent controller

openhands/llm/llm.py
no changelog
---
We're occasionally seeing this field missing in the response, causing a crash
---
=> safer model info access

frontend/src/routes/_oh.app.tsx
---
In a lot of cases, the agent using the new sonnet would assume the files are stored at /repo. This PR add additional details in the initial message the agent: tell it to find the files in /workspace
---
=> feat: provide directory information to the agent from FE

poetry.lock, pyproject.toml
---
We use a fix commit version of litellm earlier due to this issue: https://github.com/BerriAI/litellm/issues/6422
Now that issue have been resolved & fixes are released into a new version. We can bump the version now.
Locally tested & integration tests are working.
---
=> chore: bump the litellm version

README.md
no changelog
---
Some leftovers from the recent docs merge
---
=> minor cleanup in readme

openhands/server/data_models/resolver.py, openhands/server/listen.py, tests/unit/test_listen.py
=> Refactor resolver endpoints to use data models

openhands/llm/llm.py
=> style: remove extra newline in LLM wrapper function

openhands/llm/llm.py
=> feat: add return type hints to LLM class methods

frontend/src/components/expandable-message.tsx
- Initialize showDetails to false
- Fix template literals in CSS classes
- Add translations for show/hide details buttons
=> Fix ExpandableMessage component

openhands/resolver/README.md
Add note about custom configurations
---
This is important since LLM_MODEL was moved to variables.
---
=> Add note about custom configurations

evaluation/benchmarks/the_agent_company/scripts/summarise_results.py
This is a follow-up of #5731 . The script is adapted from https://github.com/TheAgentCompany/TheAgentCompany/blob/main/evaluation/summarise_results.py. The only difference is this script removes the dependency of TheAgentCompany repo, and thus doesn't generate categorical analysis based on services.
---
---
=> [Evaluation] Add summarise_results script for TheAgentCompany benchmark

openhands/agenthub/codeact_agent/codeact_agent.py, openhands/llm/llm.py
---
better json parse in logger
---
=> chore(log): better json parse

frontend/src/components/agent-status-map.constant.ts, frontend/src/components/features/chat/chat-interface.tsx, frontend/src/i18n/translation.json, frontend/src/types/agent-state.tsx, openhands/controller/agent_controller.py, openhands/core/schema/agent.py, pyproject.toml
=> feat: Added RateLimitError status on UI and Agent state

openhands/llm/llm.py
---
Made FC the default option for GPT-4o
---
=> [Fix] Restored FC default for GPT-4o

Development.md
---
This PR fixes an obvious mistake in the documentation
---
=> Fix typo in Development.md

tests/unit/test_agent_controller.py
---
Adds test for the agent controller that ensures we handle `ContextWindowExceededError` without failure.
---
See #6475.
=> Add test for context window truncation in agent controller

openhands/events/stream.py, openhands/server/session/agent_session.py
This is a PR into Stephan's PR
=> better secrets hiding

openhands/core/config/sandbox_config.py
Fix parse config `docker_runtime_kwargs = { privileged = true }`
=> Support docker_runtime_kwargs dict

openhands/runtime/impl/daytona/README.md
Improvements to the Daytona runtime README to make it easier for users to get started
---
Quick start is an optional way to get started where the user doesn't have to manually enter the release version - "hardcoding" the release version here would make it so this file needs to get updated continuously.
---
=> chore: update daytona readme

openhands/runtime/impl/daytona/README.md
Adds more verbosity to quick start for Daytona runtime
---
Sorry about opening two similar PRs in a row - I'd been told the instructions weren't clear enough :)
=> chore: daytona readme quick start verbosity

evaluation/benchmarks/gorilla/ast_eval_hf.py, evaluation/benchmarks/gorilla/ast_eval_tf.py, evaluation/benchmarks/gorilla/ast_eval_th.py, evaluation/benchmarks/gorilla/utils.py
=> Openhands fix issue 7091

evaluation/benchmarks/commit0/README.md, evaluation/benchmarks/commit0/run_infer.py, evaluation/benchmarks/commit0/scripts/run_infer.sh
---
1. Rename `commit0_bench` to `commit0`
2. fix existing bug when evaluating `commit0`
---
=> rename commit0_bench to commit0

evaluation/benchmarks/commit0/README.md
---
The link now points to the correct arxiv site.
---
=> Added link to paper in commit0 README

docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/runtimes.md, docs/modules/usage/runtimes.md
---
CC: @xingyaoww 
---
Fix #6771
=> Add doc for local runtime

openhands/agenthub/codeact_agent/codeact_agent.py, openhands/agenthub/codeact_agent/function_calling.py, openhands/agenthub/codeact_agent/tools/__init__.py, openhands/agenthub/codeact_agent/tools/bash.py, openhands/agenthub/codeact_agent/tools/str_replace_editor.py, tests/unit/test_codeact_agent.py
---
This PR handles the max tool description length of 1024 characters for OpenAI's models by maintaining a separate simplified version for them.
CC: @xingyaoww @enyst 
---
Fix #7167
=> Separate tool descriptions to support models with limited description length

.github/workflows/openhands-resolver.yml
---
Please merge this PR once a new release includes #7287 (probably v0.30.0?)
---
=> Update the resolver workflow once a new release includes #7287

openhands/memory/condenser/impl/llm_summarizing_condenser.py
Fixed typo in code which brokes the prompt 
=> fix: correct string concatenation in llm_summarizing_condenser.py

evaluation/benchmarks/swe_bench/scripts/swtbench/convert.py, openhands/integrations/github/github_service.py, openhands/integrations/gitlab/gitlab_service.py, openhands/runtime/impl/local/local_runtime.py, openhands/runtime/utils/files.py, openhands/server/routes/git.py, openhands/server/routes/public.py, tests/unit/resolver/github/test_pr_title_escaping.py, tests/unit/resolver/github/test_resolve_issues.py, tests/unit/resolver/github/test_send_pull_request.py, tests/unit/resolver/gitlab/test_gitlab_pr_title_escaping.py, tests/unit/resolver/gitlab/test_gitlab_resolve_issues.py, tests/unit/resolver/gitlab/test_gitlab_send_pull_request.py
The pre-commit command that lints the entire code has been failing for a while, this PR fixes it
---
---
=> Fix linting

openhands/agenthub/codeact_agent/codeact_agent.py
See issue description
---
---
Closes: #7963
=> Fix issue with "default" in tool schema for gemini-preview

openhands/runtime/impl/action_execution/action_execution_client.py
=> remove sse subsection accessor of McpConfig in action_execution_client

openhands/runtime/impl/docker/docker_runtime.py
=> fix: retry if Connection Timed out

openhands/llm/llm.py
Change `native_tool_calling` semantics as discussed in #8424
=> fix #8424: change native_tool_calling semantics

tests/unit/README.md
The file path on the original doc is missing.
---
---
=> docs: change to existing testing files

frontend/src/components/features/settings/app-settings/language-input.tsx, frontend/src/components/features/settings/git-settings/github-token-input.tsx, frontend/src/components/features/settings/git-settings/gitlab-token-input.tsx, frontend/src/components/features/settings/secrets-settings/secret-form.tsx, frontend/src/routes/llm-settings.tsx
---
Updated the input styles in the `/settings` page for better mobile responsiveness. I made sure to check and fix the styles in the saas mode for consistency. Please let me know if you have any suggestions on this PR.
| Before | After |
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/3dffc467-fe36-49d4-9670-d0fa0abd724c) | ![After](https://github.com/user-attachments/assets/3a76432f-4a79-4b93-a985-df66388868d8)
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/e9889760-8791-4962-a363-454d3d70ef78) | ![After](https://github.com/user-attachments/assets/9fcb382b-9135-4f22-8bd4-2f35ba0dc7d7)
|--------|-------|
| …
=> fix(frontend): fix mobile view of settings page

evaluation/README.md
=> Fix typo in evaluation README.md

evaluation/benchmarks/versicode/metric/compute_ism_pm_score.py
Description:  
This pull request refactors the `get_ISM` and `get_ISM_without_verification` functions in `compute_ism_pm_score.py` to improve code consistency and readability. The changes include:
- Standardizing the order of function arguments (`answer_code`, `model_output_list`, `answer_name`).
- Updating the regex search to use raw f-strings for better clarity and reliability.
- Minor code cleanup, such as commenting out redundant code and improving inline documentation.
=> Refactor: Improve Consistency in Function Signatures and Regex Usage in compute_ism_pm_score.py

README_JA.md, docs/README_JA.md
=> Add Japanese translations

.github/ISSUE_TEMPLATE/bug_template.yml
=> Add model name

frontend/__tests__/routes/home-screen.test.tsx, frontend/src/components/shared/modals/settings/model-selector.tsx, frontend/src/routes/app-settings.tsx, frontend/src/routes/home.tsx, frontend/src/routes/root-layout.tsx
When users resize the browser window to smaller screen sizes, a horizontal scrollbar appears, requiring them to scroll left and right to view the full content. This may lead to a suboptimal user experience, especially for users accessing the product on tablets or smaller devices.
**Reproduction steps:**
- On the home page, resize the browser window to a smaller screen width.
- On the settings page, do the same to observe the behavior.
- You can refer to the video below for more information:
You can refer to the video below for more information:
https://github.com/user-attachments/assets/d6628bd4-0884-4e3b-91f1-f848cb349680
---
**Summarize what the PR does, explaining any non-trivial design …
=> fix(frontend): Responsive issue - the horizontal scrollbar is showing when resizing the browser window

docs/usage/llms/local-llms.mdx
---
This PR adds setup instructions for using Arctic Inference with vLLM.
---
=> Add instruction to use Arctic Inference

openhands-ui/bun.lock, openhands-ui/components/dialog/Dialog.stories.tsx, openhands-ui/components/dialog/Dialog.tsx, openhands-ui/package.json
Implements dialog component
---
Implements dialog component
---
=> feat(ui): dialog component

openhands-ui/bun.lock, openhands-ui/components/button/Button.tsx, openhands-ui/components/checkbox/Checkbox.stories.tsx, openhands-ui/components/checkbox/Checkbox.tsx, openhands-ui/components/toast/Toast.stories.tsx, openhands-ui/components/toast/Toast.tsx, openhands-ui/components/toggle/Toggle.tsx, openhands-ui/package.json, openhands-ui/shared/types.ts
Custom toast component
---
Custom toast component
---
=> feat(toast): custom toast component

openhands-ui/components/accordion/Accordion.tsx, openhands-ui/components/accordion/components/AccordionHeader.tsx, openhands-ui/components/accordion/components/AccordionItem.tsx, openhands-ui/components/accordion/components/AccordionPanel.tsx, openhands-ui/components/button/Button.tsx, openhands-ui/components/checkbox/Checkbox.tsx, openhands-ui/components/chip/Chip.tsx, openhands-ui/components/dialog/Dialog.tsx, openhands-ui/components/divider/Divider.tsx, openhands-ui/components/input/Input.tsx, openhands-ui/components/interactive-chip/InteractiveChip.tsx, openhands-ui/components/radio-group/RadioGroup.tsx, openhands-ui/components/radio-group/RadioOption.tsx, openhands-ui/components/scrollable/Scrollable.tsx, openhands-ui/components/select/Select.tsx, openhands-ui/components/spinner/Spinner.tsx, openhands-ui/components/tabs/Tabs.tsx, openhands-ui/components/toast/Toast.tsx, openhands-ui/components/tooltip/Tooltip.tsx, openhands-ui/components/typography/BaseTypography.tsx, openhands-ui/package.json, openhands-ui/shared/types.ts, openhands-ui/shared/utils/clone-icon.ts
Add data test id support
---
Add data test id support
---
=> fix(ds): add test id support

Development.md
---
This PR addresses minor documentation issues in the Development.md file to improve readability and consistency.
---
**Link of any specific issues this addresses:** N/A
=> docs: fix typos and update section numbering in Development.md

frontend/src/components/shared/buttons/trajectory-action-button.tsx
We probably need to update the styles of the feedback buttons. They can be similar to the action panel buttons.
---
The PR update the styles of the feedback buttons.
We can refer to the video below for the output of the PR.
https://github.com/user-attachments/assets/b1ee706a-a917-430c-ba57-ee6a2dd9af21
---
=> feat(frontend): update the styles of the new feedback buttons (conversation ux improvements).

frontend/src/components/features/chat/git-control-bar-branch-button.tsx, frontend/src/components/features/chat/git-control-bar-repo-button.tsx, frontend/src/components/features/chat/git-control-bar.tsx
**Acceptance criteria:**
- The repo and branch chips should not have the fixed width.
---
---
=> feat(frontend): Update repo and branch chips width (chat input)

frontend/__tests__/components/features/conversation/conversation-name.test.tsx, frontend/src/components/features/context-menu/context-menu-separator.tsx, frontend/src/components/features/conversation/conversation-name-context-menu.tsx
The `conversation-name.test.tsx` file is currently failing.  
This PR addresses and fixes the broken tests.
---
This PR addresses and fixes the broken tests.
---
=> fix(frontend): conversation-name.test.tsx

frontend/src/routes/root-layout.tsx
We need to remove excessive top margin on page.
---
The PR removes excessive top margin on page
---
=> refactor(frontend): remove excessive top margin on page
